package com.yourstudio.hskstroke.bishun.ui.character

import java.util.Locale

private val frenchNavigationStrings = NavigationStrings(
    homeLabel = "Accueil",
    learnLabel = "Apprendre",
    libraryLabel = "Dictionnaire",
    accountLabel = "Paramètres",
)

private val frenchOnboardingStrings = OnboardingStrings(
    appTitle = "Hanzi",
    skipLabel = "Passer",
    backLabel = "Retour",
    nextLabel = "Suivant",
    startLabel = "Commencer",
    pages = listOf(
        OnboardingPageText(
            title = "Recherchez rapidement",
            body = "Cherchez l'ordre des traits et la prononciation hors ligne, quand vous en avez besoin.",
        ),
        OnboardingPageText(
            title = "Pratiquez avec guidance",
            body = "Tracez les traits et recevez des indices pour améliorer votre précision.",
        ),
        OnboardingPageText(
            title = "Dictionnaire intégré",
            body = "Ouvrez la fiche dictionnaire pour voir le pinyin et la définition sans quitter la pratique.",
        ),
        OnboardingPageText(
            title = "Widget quotidien",
            body = "Épinglez le widget sur l'écran d'accueil pour pratiquer en une touche.",
        ),
        OnboardingPageText(
            title = "Prononciation sécurisée",
            body = "Activez les rappels de volume pour éviter l'audio trop fort en public.",
        ),
    ),
)

private val frenchAccountStrings = AccountStrings(
    title = "Paramètres",
    signInCardTitle = "État de connexion",
    signInDescriptionSignedIn = "Connecté. Les achats restent liés à cet appareil.",
    signInDescriptionSignedOut = "Le mode invité garde les données hors ligne. Connectez-vous pour débloquer les cours.",
    signInButtonSignedIn = "Se déconnecter",
    signInButtonSignedOut = "Se connecter",
    courseCardTitle = "Déblocage des cours",
    courseDescriptionSignedOut = "Consultez les niveaux HSK. Connectez-vous pour acheter.",
    courseDescriptionUnlocked = "Tous les niveaux sont débloqués. Continuez depuis l'onglet Cours.",
    courseDescriptionLocked = "Un achat unique sauvegarde une licence locale pour un usage hors ligne.",
    courseButtonSignedOut = "Connexion requise",
    courseButtonUnlocked = "Voir les cours",
    courseButtonLocked = "Débloquer tous les cours",
    supportTitle = "Support",
    supportDescription = "Aide et informations de confidentialité.",
    supportFeedbackButton = "Envoyer un commentaire",
    clearDataTitle = "Réinitialiser les données",
    clearDataDescription = "Supprimer l'historique, la progression et les préférences de cet appareil.",
    clearDataButton = "Effacer les données",
    clearDataDialogTitle = "Effacer les données locales ?",
    clearDataDialogBody = "Cette action supprime l'historique, les séries, les préférences et les recherches. Irréversible.",
    consentSignInTitle = "Avant de se connecter",
    consentSignInBullets = listOf(
        "La connexion sert uniquement à associer les achats. Les données restent sur l'appareil.",
        "Continuer confirme que vous avez lu la politique de confidentialité.",
        "Vous pouvez rester en mode invité — les cours premium resteront verrouillés.",
    ),
    consentSignInConfirm = "Accepter et se connecter",
    consentUnlockTitle = "Débloquer les cours premium",
    consentUnlockBullets = listOf(
        "Les jetons de paiement sont mis en cache localement pour un usage hors ligne.",
        "Le déblocage enregistre l'achat pour une restauration ultérieure.",
        "Un rappel de confidentialité apparaîtra lors du paiement.",
    ),
    consentUnlockConfirm = "Confirmer le déblocage",
    consentCheckboxLabel = "J'ai lu la politique de confidentialité.",
    cancelLabel = "Annuler",
    closeLabel = "Fermer",
    proCardTitle = "Pro",
    proStatusPro = "Pro",
    proStatusFree = "Gratuit",
    proStatusPlayRequired = "Google Play requis",
    proStatusPending = "Achat en attente",
    proStatusConnecting = "Connexion\u2026",
    proStatusNotAvailable = "Non disponible",
    proDescriptionPro = "Merci de soutenir l'application. Pro fonctionne hors ligne et se restaure automatiquement.",
    proDescriptionNoPlayStore = "L'achat Pro nécessite Google Play. Installez depuis le Play Store.",
    proDescriptionFree = "Soutenez l'application avec un achat unique. Pro se restaure automatiquement via Google Play.",
    proBillingStatusCodeFormat = "Code de facturation : %1\$d",
    proRestorePurchasesButton = "Restaurer les achats",
    proBuyButton = "Acheter",
    proBuyButtonWithPriceFormat = "Acheter (%1\$s)",
    appearanceCardTitle = "Apparence",
    appearanceCardDescription = "Personnalisez l'affichage.",
    themeModeSystemLabel = "Système",
    themeModeLightLabel = "Clair",
    themeModeDarkLabel = "Sombre",
    accentColorLabel = "Couleur d'accent",
    brushThicknessLabel = "Épaisseur du trait",
    requiresProChipLabelFormat = "%1\$s · Pro",
    accentColorOptionLabels = listOf(
        "Lilas", "Bleu saphir", "Vert écume",
        "Rose argenté", "Brun cookie", "Brun gingembre",
        "Rose œillet foncé", "Rouge violet moyen",
    ),
    brushWidthOptionLabels = listOf("Fin", "Normal", "Épais"),
    audioSafetyTitle = "Sécurité audio",
    audioSafetyDescription = "Rappel avant la lecture à volume élevé.",
    audioSafetyVolumeReminderLabel = "Rappel de volume",
    audioSafetyThresholdLabel = "Seuil du rappel",
    audioSafetyLowerToLabel = "Réduire à",
    guidanceTitle = "Guide de démarrage",
    guidanceDescription = "Consultez le guide rapide.",
    guidanceOpenButton = "Ouvrir le guide",
    dailyReminderTitle = "Rappel quotidien",
    dailyReminderDescription = "Recevez une notification quotidienne pour pratiquer le caractère du jour.",
    dailyReminderEnabledLabel = "Activer le rappel",
    dailyReminderTimeLabelFormat = "Heure du rappel : %1\$s",
    dailyReminderChangeTimeButton = "Modifier",
    dailyReminderOnlyWhenIncompleteLabel = "Uniquement si non terminé",
    languageTitle = "Langue",
    languageDescription = "Remplacer la langue de l'interface.",
    languageCurrentFormat = "Actuelle : %1\$s",
    languageChangeButton = "Modifier",
    languageSystemOption = "Système",
    languageChineseOption = "Chinois",
    languageEnglishOption = "Anglais",
    languageSpanishOption = "Espagnol",
    languageJapaneseOption = "Japonais",
    languageKoreanOption = "Coréen",
    languageFrenchOption = "Français",
    dataTitle = "Données",
    dataDescription = "Gérer les données stockées sur cet appareil.",
    clearDictionaryHistoryButton = "Effacer l'historique du dictionnaire",
    clearDictionaryHistoryDialogTitle = "Effacer l'historique ?",
    clearDictionaryHistoryDialogBody = "Supprimer les recherches récentes du dictionnaire.",
    clearDictionaryHistoryConfirmButton = "Effacer",
    shareAppButton = "Partager l'app",
    shareAppMessage = "Découvrez Hanzi Dictionary & Strokes — apprenez l'ordre des traits chinois hors ligne !\nhttps://play.google.com/store/apps/details?id=com.yourstudio.hskstroke.bishun",
    rateAppButton = "Noter sur Google Play",
    hskWebsiteButton = "Site officiel HSK",
)

fun localizedStringsFr(locale: Locale): LocalizedStrings {
    val base = localizedStringsEn(locale)
    return base.copy(
        locale = locale,
        navigation = frenchNavigationStrings,
        onboarding = frenchOnboardingStrings,
        account = frenchAccountStrings,
        widget = WidgetStrings(
            dailyTitle = "Caractère du jour",
            streakDaysFormat = "%1\$d jours de suite",
            completedTodayLabel = "Terminé aujourd'hui",
            practiceLabel = "Pratiquer",
            dictionaryLabel = "Dictionnaire",
            tapToPracticeLabel = "Appuyez pour pratiquer",
            notificationChannelName = "Rappel quotidien",
            notificationChannelDescription = "Vous rappelle de pratiquer le caractère du jour",
        ),
    )
}
