package com.yourstudio.hskstroke.bishun.ui.character

import java.util.Locale

private val koreanNavigationStrings = NavigationStrings(
    homeLabel = "홈",
    learnLabel = "학습",
    flashcardLabel = "플래시카드",
    libraryLabel = "사전",
    accountLabel = "설정",
)

private val koreanFlashcardStrings = FlashcardStrings(
    title = "플래시카드",
    description = "간격 반복으로 어휘를 복습하세요.",
    levelAll = "전체",
    levelFormat = "HSK %1\$d",
    statDue = "복습 예정: %1\$d",
    statWeak = "취약: %1\$d",
    statMastered = "숙련: %1\$d",
    ratingAgain = "다시",
    ratingHard = "어려움",
    ratingGood = "보통",
    ratingEasy = "쉬움",
    cardFrontHint = "탭하여 뒤집기",
    emptyTitle = "모두 완료!",
    emptyDescription = "복습할 카드가 없습니다. 나중에 다시 오세요.",
    reviewedFormat = "%1\$d장의 카드 복습 완료",
    proGateTitle = "HSK 2–7 잠금 해제",
    proGateDescription = "Pro로 업그레이드하여 간격 반복으로 전체 3,090자를 학습하세요.",
    proGateButton = "Pro로 업그레이드",
    seedingMessage = "플래시카드 준비 중…",
    nextReviewLabel = "다음 복습:",
    tomorrowLabel = "내일",
    inDaysFormat = "%1\$d일 후",
)

private val koreanPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "연습 시작",
    hintLabel = "힌트",
    previousLabel = "이전 글자",
    nextLabel = "다음 글자",
    settingsLabel = "판 설정",
    pronunciationLabel = "발음 재생",
    dictionaryLabel = "사전 정의 보기",
    hskLabel = "HSK 정보",
    statusReadyLabel = "시작 준비 완료",
    statusStrokeProgressFormat = "획 %1\$d/%2\$d",
    statusStartFromStrokeFormat = "%1\$d번째 획부터 시작",
    statusTryAgainFormat = "다시 시도 (실수 %1\$d회)",
    statusGreatContinueLabel = "잘했어요! 다음 획으로 계속하세요",
    statusBackwardsAcceptedLabel = "획 방향이 반대였지만 인정됨",
    statusPracticeCompleteLabel = "연습 완료",
)

private val koreanProgressStrings = ProgressStrings(
    title = "진행 상황",
    description = "연속 학습 일수, HSK 등급별 숙련도, 최근 연습 기록을 확인하세요. 새로운 한자를 쓸 때마다 자동으로 갱신됩니다.",
    jumpBackLabel = "연습으로 돌아가기",
    dailyTitle = "오늘의 한자",
    dailyDescription = "매일 한 글자를 연습하세요. 다음 HSK 목표에서 오늘의 한자를 추천합니다.",
    dailyPracticeLabel = "연습",
    dailyCompletedLabel = "오늘 완료",
    learnedLabel = "숙련",
    streakLabel = "연속",
    lastSessionLabel = "최근 연습",
    streakDaySingularFormat = "%1\$d일",
    streakDayPluralFormat = "%1\$d일",
    streakStartLabel = "시작",
    lastSessionNeverLabel = "없음",
    weeklyChartTitle = "최근 7일",
    levelsTitle = "HSK 등급",
    levelsEmpty = "연습을 시작하면 각 HSK 등급의 진행 상황이 여기에 표시됩니다.",
    levelLabelFormat = "HSK %1\$d",
    levelMasteredFormat = "%1\$d/%2\$d 숙련",
    levelJumpDescription = "다음 한자로 이동",
    levelBrowseCourses = "코스 보기",
    historyTitle = "최근 연습",
    historyEmpty = "한자를 쓰면 여기에 표시되어 빠른 복습이 가능합니다.",
    historyStrokesFormat = "%1\$d획 · %2\$s",
    historyMistakesPerfect = "완벽",
    historyMistakesFormat = "실수 %1\$d회",
    historyLoadCharacterFormat = "%1\$s 불러오기",
    relativeJustNow = "방금",
    relativeMinutesFormat = "%1\$d분 전",
    relativeHoursFormat = "%1\$d시간 전",
    relativeDaysFormat = "%1\$d일 전",
)

private val koreanLibraryStrings = LibraryStrings(
    title = "사전",
    description = "병음, 부수, 간단한 정의를 모두 오프라인으로 확인할 수 있습니다. 한 글자만 입력하면 언제든 연습 탭으로 돌아갈 수 있습니다.",
    tabSearchLabel = "검색",
    tabFavoritesLabel = "즐겨찾기",
    tabHistoryLabel = "기록",
    inputLabel = "한자",
    supportingText = "팁: 한 글자만 입력하세요 (HSK 1은 항상 무료입니다).",
    resultsHeader = "결과",
    quickTryLabel = "예시:",
    recentHeader = "최근 검색",
    recentClear = "지우기",
    recentOverflowLabel = "더보기...",
    recentOverflowDialogTitle = "최근 검색",
    recentOverflowClose = "닫기",
    lookupLabel = "찾기",
    lookupLoadingLabel = "검색 중...",
    clearResultLabel = "결과 지우기",
    editLabel = "편집",
    doneLabel = "완료",
    selectAllLabel = "전체 선택",
    deselectAllLabel = "선택 해제",
    selectedCountFormat = "%1\$d개 선택됨",
    deleteLabel = "삭제",
    favoritesFilterLabel = "즐겨찾기 필터",
    historyFilterLabel = "기록 필터",
    filterNoResultsLabel = "일치하는 항목이 없습니다.",
    favoritesHeader = "즐겨찾기",
    favoritesEmpty = "나중에 다시 보려면 한자나 단어를 저장하세요.",
    favoritesSaveLabel = "저장",
    favoritesSavedLabel = "저장됨",
    favoritesAddLabel = "저장",
    favoritesRemoveLabel = "제거",
    favoritesClearLabel = "모두 지우기",
    favoritesClearDialogTitle = "즐겨찾기를 지우시겠습니까?",
    favoritesClearDialogBody = "이 기기에 저장된 모든 사전 항목을 삭제합니다.",
    favoritesClearConfirmLabel = "지우기",
    favoritesClearCancelLabel = "취소",
    historyHeader = "기록",
    historyPinnedHeader = "고정됨",
    historyEmpty = "최근 사전 검색 결과가 여기에 표시됩니다.",
    historyPinLabel = "고정",
    historyUnpinLabel = "고정 해제",
    historyRemoveLabel = "제거",
    historyClearLabel = "지우기",
    historyClearDialogTitle = "기록을 지우시겠습니까?",
    historyClearDialogBody = "이 기기의 사전 검색 기록을 삭제합니다.",
    historyClearConfirmLabel = "지우기",
    historyClearCancelLabel = "취소",
    sortRecentLabel = "최신",
    sortNameLabel = "가나다",
    moreActionsLabel = "더보기",
    helpTitle = "사용 팁",
    helpBody = "- 데이터는 번들된 word.db에서 가져오므로 완전 오프라인으로 작동합니다.\n- 저장된 항목과 기록은 기기에만 저장됩니다.\n- 획순 및 개인정보 세부사항은 프로젝트의 docs/help-guide.md를 참조하세요.",
    pinyinLabelFormat = "병음: %1\$s",
    radicalsStrokesFormat = "부수: %1\$s    획수: %2\$s",
    traditionalLabelFormat = "번체: %1\$s",
    definitionFallback = "정의를 가져올 수 없습니다.",
    valueNotAvailable = "없음",
    valueUnknown = "?",
    practiceButtonLabel = "이 한자 연습하기",
    practiceCharactersLabel = "글자 연습하기",
    quickSuggestions = listOf("永", "学", "好", "中", "发"),
    errorEmpty = "검색할 한자를 한 글자 입력하세요.",
    errorNotFound = "오프라인 사전에서 해당 한자를 찾을 수 없습니다.",
    errorRead = "사전을 읽을 수 없습니다. 다시 시도해 주세요.",
)

private val koreanCoursesStrings = CoursesStrings(
    title = "코스",
    description = "HSK 등급을 탐색하고 모든 한자를 오프라인으로 연습하세요.",
    emptyCatalogMessage = "코스 데이터를 찾을 수 없습니다. assets/learn-datas가 번들되어 있는지 확인하세요.",
    filterAll = "전체",
    filterRemaining = "남은 항목",
    filterCompleted = "완료",
    legendTitle = "범례",
    legendActive = "진행 중",
    legendCompleted = "완료",
    legendRemaining = "남은 항목",
    legendHint = "글자 카드를 길게 누르면 숙련됨으로 표시됩니다.",
    symbolEmptyMessage = "현재 필터와 일치하는 한자가 없습니다.",
    symbolShowAllLabel = "전체 글자 보기",
    symbolCollapseLabel = "목록 접기",
    activeCourseTitleFormat = "진행 중인 코스 · HSK %1\$d",
    activeCourseStatusFormat = "글자 %1\$s · %2\$s",
    activeResume = "계속",
    activeSkip = "건너뛰기",
    activeRestart = "다시 시작",
    activeExit = "나가기",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "%1\$d等级",
    levelProgressFormat = "%1\$d/%2\$d · 남은 항목 %3\$d",
    levelNextFormat = "다음 · %1\$s",
    levelCompletedLabel = "완료",
    lockedSignInLabel = "로그인",
    lockedUnlockLabel = "잠금 해제",
    lockedBrowseLabel = "코스 보기",
    lockedGreatJobLabel = "잘했어요!",
    iconStartDescriptionFormat = "HSK %1\$d 시작",
    toastSkippedLabel = "건너뛰기",
    toastMarkedLearnedFormat = "%1\$s을(를) 숙련됨으로 표시했습니다",
    toastCourseCompleteFormat = "HSK %1\$d 완료!",
    toastAutoAdvancedFormat = "자동으로 %1\$s으로 이동했습니다",
    toastNextUpFormat = "다음: %1\$s",
)

private val koreanWidgetStrings = WidgetStrings(
    dailyTitle = "오늘의 한자",
    streakDaysFormat = "%1\$d일 연속",
    completedTodayLabel = "오늘 완료",
    practiceLabel = "연습",
    dictionaryLabel = "사전",
    tapToPracticeLabel = "탭하여 연습 시작",
    notificationChannelName = "매일 알림",
    notificationChannelDescription = "오늘의 한자 연습 알림",
)

private val koreanSupportStrings = SupportStrings(
    analyticsTitle = "사용 분석",
    analyticsDescription = "향후 기능 계획용 익명 카운터입니다.",
    crashTitle = "충돌 보고서",
    crashDescription = "렌더링 실패 시 경량 로그를 공유할 수 있습니다.",
    prefetchTitle = "네트워크 사전 로드",
    prefetchDescription = "향후 팩의 Wi-Fi 다운로드를 허용합니다.",
    privacyCloseLabel = "닫기",
    feedbackTitle = "피드백 보내기",
    feedbackThanksTitle = "감사합니다!",
    feedbackSavedMessage = "메모가 로컬에 저장되었습니다. 다음 업데이트에서 진단 내보내기와 함께 번들되므로 아무것도 분실되지 않습니다.",
    feedbackTopicLabel = "주제",
    feedbackTopicPlaceholder = "기능 요청, 버그 신고...",
    feedbackMessageLabel = "상세 내용",
    feedbackMessagePlaceholder = "아이디어나 발생한 문제를 설명해 주세요",
    feedbackContactLabel = "연락처 (선택)",
    feedbackContactPlaceholder = "이메일 또는 연락처",
    feedbackSendLabel = "보내기",
    feedbackCloseLabel = "닫기",
    feedbackShareLogLabel = "로그 공유",
    feedbackCancelLabel = "취소",
    feedbackLastSentFormat = "마지막 전송: %1\$s",
    feedbackLogEmpty = "피드백 로그가 비어 있습니다.",
    feedbackLogShareError = "로그를 공유할 수 없습니다.",
    feedbackLogNoApps = "로그를 공유할 수 있는 앱이 없습니다.",
    feedbackEmailError = "이메일을 열 수 없습니다. 로그가 로컬에 저장되었습니다. 나중에 계정에서 공유해 주세요.",
    feedbackEmailNoApp = "이메일 앱이 설치되어 있지 않습니다. 로그가 로컬에 저장되었습니다. 나중에 계정에서 공유해 주세요.",
)

private val koreanOnboardingStrings = OnboardingStrings(
    appTitle = "한자",
    skipLabel = "건너뛰기",
    backLabel = "이전",
    nextLabel = "다음",
    startLabel = "시작",
    pages = listOf(
        OnboardingPageText(
            title = "한자를 빠르게 찾기",
            body = "획순과 발음을 오프라인으로 언제든지 확인할 수 있습니다.",
        ),
        OnboardingPageText(
            title = "안내와 함께 연습하기",
            body = "획을 따라 쓰고 힌트를 받아 정확도와 자신감을 높이세요.",
        ),
        OnboardingPageText(
            title = "필요할 때 사전 활용",
            body = "연습을 떠나지 않고 사전 카드에서 병음과 의미를 확인할 수 있습니다.",
        ),
        OnboardingPageText(
            title = "오늘의 위젯 추가하기",
            body = "홈 화면에 추가하여 원탭으로 연습하고 발음을 확인할 수 있습니다.",
        ),
        OnboardingPageText(
            title = "더 안전한 음량 재생",
            body = "공공 장소에서 음량이 너무 크지 않도록 음량 알림을 설정할 수 있습니다.",
        ),
    ),
)

private val koreanAccountStrings = AccountStrings(
    title = "설정",
    signInCardTitle = "로그인 상태",
    signInDescriptionSignedIn = "로그인되어 있습니다. 구매 및 잠금 해제된 등급은 이 기기에 연결됩니다.",
    signInDescriptionSignedOut = "게스트 모드는 연습 데이터를 오프라인으로 기기에 저장합니다. 코스의 잠금을 해제할 준비가 되었을 때만 로그인하세요.",
    signInButtonSignedIn = "로그아웃",
    signInButtonSignedOut = "로그인 및 정책 동의",
    courseCardTitle = "코스 잠금 해제",
    courseDescriptionSignedOut = "HSK 등급을 언제든지 미리볼 수 있습니다. 로그인하여 구매 체크리스트를 완료하세요.",
    courseDescriptionUnlocked = "모든 프리미엄 등급이 잠금 해제되었습니다. 학습 탭에서 계속하세요.",
    courseDescriptionLocked = "일회성 잠금 해제는 로컬 라이선스를 저장하여 코스가 오프라인에서도 사용 가능하도록 합니다.",
    courseButtonSignedOut = "로그인 필요",
    courseButtonUnlocked = "코스 탐색",
    courseButtonLocked = "모든 코스 잠금 해제",
    supportTitle = "지원",
    supportDescription = "도움말 기사 및 개인정보 안내가 여기 있습니다.",
    supportFeedbackButton = "피드백 보내기",
    clearDataTitle = "로컬 데이터 초기화",
    clearDataDescription = "이 기기에 저장된 연습 기록, 코스 진행 상황, 설정을 삭제합니다.",
    clearDataButton = "로컬 기록 지우기",
    clearDataDialogTitle = "로컬 데이터를 삭제하시겠습니까?",
    clearDataDialogBody = "이렇게 하면 연습 기록, 연속 일수, 설정, 사전 검색 기록이 기기에서 삭제됩니다. 이 작업은 취소할 수 없습니다.",
    consentSignInTitle = "로그인 전에 확인하세요",
    consentSignInBullets = listOf(
        "로그인은 구매 연결에만 필요합니다. 연습 데이터는 기기에 남아 있습니다.",
        "계속하면 개인정보 처리방침을 검토했음을 확인하는 것입니다.",
        "언제든지 게스트 모드를 유지할 수 있습니다. 프리미엄 레슨은 단순히 잠긴 상태로 유지됩니다.",
    ),
    consentSignInConfirm = "동의 및 로그인",
    consentUnlockTitle = "프리미엄 레슨 잠금 해제",
    consentUnlockBullets = listOf(
        "결제 토큰은 로컬에 캐시되므로 모든 콘텐츠가 오프라인에서 작동합니다.",
        "잠금 해제하면 나중에 복원할 수 있도록 계정 탭에 구매 정보도 기록됩니다.",
        "컴플라이언스를 위해 체크아웃 중 간단한 개인정보 알림이 다시 표시됩니다.",
    ),
    consentUnlockConfirm = "잠금 해제 확인",
    consentCheckboxLabel = "개인정보 처리방침을 검토했습니다.",
    cancelLabel = "취소",
    closeLabel = "닫기",
    proCardTitle = "Pro",
    proStatusPro = "Pro",
    proStatusFree = "무료",
    proStatusPlayRequired = "Google Play 필요",
    proStatusPending = "구매 대기 중",
    proStatusConnecting = "연결 중...",
    proStatusNotAvailable = "사용 불가",
    proDescriptionPro = "앱을 지원해 주셔서 감사합니다. Pro는 오프라인에서도 사용 가능하며 Google Play에서 자동으로 복원됩니다.",
    proDescriptionNoPlayStore = "Pro 구매는 Google Play가 설치된 기기에서만 사용할 수 있습니다. 구매 및 복원하려면 Google Play에서 설치하세요.",
    proDescriptionFree = "일회성 구매로 앱을 지원하세요. Pro는 Google Play에서 자동으로 복원됩니다.",
    proBillingStatusCodeFormat = "결제 상태 코드: %1\$d",
    proRestorePurchasesButton = "구매 복원",
    proBuyButton = "구매",
    proBuyButtonWithPriceFormat = "구매 (%1\$s)",
    appearanceCardTitle = "외관",
    appearanceCardDescription = "이 기기에서 앱의 모양을 선택하세요.",
    themeModeSystemLabel = "시스템",
    themeModeLightLabel = "밝게",
    themeModeDarkLabel = "어둡게",
    accentColorLabel = "강조 색상",
    brushThicknessLabel = "붓 굵기",
    requiresProChipLabelFormat = "%1\$s · Pro",
    accentColorOptionLabels = listOf(
        "라벤더",
        "사파이어 블루",
        "민트 그린",
        "실버 핑크",
        "쿠키 브라운",
        "지nger 브라운",
        "다크 카네이션 핑크",
        "미디엄 바이올렛 레드",
    ),
    brushWidthOptionLabels = listOf(
        "얇게",
        "표준",
        "두껍게",
    ),
    audioSafetyTitle = "음량 안전",
    audioSafetyDescription = "높은 음량으로 발음을 재생하기 전에 알림을 표시합니다.",
    audioSafetyVolumeReminderLabel = "음량 알림",
    audioSafetyThresholdLabel = "알림 기준",
    audioSafetyLowerToLabel = "자동으로 낮추기",
    guidanceTitle = "시작 가이드",
    guidanceDescription = "처음 사용하는 분은 빠른 안내를 확인하세요.",
    guidanceOpenButton = "안내 열기",
    dailyReminderTitle = "매일 알림",
    dailyReminderDescription = "매일 지정된 시간에 오늘의 한자 연습 알림을 받으세요 (Android 13+는 알림 권한이 필요합니다).",
    dailyReminderEnabledLabel = "알림 활성화",
    dailyReminderTimeLabelFormat = "알림 시간: %1\$s",
    dailyReminderChangeTimeButton = "변경",
    dailyReminderOnlyWhenIncompleteLabel = "미완료 시에만 알림",
    languageTitle = "언어",
    languageDescription = "앱 내 콘텐츠 언어를 재정의합니다.",
    languageCurrentFormat = "현재: %1\$s",
    languageChangeButton = "변경",
    languageSystemOption = "시스템",
    languageChineseOption = "중국어",
    languageEnglishOption = "영어",
    languageSpanishOption = "스페인어",
    languageJapaneseOption = "일본어",
    languageKoreanOption = "한국어",
    languageFrenchOption = "프랑스어",
    dataTitle = "데이터",
    dataDescription = "이 기기에 저장된 콘텐츠를 관리합니다.",
    clearDictionaryHistoryButton = "사전 기록 지우기",
    clearDictionaryHistoryDialogTitle = "사전 기록 지우기",
    clearDictionaryHistoryDialogBody = "이 기기에 저장된 최근 사전 검색을 삭제합니다.",
    clearDictionaryHistoryConfirmButton = "지우기",
    shareAppButton = "앱 공유하기",
    shareAppMessage = "한자 사전 & 획순 — 오프라인으로 한자 획순을 배울 수 있는 앱을 추천합니다!\nhttps://play.google.com/store/apps/details?id=com.yourstudio.hskstroke.bishun",
    rateAppButton = "Google Play에서 평가하기",
    hskWebsiteButton = "HSK 공식 웹사이트",
)

private val koreanHelpSections = listOf(
    HelpSectionText(
        title = "빠른 시작",
        description = "데모 → 연습 사이클을 몇 초 만에 완료하세요.",
        bullets = listOf(
            "아무 한자나 입력하고 클라우드 아이콘을 눌러 오프라인 데이터를 불러옵니다.",
            "재생 또는 루프를 눌러 데모를 보고, 정확한 획순을 따라 쓰려면 서체 템플릿을 활성화하세요.",
            "판 위의 연필 아이콘을 눌러 시작하세요. 힌트 아이콘이 다음 획을 강조합니다.",
        ),
    ),
    HelpSectionText(
        title = "코스 및 진행 상황",
        description = "HSK 코스는 아바타 메뉴 아래에 있으며 배지는 현재 상태를 반영합니다.",
        bullets = listOf(
            "배지 내 아이콘으로 재개/건너뛰기/다시 시작/나가기가 가능하여 판이 가려지지 않습니다.",
            "화살표로 한자를 전환할 수 있으며, 완료 시 요약이 즉시 업데이트됩니다.",
        ),
    ),
    HelpSectionText(
        title = "카드 및 발음",
        description = "카이슈 카드는 사전 데이터와 텍스트 음성 변환 재생을 보여줍니다.",
        bullets = listOf(
            "카드를 눌러 전체 정의를 열고 설명을 스크롤할 수 있습니다.",
            "스피커 버튼은普通话 오디오를 완전 오프라인으로 재생합니다.",
        ),
    ),
    HelpSectionText(
        title = "격자 및 템플릿",
        description = "판 설정은 미 격자, 구궁 격자, 또는 가이드 없음을 지원합니다.",
        bullets = listOf(
            "외곽선 모드와 자유형 모드를 전환할 수 있습니다. 획 색상은 세션 간에 유지됩니다.",
            "캔버스 밖에서 스크롤하면 페이지가 이동하여 작성 영역이 고정됩니다.",
        ),
    ),
    HelpSectionText(
        title = "지원",
        description = "도움이 필요하시면 언제든지 문의하세요.",
        bullets = listOf(
            "이메일: qq260316514@gmail.com",
            "핵심 학습은 오프라인으로 작동하며 학습 데이터는 기기에 남아 있습니다.",
        ),
    ),
)

private val koreanPrivacySummaryRows = listOf(
    SummaryRowText(title = "데이터 저장", detail = "연습 기록, 코스 진행 상황, 판 설정은 로컬 DataStore에만 저장됩니다."),
    SummaryRowText(title = "오프라인 자산", detail = "획순 JSON 및 코스 팩은 APK 내부에 포함됩니다."),
    SummaryRowText(title = "알림", detail = "선택적 매일 알림. Android 13+는 알림을 활성화한 경우에만 알림 권한을 요청합니다."),
    SummaryRowText(title = "네트워크", detail = "네트워크 권한은 선택적 Google Play 구매 및 복원에만 사용됩니다. 학습 데이터는 업로드되지 않습니다."),
)

private val koreanFullPolicySections = listOf(
    PolicySectionText(
        title = "1. 당사가 수집하는 데이터",
        bullets = listOf(
            "획순 애니메이션 렌더링을 위한 APK에 패키지된 한자 리소스.",
            "로컬 연습 기록, HSK 진행 상황, 재개 상태.",
            "격자, 색상, 템플릿 표시 여부, 언어 재정의 등 판 환경설정.",
            "기기에 저장된 최근 사전 검색.",
            "기기에 저장된 매일 알림 환경설정 (활성화/시간/규칙).",
            "선택적 인앱 구매는 Google Play가 처리합니다. 광고 없음.",
        ),
    ),
    PolicySectionText(
        title = "2. 데이터 사용 방법",
        bullets = listOf(
            "로컬에서 연습 및 코스 진행 상황을 재개합니다.",
            "사전 카드 및 HSK 요약을 완전 오프라인으로 표시합니다.",
            "로컬에서 진행 상황 및 연속 일수를 계산합니다.",
        ),
    ),
    PolicySectionText(
        title = "3. 권한",
        bullets = listOf(
            "POST_NOTIFICATIONS (Android 13+): 선택적. 알림이 활성화된 경우 매일 알림용.",
            "RECEIVE_BOOT_COMPLETED: 재부팅, 앱 업데이트 또는 시간 변경 후 알림을 복원합니다.",
            "네트워크 권한: 선택적 Google Play 구매 및 복원 전용. 핵심 학습은 오프라인으로 작동합니다.",
            "정확한 위치, 연락처, 카메라 또는 마이크에 액세스하지 않습니다.",
        ),
    ),
    PolicySectionText(
        title = "4. 사용자 제어",
        bullets = listOf(
            "Android 설정에서 앱 저장소를 지우면 모든 데이터가 재설정됩니다.",
            "폰을 백업하지 않는 한 모든 데이터는 이 기기에만 저장됩니다.",
        ),
    ),
    PolicySectionText(
        title = "5. 연락처",
        bullets = listOf("이메일: qq260316514@gmail.com"),
    ),
)

fun localizedStringsKo(locale: Locale): LocalizedStrings {
    val base = localizedStringsEn(locale)
    return base.copy(
        locale = locale,
        appTitle = "한자 획순",
        navigation = koreanNavigationStrings,
        onboarding = koreanOnboardingStrings,
        searchLabel = "한자",
        loadButton = "글자 불러오기",
        clearButton = "입력 지우기",
        loadingLabel = "불러오는 중...",
        coursesDialogTitle = "HSK 코스",
        coursePlanHeading = "계속할 코스를 선택하세요",
        courseIntroTitle = "코스 이용 안내",
        courseIntroBullets = listOf(
            "HSK 등급을 선택하여 시작하거나 마지막 중단 지점에서 다시 시작하세요.",
            "한자를 눌러 연습하고, 길게 눌러 숙련됨으로 표시하세요.",
            "판 위의 배지가 현재 코스 진행 상황을 실시간으로 표시합니다.",
        ),
        courseEmptyTitle = "진행 중인 코스가 없습니다",
        courseEmptyDescription = "아래에서 HSK 등급을 선택하여 안내된 연습을 시작하세요.",
        courseNoDataMessage = "코스 데이터를 찾을 수 없습니다. 리소스 팩을 확인해 주세요.",
        expandCharactersLabel = "전체 보기",
        collapseCharactersLabel = "숨기기",
        legendTitle = "범례 및 제스처",
        legendGesture = "한자를 눌러 연습하고, 길게 눌러 숙련됨으로 표시하세요.",
        legendActiveLabel = "진행 중",
        legendCompletedLabel = "완료",
        legendRemainingLabel = "남은 항목",
        courseLegendHint = "배지 내 컨트롤로 재개, 건너뛰기, 다시 시작, 나가기가 가능하여 판을 가리지 않습니다.",
        courseLevelCompleteLabel = "코스 완료",
        courseLevelStartFormat = "'%s'부터 시작",
        courseLevelNextFormat = "다음 · %s",
        levelLabelFormat = "%d等级",
        courseLevelProgressFormat = "%1\$d/%2\$d 숙련 · 남은 항목 %3\$d",
        loadLevelFormat = "HSK %d 불러오기",
        filterAllLabel = "전체",
        filterRemainingLabel = "남은 항목",
        filterCompletedLabel = "완료",
        helpTitle = "도움말 및 시작 가이드",
        helpSections = koreanHelpSections,
        helpConfirm = "알겠습니다",
        privacyTitle = "개인정보",
        privacyIntro = "기본적으로 완전 오프라인입니다.",
        dataSafetyHeading = "데이터 안전 개요",
        privacySummaryRows = koreanPrivacySummaryRows,
        contactSupportLabel = "연락처: %s",
        emailSupportButton = "이메일로 문의",
        viewPolicyButton = "전체 개인정보 처리방침 보기",
        fullPolicyTitle = "개인정보 처리방침",
        fullPolicySections = koreanFullPolicySections,
        progress = koreanProgressStrings,
        library = koreanLibraryStrings,
        courses = koreanCoursesStrings,
        account = koreanAccountStrings,
        support = koreanSupportStrings,
        widget = koreanWidgetStrings,
        flashcard = koreanFlashcardStrings,
        boardControls = koreanPracticeBoardStrings,
    )
}
