package com.yourstudio.hskstroke.bishun.ui.character

import java.util.Locale

private val enNavigationStrings = NavigationStrings(
    homeLabel = "Home",
    learnLabel = "Learn",
    libraryLabel = "Dictionary",
    accountLabel = "Account",
)

private val enPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Start practice",
    hintLabel = "Hint",
    previousLabel = "Previous character",
    nextLabel = "Next character",
    settingsLabel = "Canvas settings",
    pronunciationLabel = "Play pronunciation",
    dictionaryLabel = "Show dictionary entry",
    hskLabel = "HSK info",
    statusReadyLabel = "Ready to start",
    statusStrokeProgressFormat = "Stroke %1\$d/%2\$d",
    statusStartFromStrokeFormat = "Start from stroke %1\$d",
    statusTryAgainFormat = "Try again (mistakes %1\$d)",
    statusGreatContinueLabel = "Great! Continue to the next stroke",
    statusBackwardsAcceptedLabel = "Stroke direction reversed but accepted",
    statusPracticeCompleteLabel = "Practice complete",
)

private val enProgressStrings = ProgressStrings(
    title = "Progress",
    description = "Check streaks, HSK completion, and the latest practice records. Everything refreshes automatically whenever you trace a new character.",
    jumpBackLabel = "Back to Practice",
    dailyTitle = "Daily",
    dailyDescription = "Practice one character a day. Suggested from your next HSK target.",
    dailyPracticeLabel = "Practice",
    dailyCompletedLabel = "Completed today",
    learnedLabel = "Learned",
    streakLabel = "Streak",
    lastSessionLabel = "Last session",
    streakDaySingularFormat = "%1\$d day",
    streakDayPluralFormat = "%1\$d days",
    streakStartLabel = "Start",
    lastSessionNeverLabel = "Never",
    weeklyChartTitle = "Last 7 days",
    levelsTitle = "Levels",
    levelsEmpty = "Start a practice session to see each HSK level tracked here.",
    levelLabelFormat = "HSK %1\$d",
    levelMasteredFormat = "%1\$d/%2\$d mastered",
    levelJumpDescription = "Jump to the next character",
    levelBrowseCourses = "Browse courses",
    historyTitle = "Recent practice",
    historyEmpty = "Trace any character and it shows up here for a quick review.",
    historyStrokesFormat = "%1\$d strokes \u00b7 %2\$s",
    historyMistakesPerfect = "Perfect run",
    historyMistakesFormat = "%1\$d mistakes",
    historyLoadCharacterFormat = "Load %1\$s",
    relativeJustNow = "just now",
    relativeMinutesFormat = "%1\$d min ago",
    relativeHoursFormat = "%1\$d hr ago",
    relativeDaysFormat = "%1\$d d ago",
)

private val enLibraryStrings = LibraryStrings(
    title = "Dictionary",
    description = "Check pinyin, radicals, and quick definitions entirely offline. Enter a single character and hop back to Practice whenever you want to trace.",
    tabSearchLabel = "Search",
    tabFavoritesLabel = "Saved",
    tabHistoryLabel = "History",
    inputLabel = "Chinese character",
    supportingText = "Tip: Input one character (HSK 1 stays unlocked).",
    resultsHeader = "Results",
    quickTryLabel = "Try:",
    recentHeader = "Recent searches",
    recentClear = "Clear",
    recentOverflowLabel = "More...",
    recentOverflowDialogTitle = "Recent searches",
    recentOverflowClose = "Close",
    lookupLabel = "Lookup",
    lookupLoadingLabel = "Looking up...",
    clearResultLabel = "Clear result",
    editLabel = "Edit",
    doneLabel = "Done",
    selectAllLabel = "Select all",
    deselectAllLabel = "Deselect all",
    selectedCountFormat = "%1\$d selected",
    deleteLabel = "Delete",
    favoritesFilterLabel = "Filter saved",
    historyFilterLabel = "Filter history",
    filterNoResultsLabel = "No matches.",
    favoritesHeader = "Saved",
    favoritesEmpty = "Save a character or word to revisit it later.",
    favoritesSaveLabel = "Save",
    favoritesSavedLabel = "Saved",
    favoritesAddLabel = "Save",
    favoritesRemoveLabel = "Remove",
    favoritesClearLabel = "Clear",
    favoritesClearDialogTitle = "Clear saved items?",
    favoritesClearDialogBody = "This removes all saved dictionary items on this device.",
    favoritesClearConfirmLabel = "Clear",
    favoritesClearCancelLabel = "Cancel",
    historyHeader = "History",
    historyPinnedHeader = "Pinned",
    historyEmpty = "Recent dictionary lookups will appear here.",
    historyPinLabel = "Pin",
    historyUnpinLabel = "Unpin",
    historyRemoveLabel = "Remove",
    historyClearLabel = "Clear",
    historyClearDialogTitle = "Clear history?",
    historyClearDialogBody = "This clears dictionary history on this device.",
    historyClearConfirmLabel = "Clear",
    historyClearCancelLabel = "Cancel",
    sortRecentLabel = "Recent",
    sortNameLabel = "A–Z",
    moreActionsLabel = "More",
    helpTitle = "Tips",
    helpBody = "- Data comes from the bundled word.db so it works offline.\n- Saved items and history stay only on your device.\n- For writing details and privacy specifics see docs/help-guide.md in the project.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Strokes: %2\$s",
    traditionalLabelFormat = "Traditional: %1\$s",
    definitionFallback = "No definition available.",
    valueNotAvailable = "N/A",
    valueUnknown = "?",
    practiceButtonLabel = "Practice this character",
    practiceCharactersLabel = "Practice characters",
    quickSuggestions = listOf("永", "学", "好", "中", "发"),
    errorEmpty = "Enter one character to search.",
    errorNotFound = "Character not found in the offline dictionary.",
    errorRead = "Unable to read the dictionary. Try again.",
)

private val enCoursesStrings = CoursesStrings(
    title = "Courses",
    description = "Browse HSK levels and practice each character fully offline.",
    emptyCatalogMessage = "No course data found. Make sure assets/learn-datas is bundled.",
    filterAll = "All",
    filterRemaining = "Remaining",
    filterCompleted = "Completed",
    legendTitle = "Legend",
    legendActive = "Active",
    legendCompleted = "Completed",
    legendRemaining = "Remaining",
    legendHint = "Long press any chip to mark it as learned.",
    symbolEmptyMessage = "No characters match the current filter.",
    symbolShowAllLabel = "Show all characters",
    symbolCollapseLabel = "Collapse list",
    activeCourseTitleFormat = "Active course \u00b7 HSK %1\$d",
    activeCourseStatusFormat = "Character %1\$s \u00b7 %2\$s",
    activeResume = "Resume",
    activeSkip = "Skip",
    activeRestart = "Restart",
    activeExit = "Exit",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Level %1\$d",
    levelProgressFormat = "%1\$d/%2\$d \u00b7 remaining %3\$d",
    levelNextFormat = "Next \u00b7 %1\$s",
    levelCompletedLabel = "Completed",
    lockedSignInLabel = "Sign in",
    lockedUnlockLabel = "Unlock",
    lockedBrowseLabel = "Browse courses",
    lockedGreatJobLabel = "Great job!",
    iconStartDescriptionFormat = "Start HSK %1\$d",
    toastSkippedLabel = "Skipped character",
    toastMarkedLearnedFormat = "Marked %1\$s as learned",
    toastCourseCompleteFormat = "HSK %1\$d complete!",
    toastAutoAdvancedFormat = "Auto-advanced to %1\$s",
    toastNextUpFormat = "Next up: %1\$s",
)

private val enSupportStrings = SupportStrings(
    analyticsTitle = "Usage analytics",
    analyticsDescription = "Anonymous counters for upcoming features.",
    crashTitle = "Crash reports",
    crashDescription = "Share lightweight logs if rendering fails.",
    prefetchTitle = "Network prefetch",
    prefetchDescription = "Allow Wi-Fi downloads of future packs.",
    privacyCloseLabel = "Close",
    feedbackTitle = "Send feedback",
    feedbackThanksTitle = "Thanks!",
    feedbackSavedMessage = "We stored your note locally. The next release will bundle it with diagnostic exports so nothing gets lost.",
    feedbackTopicLabel = "Topic",
    feedbackTopicPlaceholder = "Feature request, bug...",
    feedbackMessageLabel = "Details",
    feedbackMessagePlaceholder = "Describe the idea or issue",
    feedbackContactLabel = "Contact (optional)",
    feedbackContactPlaceholder = "Email or handle",
    feedbackSendLabel = "Send",
    feedbackCloseLabel = "Close",
    feedbackShareLogLabel = "Share log",
    feedbackCancelLabel = "Cancel",
    feedbackLastSentFormat = "Last sent: %1\$s",
    feedbackLogEmpty = "Feedback log is empty.",
    feedbackLogShareError = "Unable to share log.",
    feedbackLogNoApps = "No apps available to share log.",
    feedbackEmailError = "Couldn't open email. Log saved locally—share from Account later.",
    feedbackEmailNoApp = "No email app installed. Log saved locally—share from Account later.",
)

private val enAccountStrings = AccountStrings(
    title = "Settings",
    signInCardTitle = "Sign-in status",
    signInDescriptionSignedIn = "Signed in. Purchases and unlocked levels remain linked to this device.",
    signInDescriptionSignedOut = "Guest mode keeps practice data offline. Sign in only when you are ready to unlock courses.",
    signInButtonSignedIn = "Sign out",
    signInButtonSignedOut = "Sign in & accept policy",
    courseCardTitle = "Course unlock",
    courseDescriptionSignedOut = "Preview HSK levels anytime. Sign in to complete the purchase checklist.",
    courseDescriptionUnlocked = "All premium levels are unlocked. Continue from the Courses tab.",
    courseDescriptionLocked = "One-time unlock stores a local license so lessons remain available offline.",
    courseButtonSignedOut = "Sign in required",
    courseButtonUnlocked = "Browse courses",
    courseButtonLocked = "Unlock all courses",
    supportTitle = "Support",
    supportDescription = "Help articles and privacy information live here.",
    supportFeedbackButton = "Send feedback",
    clearDataTitle = "Reset local data",
    clearDataDescription = "Remove practice history, course progress, and preferences stored on this device.",
    clearDataButton = "Clear local records",
    clearDataDialogTitle = "Erase local data?",
    clearDataDialogBody = "This removes practice history, streaks, preferences, and dictionary searches from this device. This cannot be undone.",
    consentSignInTitle = "Before signing in",
    consentSignInBullets = listOf(
        "Sign-in is only needed to associate purchases. Practice data stays on-device.",
        "Continuing confirms you have reviewed the Privacy Policy.",
        "You can remain in guest mode at any time—premium lessons simply stay locked.",
    ),
    consentSignInConfirm = "Agree & sign in",
    consentUnlockTitle = "Unlock premium lessons",
    consentUnlockBullets = listOf(
        "Payment tokens are cached locally so all content works offline.",
        "Unlocking also records the purchase under your account tab for later restores.",
        "A quick privacy reminder will appear again during checkout for compliance.",
    ),
    consentUnlockConfirm = "Confirm unlock",
    consentCheckboxLabel = "I have reviewed the privacy policy.",
    cancelLabel = "Cancel",
    closeLabel = "Close",
    proCardTitle = "Pro",
    proStatusPro = "Pro",
    proStatusFree = "Free",
    proStatusPlayRequired = "Google Play required",
    proStatusPending = "Pending purchase",
    proStatusConnecting = "Connecting\u2026",
    proStatusNotAvailable = "Not available",
    proDescriptionPro = "Thanks for supporting the app. Pro stays available offline and restores automatically with Google Play.",
    proDescriptionNoPlayStore = "Pro purchase is available only on devices with Google Play. Install from Google Play to buy and restore purchases.",
    proDescriptionFree = "Support the app with a one-time purchase. Pro restores automatically with Google Play.",
    proBillingStatusCodeFormat = "Billing status code: %1\$d",
    proRestorePurchasesButton = "Restore purchases",
    proBuyButton = "Buy",
    proBuyButtonWithPriceFormat = "Buy (%1\$s)",
    appearanceCardTitle = "Appearance",
    appearanceCardDescription = "Choose how the app looks on this device.",
    themeModeSystemLabel = "System",
    themeModeLightLabel = "Light",
    themeModeDarkLabel = "Dark",
    accentColorLabel = "Accent color",
    brushThicknessLabel = "Brush thickness",
    requiresProChipLabelFormat = "%1\$s \u00b7 Pro",
    accentColorOptionLabels = listOf(
        "Lilac", "Sapphire Blue", "Seafoam Green",
        "Silver Pink", "Cookie Brown", "Ginger Brown",
        "Dark Carnation Pink", "Medium Violet Red",
    ),
    brushWidthOptionLabels = listOf("Thin", "Regular", "Bold"),
    audioSafetyTitle = "Audio safety",
    audioSafetyDescription = "Show a reminder before playing pronunciation at high volume.",
    audioSafetyVolumeReminderLabel = "Volume reminder",
    audioSafetyThresholdLabel = "Reminder threshold",
    audioSafetyLowerToLabel = "Lower to",
    guidanceTitle = "Getting started",
    guidanceDescription = "Review the quick guide for first-time users.",
    guidanceOpenButton = "Open guide",
    dailyReminderTitle = "Daily reminder",
    dailyReminderDescription = "Get a notification each day to practice today's character (Android 13+ requires notification permission).",
    dailyReminderEnabledLabel = "Enable reminder",
    dailyReminderTimeLabelFormat = "Reminder time: %1\$s",
    dailyReminderChangeTimeButton = "Change",
    dailyReminderOnlyWhenIncompleteLabel = "Only when incomplete",
    languageTitle = "Language",
    languageDescription = "Overrides in-app content language.",
    languageCurrentFormat = "Current: %1\$s",
    languageChangeButton = "Change",
    languageSystemOption = "System",
    languageChineseOption = "Chinese",
    languageEnglishOption = "English",
    languageSpanishOption = "Spanish",
    languageJapaneseOption = "Japanese",
    dataTitle = "Data",
    dataDescription = "Manage what is stored on this device.",
    clearDictionaryHistoryButton = "Clear dictionary history",
    clearDictionaryHistoryDialogTitle = "Clear dictionary history",
    clearDictionaryHistoryDialogBody = "Remove recent dictionary searches saved on this device.",
    clearDictionaryHistoryConfirmButton = "Clear",
    shareAppButton = "Share app",
    shareAppMessage = "Check out Hanzi Dictionary & Strokes — learn Chinese stroke order offline!\nhttps://play.google.com/store/apps/details?id=com.yourstudio.hskstroke.bishun",
    rateAppButton = "Rate on Google Play",
)

private val enOnboardingStrings = OnboardingStrings(
    appTitle = "Hanzi",
    skipLabel = "Skip",
    backLabel = "Back",
    nextLabel = "Next",
    startLabel = "Start",
    pages = listOf(
        OnboardingPageText(
            title = "Look up characters fast",
            body = "Search stroke order and pronunciation offline, anytime you need it.",
        ),
        OnboardingPageText(
            title = "Practice with guidance",
            body = "Trace strokes and get hints to improve accuracy and confidence.",
        ),
        OnboardingPageText(
            title = "Dictionary when you need details",
            body = "Open the dictionary card to see pinyin and meaning without leaving practice.",
        ),
        OnboardingPageText(
            title = "Add the Daily widget",
            body = "Pin the Daily widget to your home screen for one-tap practice and pronunciation.",
        ),
        OnboardingPageText(
            title = "Safer pronunciation playback",
            body = "Enable volume reminders to avoid playing audio too loud in public.",
        ),
    ),
)

private val enHelpSections = listOf(
    HelpSectionText(
        title = "Quick start",
        description = "Complete a full demo → practice cycle in seconds.",
        bullets = listOf(
            "Enter any hanzi and tap the cloud icon to load offline data.",
            "Use Play or Loop to watch the demo; enable the calligraphy template for tracing.",
            "Press the pencil on the board to begin; the hint icon highlights the next stroke.",
        ),
    ),
    HelpSectionText(
        title = "Courses & progress",
        description = "HSK courses live under the avatar menu, and the badge reflects your status.",
        bullets = listOf(
            "Resume/Skip/Restart/Exit icons stay inside the badge so controls never hide the board.",
            "Chevron arrows jump between characters; finishing one updates the summary instantly.",
        ),
    ),
    HelpSectionText(
        title = "Cards & pronunciation",
        description = "The Kaishu card shows dictionary data plus TextToSpeech playback.",
        bullets = listOf(
            "Tap the card to open the full definition and scroll through the explanation.",
            "The speaker button plays Mandarin audio entirely offline.",
        ),
    ),
    HelpSectionText(
        title = "Grids & templates",
        description = "Board settings support Mi-grid, nine-grid, or no guides at all.",
        bullets = listOf(
            "Switch between outline and freestyle modes; stroke colors persist between sessions.",
            "Scroll outside the canvas to move the page so the writing surface stays fixed.",
        ),
    ),
    HelpSectionText(
        title = "Support",
        description = "Need help? Reach out anytime.",
        bullets = listOf(
            "Email: qq260316514@gmail.com",
            "Core learning works offline and your learning data stays on-device.",
        ),
    ),
)

private val enPrivacySummaryRows = listOf(
    SummaryRowText(title = "Data storage", detail = "Practice history, course progress, and board settings stay in local DataStore only."),
    SummaryRowText(title = "Offline assets", detail = "Stroke JSON and course packs ship inside the APK."),
    SummaryRowText(title = "Notifications", detail = "Optional daily reminders. On Android 13+ the app asks for notification permission only if you enable reminders."),
    SummaryRowText(title = "Network", detail = "Network permission is used for optional Google Play purchase and restore. Learning data is not uploaded."),
)

private val enFullPolicySections = listOf(
    PolicySectionText(
        title = "1. Data we collect",
        bullets = listOf(
            "Character resources packaged in the APK for rendering stroke order.",
            "Local practice history, HSK progress, and resume state.",
            "Board preferences such as grids, colors, template visibility, and language override.",
            "Recent dictionary searches stored on-device.",
            "Daily reminder preferences (enabled/time/rules) stored on-device.",
            "Optional in-app purchases are handled by Google Play. No ads.",
        ),
    ),
    PolicySectionText(
        title = "2. How data is used",
        bullets = listOf(
            "Resume practice and course progress locally.",
            "Display dictionary cards and HSK summaries fully offline.",
            "Compute progress and streaks locally.",
        ),
    ),
    PolicySectionText(
        title = "3. Permissions",
        bullets = listOf(
            "POST_NOTIFICATIONS (Android 13+): optional, for daily reminders if enabled.",
            "RECEIVE_BOOT_COMPLETED: restore reminders after reboot, app update, or time changes.",
            "Network permission: for optional Google Play purchases and restore. Core learning works offline.",
            "No access to precise location, contacts, camera, or microphone.",
        ),
    ),
    PolicySectionText(
        title = "4. Your controls",
        bullets = listOf(
            "Clear the app's storage in Android settings to reset all data.",
            "All data stays on this device unless you back up your phone.",
        ),
    ),
    PolicySectionText(
        title = "5. Contact",
        bullets = listOf("Email: qq260316514@gmail.com"),
    ),
)

fun localizedStringsEn(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    navigation = enNavigationStrings,
    onboarding = enOnboardingStrings,
    searchLabel = "Hanzi",
    loadButton = "Load character",
    clearButton = "Clear input",
    loadingLabel = "Loading...",
    coursesDialogTitle = "HSK Courses",
    coursePlanHeading = "Pick a course to continue",
    courseIntroTitle = "How courses work",
    courseIntroBullets = listOf(
        "Choose an HSK level to begin or jump back in.",
        "Tap a character to practice; long-press to mark it mastered.",
        "The badge above the board mirrors your current course progress.",
    ),
    courseEmptyTitle = "No active course yet",
    courseEmptyDescription = "Select an HSK level below to start a guided session.",
    courseNoDataMessage = "No course data found. Please double-check the resource pack.",
    expandCharactersLabel = "Show all",
    collapseCharactersLabel = "Hide",
    legendTitle = "Legend & gestures",
    legendGesture = "Tap any character to practice; long-press to mark it as learned.",
    legendActiveLabel = "Active",
    legendCompletedLabel = "Completed",
    legendRemainingLabel = "Remaining",
    courseLegendHint = "Badge controls let you resume, skip, restart, or exit without covering the board.",
    courseLevelCompleteLabel = "Course complete",
    courseLevelStartFormat = "Start with %s",
    courseLevelNextFormat = "Next • %s",
    levelLabelFormat = "Level %d",
    courseLevelProgressFormat = "%1\$d/%2\$d mastered · %3\$d remaining",
    loadLevelFormat = "Load HSK %d",
    filterAllLabel = "All",
    filterRemainingLabel = "Remaining",
    filterCompletedLabel = "Completed",
    helpTitle = "Help & onboarding",
    helpSections = enHelpSections,
    helpConfirm = "Got it",
    privacyTitle = "Privacy",
    privacyIntro = "Fully offline by default.",
    dataSafetyHeading = "Data safety snapshot",
    privacySummaryRows = enPrivacySummaryRows,
    contactSupportLabel = "Contact: %s",
    emailSupportButton = "Email support",
    viewPolicyButton = "View full policy",
    fullPolicyTitle = "Privacy policy",
    fullPolicySections = enFullPolicySections,
    progress = enProgressStrings,
    library = enLibraryStrings,
    courses = enCoursesStrings,
    account = enAccountStrings,
    support = enSupportStrings,
    boardControls = enPracticeBoardStrings,
)
