package com.yourstudio.hskstroke.bishun.ui.character

import java.util.Locale

private val chineseNavigationStrings = NavigationStrings(
    homeLabel = "首页",
    learnLabel = "学习",
    libraryLabel = "字典",
    accountLabel = "我的",
)

private val chinesePracticeBoardStrings = PracticeBoardStrings(
    startLabel = "开始练习",
    hintLabel = "提示",
    previousLabel = "上一个字",
    nextLabel = "下一个字",
    settingsLabel = "画板设置",
    pronunciationLabel = "播放发音",
    dictionaryLabel = "查看字典释义",
    hskLabel = "HSK 信息",
    statusReadyLabel = "准备开始",
    statusStrokeProgressFormat = "笔画 %1\$d/%2\$d",
    statusStartFromStrokeFormat = "从第 %1\$d 笔开始",
    statusTryAgainFormat = "重试（错误 %1\$d 次）",
    statusGreatContinueLabel = "很好！继续下一笔",
    statusBackwardsAcceptedLabel = "笔顺反向但已接受",
    statusPracticeCompleteLabel = "练习完成",
)

private val chineseProgressStrings = ProgressStrings(
    title = "学习进度",
    description = "查看连续练习天数、HSK 各等级掌握情况和最近练习记录。每次书写新的汉字都会自动更新。",
    jumpBackLabel = "返回练习",
    dailyTitle = "每日一字",
    dailyDescription = "每天练习一个汉字。从下一个 HSK 目标中推荐今日内容。",
    dailyPracticeLabel = "练习",
    dailyCompletedLabel = "今日已完成",
    learnedLabel = "已掌握",
    streakLabel = "连续天数",
    lastSessionLabel = "上次练习",
    streakDaySingularFormat = "%1\$d 天",
    streakDayPluralFormat = "%1\$d 天",
    streakStartLabel = "开始",
    lastSessionNeverLabel = "从未",
    weeklyChartTitle = "最近 7 天",
    levelsTitle = "HSK 等级",
    levelsEmpty = "开始练习后，这里会显示各 HSK 等级的进度。",
    levelLabelFormat = "HSK %1\$d",
    levelMasteredFormat = "%1\$d/%2\$d 已掌握",
    levelJumpDescription = "跳到下一个汉字",
    levelBrowseCourses = "浏览课程",
    historyTitle = "最近练习",
    historyEmpty = "书写任意汉字后，会在这里出现，方便快速复习。",
    historyStrokesFormat = "%1\$d 画 · %2\$s",
    historyMistakesPerfect = "零失误",
    historyMistakesFormat = "错误 %1\$d 次",
    historyLoadCharacterFormat = "加载 %1\$s",
    relativeJustNow = "刚刚",
    relativeMinutesFormat = "%1\$d 分钟前",
    relativeHoursFormat = "%1\$d 小时前",
    relativeDaysFormat = "%1\$d 天前",
)

private val chineseLibraryStrings = LibraryStrings(
    title = "字典",
    description = "随时离线查看拼音、部首和释义。输入一个汉字，随时跳转练习。",
    tabSearchLabel = "查字",
    tabFavoritesLabel = "收藏",
    tabHistoryLabel = "历史",
    inputLabel = "汉字",
    supportingText = "提示：输入一个汉字（HSK 1 始终免费）。",
    resultsHeader = "结果",
    quickTryLabel = "试试：",
    recentHeader = "最近搜索",
    recentClear = "清除",
    recentOverflowLabel = "更多…",
    recentOverflowDialogTitle = "最近搜索",
    recentOverflowClose = "关闭",
    lookupLabel = "查询",
    lookupLoadingLabel = "查询中…",
    clearResultLabel = "清除结果",
    editLabel = "编辑",
    doneLabel = "完成",
    selectAllLabel = "全选",
    deselectAllLabel = "取消全选",
    selectedCountFormat = "已选 %1\$d 项",
    deleteLabel = "删除",
    favoritesFilterLabel = "筛选收藏",
    historyFilterLabel = "筛选历史",
    filterNoResultsLabel = "无匹配结果。",
    favoritesHeader = "收藏",
    favoritesEmpty = "收藏汉字或词语，方便日后查看。",
    favoritesSaveLabel = "收藏",
    favoritesSavedLabel = "已收藏",
    favoritesAddLabel = "收藏",
    favoritesRemoveLabel = "移除",
    favoritesClearLabel = "清空",
    favoritesClearDialogTitle = "清空收藏？",
    favoritesClearDialogBody = "将从本机移除所有收藏的字词，此操作不可撤销。",
    favoritesClearConfirmLabel = "清空",
    favoritesClearCancelLabel = "取消",
    historyHeader = "历史",
    historyPinnedHeader = "已固定",
    historyEmpty = "最近查过的字会出现在这里。",
    historyPinLabel = "固定",
    historyUnpinLabel = "取消固定",
    historyRemoveLabel = "移除",
    historyClearLabel = "清除",
    historyClearDialogTitle = "清除历史？",
    historyClearDialogBody = "将从本机清除搜索历史，此操作不可撤销。",
    historyClearConfirmLabel = "清除",
    historyClearCancelLabel = "取消",
    sortRecentLabel = "最近",
    sortNameLabel = "按拼音",
    moreActionsLabel = "更多",
    helpTitle = "使用提示",
    helpBody = "数据来自内置词库，完全离线可用。\n收藏和历史仅保存在本机。\n笔顺和隐私详情见项目文档。",
    pinyinLabelFormat = "拼音：%1\$s",
    radicalsStrokesFormat = "部首：%1\$s    画数：%2\$s",
    traditionalLabelFormat = "繁体：%1\$s",
    definitionFallback = "暂无释义。",
    valueNotAvailable = "无",
    valueUnknown = "?",
    practiceButtonLabel = "练习这个字",
    practiceCharactersLabel = "批量练习",
    quickSuggestions = listOf("永", "学", "好", "中", "发"),
    errorEmpty = "请输入一个汉字进行查询。",
    errorNotFound = "离线词库中未找到该汉字。",
    errorRead = "无法读取词库，请重试。",
)

private val chineseCoursesStrings = CoursesStrings(
    title = "课程",
    description = "浏览 HSK 等级，离线练习每个汉字。",
    emptyCatalogMessage = "未找到课程数据，请确认 assets/learn-datas 已正确打包。",
    filterAll = "全部",
    filterRemaining = "待学",
    filterCompleted = "已掌握",
    legendTitle = "图例",
    legendActive = "进行中",
    legendCompleted = "已掌握",
    legendRemaining = "待学",
    legendHint = "长按任意字卡可将其标记为已掌握。",
    symbolEmptyMessage = "没有符合当前筛选条件的汉字。",
    symbolShowAllLabel = "显示全部",
    symbolCollapseLabel = "收起",
    activeCourseTitleFormat = "进行中 · HSK %1\$d",
    activeCourseStatusFormat = "%1\$s · %2\$s",
    activeResume = "继续",
    activeSkip = "跳过",
    activeRestart = "重来",
    activeExit = "退出",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "%1\$d 级",
    levelProgressFormat = "%1\$d/%2\$d · 待学 %3\$d",
    levelNextFormat = "下一个 · %1\$s",
    levelCompletedLabel = "已完成",
    lockedSignInLabel = "登录",
    lockedUnlockLabel = "解锁",
    lockedBrowseLabel = "浏览课程",
    lockedGreatJobLabel = "太棒了！",
    iconStartDescriptionFormat = "开始 HSK %1\$d",
    toastSkippedLabel = "已跳过",
    toastMarkedLearnedFormat = "已将「%1\$s」标记为已掌握",
    toastCourseCompleteFormat = "HSK %1\$d 已完成！",
    toastAutoAdvancedFormat = "自动进入「%1\$s」",
    toastNextUpFormat = "下一个：%1\$s",
)

private val chineseWidgetStrings = WidgetStrings(
    dailyTitle = "今日一字",
    streakDaysFormat = "连续 %1\$d 天",
    completedTodayLabel = "今日已完成",
    practiceLabel = "练习",
    dictionaryLabel = "字典",
    tapToPracticeLabel = "点击开始练习",
    notificationChannelName = "每日提醒",
    notificationChannelDescription = "提醒你练习今日一字",
)

private val chineseSupportStrings = SupportStrings(
    analyticsTitle = "使用统计",
    analyticsDescription = "匿名计数，用于规划未来功能。",
    crashTitle = "崩溃报告",
    crashDescription = "渲染失败时可分享轻量日志。",
    prefetchTitle = "网络预加载",
    prefetchDescription = "允许 Wi-Fi 下载未来的数据包。",
    privacyCloseLabel = "关闭",
    feedbackTitle = "发送反馈",
    feedbackThanksTitle = "感谢！",
    feedbackSavedMessage = "您的意见已本地保存。下次更新时会连同诊断日志一起导出，不会丢失。",
    feedbackTopicLabel = "主题",
    feedbackTopicPlaceholder = "功能建议、Bug 反馈…",
    feedbackMessageLabel = "详细内容",
    feedbackMessagePlaceholder = "描述您的想法或遇到的问题",
    feedbackContactLabel = "联系方式（选填）",
    feedbackContactPlaceholder = "邮箱或社交账号",
    feedbackSendLabel = "发送",
    feedbackCloseLabel = "关闭",
    feedbackShareLogLabel = "分享日志",
    feedbackCancelLabel = "取消",
    feedbackLastSentFormat = "上次发送：%1\$s",
    feedbackLogEmpty = "日志为空。",
    feedbackLogShareError = "无法分享日志。",
    feedbackLogNoApps = "没有可分享日志的应用。",
    feedbackEmailError = "无法打开邮件，日志已本地保存，之后可在账号页分享。",
    feedbackEmailNoApp = "没有安装邮件应用，日志已本地保存。",
)

private val chineseOnboardingStrings = OnboardingStrings(
    appTitle = "汉字",
    skipLabel = "跳过",
    backLabel = "上一步",
    nextLabel = "下一步",
    startLabel = "开始",
    pages = listOf(
        OnboardingPageText(
            title = "快速查字",
            body = "随时离线查看发音和笔顺。",
        ),
        OnboardingPageText(
            title = "跟练笔顺",
            body = "描摹笔画并获得提示，逐步提升准确度。",
        ),
        OnboardingPageText(
            title = "需要时打开字典",
            body = "在练习中查看拼音与释义，不用离开当前页面。",
        ),
        OnboardingPageText(
            title = "添加桌面小组件",
            body = "把“今日一字”放到桌面，一键开始每日练习。",
        ),
        OnboardingPageText(
            title = "发音更安全",
            body = "开启音量提醒，避免公共场合突然外放过大。",
        ),
    ),
)

private val chineseAccountStrings = AccountStrings(
    title = "设置",
    signInCardTitle = "登录状态",
    signInDescriptionSignedIn = "已登录。购买与解锁内容会与此设备关联。",
    signInDescriptionSignedOut = "访客模式会将练习数据保存在本地离线。只有在准备解锁课程时才需要登录。",
    signInButtonSignedIn = "退出登录",
    signInButtonSignedOut = "登录并同意政策",
    courseCardTitle = "课程解锁",
    courseDescriptionSignedOut = "随时预览 HSK 等级。登录后可完成购买流程。",
    courseDescriptionUnlocked = "已解锁所有高级等级。请在“学习”页继续。",
    courseDescriptionLocked = "一次性解锁会保存本地许可，使课程离线可用。",
    courseButtonSignedOut = "需要登录",
    courseButtonUnlocked = "浏览课程",
    courseButtonLocked = "解锁全部课程",
    supportTitle = "支持",
    supportDescription = "帮助与隐私信息在这里。",
    supportFeedbackButton = "发送反馈",
    clearDataTitle = "重置本地数据",
    clearDataDescription = "清除本机保存的练习记录、课程进度与偏好设置。",
    clearDataButton = "清除本地记录",
    clearDataDialogTitle = "确定清除本地数据？",
    clearDataDialogBody = "将从本机移除练习记录、连续天数、偏好设置与字典搜索历史。此操作不可撤销。",
    consentSignInTitle = "登录前请确认",
    consentSignInBullets = listOf(
        "登录仅用于关联购买记录。练习数据仍保存在本机。",
        "继续表示你已阅读《隐私政策》。",
        "你可以随时保持访客模式——高级内容将保持锁定。",
    ),
    consentSignInConfirm = "同意并登录",
    consentUnlockTitle = "解锁高级内容",
    consentUnlockBullets = listOf(
        "支付凭证会本地缓存，离线也可使用全部内容。",
        "解锁后会在账号页记录购买信息，便于之后恢复。",
        "结算时会再次弹出隐私提示以符合平台要求。",
    ),
    consentUnlockConfirm = "确认解锁",
    consentCheckboxLabel = "我已阅读隐私政策。",
    cancelLabel = "取消",
    closeLabel = "关闭",
    proCardTitle = "Pro",
    proStatusPro = "Pro",
    proStatusFree = "免费",
    proStatusPlayRequired = "需要 Google Play",
    proStatusPending = "待处理购买",
    proStatusConnecting = "连接中…",
    proStatusNotAvailable = "不可用",
    proDescriptionPro = "感谢支持。Pro 可离线使用，并可通过 Google Play 自动恢复。",
    proDescriptionNoPlayStore = "Pro 购买仅在带 Google Play 的设备上可用。请从 Google Play 安装以购买与恢复。",
    proDescriptionFree = "通过一次性购买支持我们。Pro 会随 Google Play 自动恢复。",
    proBillingStatusCodeFormat = "Billing 状态码：%1\$d",
    proRestorePurchasesButton = "恢复购买",
    proBuyButton = "购买",
    proBuyButtonWithPriceFormat = "购买（%1\$s）",
    appearanceCardTitle = "外观",
    appearanceCardDescription = "选择此设备上的显示方式。",
    themeModeSystemLabel = "跟随系统",
    themeModeLightLabel = "浅色",
    themeModeDarkLabel = "深色",
    accentColorLabel = "强调色",
    brushThicknessLabel = "笔画粗细",
    requiresProChipLabelFormat = "%1\$s · Pro",
    accentColorOptionLabels = listOf(
        "紫丁香",
        "宝石蓝",
        "海泡绿",
        "银粉",
        "曲奇棕",
        "姜棕",
        "康乃馨粉",
        "紫红",
    ),
    brushWidthOptionLabels = listOf(
        "细",
        "标准",
        "粗",
    ),
    audioSafetyTitle = "音量安全",
    audioSafetyDescription = "在高音量播放发音前先提醒。",
    audioSafetyVolumeReminderLabel = "音量提醒",
    audioSafetyThresholdLabel = "提醒阈值",
    audioSafetyLowerToLabel = "自动降至",
    guidanceTitle = "新手引导",
    guidanceDescription = "首次使用可查看快速介绍。",
    guidanceOpenButton = "打开引导",
    dailyReminderTitle = "每日提醒",
    dailyReminderDescription = "每天在指定时间提醒你练习今日一字（Android 13+ 需允许通知权限）。",
    dailyReminderEnabledLabel = "开启提醒",
    dailyReminderTimeLabelFormat = "提醒时间：%1\$s",
    dailyReminderChangeTimeButton = "修改",
    dailyReminderOnlyWhenIncompleteLabel = "仅未完成时提醒",
    languageTitle = "语言",
    languageDescription = "覆盖应用内文案语言。",
    languageCurrentFormat = "当前：%1\$s",
    languageChangeButton = "修改",
    languageSystemOption = "跟随系统",
    languageChineseOption = "中文",
    languageEnglishOption = "英语",
    languageSpanishOption = "西班牙语",
    languageJapaneseOption = "日语",
    languageKoreanOption = "韩语",
    languageFrenchOption = "法语",
    dataTitle = "数据",
    dataDescription = "管理存储在此设备上的内容。",
    clearDictionaryHistoryButton = "清除字典历史",
    clearDictionaryHistoryDialogTitle = "清除字典历史",
    clearDictionaryHistoryDialogBody = "移除本机保存的最近字典搜索记录。",
    clearDictionaryHistoryConfirmButton = "清除",
    shareAppButton = "分享给朋友",
    shareAppMessage = "推荐一个好用的汉字笔顺学习工具——Hanzi Dictionary & Strokes，离线也能用！\nhttps://play.google.com/store/apps/details?id=com.yourstudio.hskstroke.bishun",
    rateAppButton = "去 Google Play 评价",
    hskWebsiteButton = "HSK 官方网站",
)

fun localizedStringsZh(locale: Locale): LocalizedStrings {
    val base = localizedStringsEn(locale)
    return base.copy(
        locale = locale,
        appTitle = "汉字笔顺",
        navigation = chineseNavigationStrings,
        onboarding = chineseOnboardingStrings,
        account = chineseAccountStrings,
        searchLabel = "汉字",
        loadButton = "加载汉字",
        clearButton = "清除输入",
        loadingLabel = "加载中…",
        coursesDialogTitle = "HSK 课程",
        coursePlanHeading = "选择课程继续学习",
        courseIntroTitle = "课程使用说明",
        courseIntroBullets = listOf(
            "选择一个 HSK 等级开始，或从上次中断处继续。",
            "点击汉字进行练习；长按将其标记为已掌握。",
            "画板上方徽章实时显示当前课程进度。",
        ),
        courseEmptyTitle = "暂无进行中的课程",
        courseEmptyDescription = "在下方选择一个 HSK 等级，开始有引导的练习。",
        courseNoDataMessage = "未找到课程数据，请检查数据包是否正确打包。",
        expandCharactersLabel = "展开全部",
        collapseCharactersLabel = "收起",
        legendTitle = "图例与操作",
        legendGesture = "点击汉字进行练习；长按将其标记为已掌握。",
        legendActiveLabel = "进行中",
        legendCompletedLabel = "已掌握",
        legendRemainingLabel = "待学",
        courseLegendHint = "徽章内的控制按钮可以在不遮挡画板的情况下继续、跳过、重来或退出。",
        courseLevelCompleteLabel = "课程完成",
        courseLevelStartFormat = "从「%s」开始",
        courseLevelNextFormat = "下一个 · %s",
        levelLabelFormat = "%d 级",
        courseLevelProgressFormat = "%1\$d/%2\$d 已掌握 · 待学 %3\$d",
        loadLevelFormat = "加载 HSK %d",
        filterAllLabel = "全部",
        filterRemainingLabel = "待学",
        filterCompletedLabel = "已掌握",
        helpTitle = "帮助与引导",
        helpConfirm = "知道了",
        privacyTitle = "隐私",
        privacyIntro = "默认完全离线运行。",
        dataSafetyHeading = "数据安全摘要",
        privacySummaryRows = listOf(
            SummaryRowText(
                title = "数据存储",
                detail = "练习记录、课程进度和画板设置仅保存在本地 DataStore 中。",
            ),
            SummaryRowText(
                title = "离线数据包",
                detail = "笔顺动画 JSON 和课程数据均打包在 APK 内。",
            ),
            SummaryRowText(
                title = "通知",
                detail = "可选的每日提醒。Android 13+ 仅在您开启提醒时才会申请通知权限。",
            ),
            SummaryRowText(
                title = "网络",
                detail = "网络权限仅用于 Google Play 内购验证。学习数据不会上传。",
            ),
        ),
        contactSupportLabel = "联系邮箱：%s",
        emailSupportButton = "邮件联系",
        viewPolicyButton = "查看完整隐私政策",
        fullPolicyTitle = "隐私政策",
        fullPolicySections = listOf(
            PolicySectionText(
                title = "1. 我们收集的数据",
                bullets = listOf(
                    "APK 内打包的汉字资源，用于笔顺动画渲染。",
                    "本地练习记录、HSK 进度和继续状态。",
                    "画板偏好（网格、颜色、描红可见性）及语言覆盖设置。",
                    "保存在本机的最近字典搜索记录。",
                    "保存在本机的每日提醒偏好（开启/时间/规则）。",
                    "可选的内购由 Google Play 处理。无广告。",
                ),
            ),
            PolicySectionText(
                title = "2. 数据用途",
                bullets = listOf(
                    "在本地恢复练习和课程进度。",
                    "完全离线显示字典卡片和 HSK 摘要。",
                    "在本地计算学习进度和连续天数。",
                ),
            ),
            PolicySectionText(
                title = "3. 权限",
                bullets = listOf(
                    "POST_NOTIFICATIONS（Android 13+）：可选，用于开启提醒后的每日通知。",
                    "RECEIVE_BOOT_COMPLETED：重启、更新或时间变更后恢复提醒设置。",
                    "网络权限：仅用于 Google Play 内购验证与恢复。核心学习功能完全离线。",
                    "不访问精确位置、通讯录、摄像头或麦克风。",
                ),
            ),
            PolicySectionText(
                title = "4. 您的控制权",
                bullets = listOf(
                    "在 Android 设置中清除 App 存储即可重置所有数据。",
                    "除非主动备份手机，否则所有数据均保存在本设备。",
                ),
            ),
            PolicySectionText(
                title = "5. 联系我们",
                bullets = listOf(
                    "邮箱：qq260316514@gmail.com",
                ),
            ),
        ),
        progress = chineseProgressStrings,
        library = chineseLibraryStrings,
        courses = chineseCoursesStrings,
        support = chineseSupportStrings,
        widget = chineseWidgetStrings,
        boardControls = chinesePracticeBoardStrings,
    )
}
