package com.yourstudio.hskstroke.bishun.ui.character

import java.util.Locale

private val spanishPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Iniciar pr\u00e1ctica",
    hintLabel = "Pista",
    previousLabel = "Car\u00e1cter anterior",
    nextLabel = "Siguiente car\u00e1cter",
    settingsLabel = "Ajustes del tablero",
    pronunciationLabel = "Reproducir pronunciaci\u00f3n",
    dictionaryLabel = "Mostrar definici\u00f3n",
    hskLabel = "Informaci\u00f3n HSK",
    statusReadyLabel = "Listo para empezar",
    statusStrokeProgressFormat = "Trazo %1\$d/%2\$d",
    statusStartFromStrokeFormat = "Empieza desde el trazo %1\$d",
    statusTryAgainFormat = "Intenta de nuevo (errores %1\$d)",
    statusGreatContinueLabel = "\u00a1Bien! Contin\u00faa con el siguiente trazo",
    statusBackwardsAcceptedLabel = "Direcci\u00f3n del trazo invertida, pero aceptada",
    statusPracticeCompleteLabel = "Pr\u00e1ctica completada",
)

private val spanishLibraryStrings = LibraryStrings(
    title = "Diccionario",
    description = "Consulta pinyin, radicales y definiciones rápidas completamente sin conexión. Ingresa un solo carácter y vuelve a Práctica cuando quieras trazarlo.",
    tabSearchLabel = "Buscar",
    tabFavoritesLabel = "Guardados",
    tabHistoryLabel = "Historial",
    inputLabel = "Carácter chino",
    supportingText = "Consejo: escribe un carácter (HSK 1 siempre está desbloqueado).",
    resultsHeader = "Resultados",
    quickTryLabel = "Prueba:",
    recentHeader = "Búsquedas recientes",
    recentClear = "Limpiar",
    recentOverflowLabel = "Más...",
    recentOverflowDialogTitle = "Búsquedas recientes",
    recentOverflowClose = "Cerrar",
    lookupLabel = "Buscar",
    lookupLoadingLabel = "Buscando...",
    clearResultLabel = "Borrar resultado",
    editLabel = "Editar",
    doneLabel = "Listo",
    selectAllLabel = "Seleccionar todo",
    deselectAllLabel = "Quitar selección",
    selectedCountFormat = "%1\$d seleccionados",
    deleteLabel = "Eliminar",
    favoritesFilterLabel = "Filtrar guardados",
    historyFilterLabel = "Filtrar historial",
    filterNoResultsLabel = "Sin coincidencias.",
    favoritesHeader = "Guardados",
    favoritesEmpty = "Guarda un carácter o palabra para verla más tarde.",
    favoritesSaveLabel = "Guardar",
    favoritesSavedLabel = "Guardado",
    favoritesAddLabel = "Guardar",
    favoritesRemoveLabel = "Quitar",
    favoritesClearLabel = "Limpiar",
    favoritesClearDialogTitle = "¿Limpiar guardados?",
    favoritesClearDialogBody = "Esto elimina todos los elementos guardados del diccionario en este dispositivo.",
    favoritesClearConfirmLabel = "Limpiar",
    favoritesClearCancelLabel = "Cancelar",
    historyHeader = "Historial",
    historyPinnedHeader = "Fijados",
    historyEmpty = "Tus búsquedas recientes aparecerán aquí.",
    historyPinLabel = "Fijar",
    historyUnpinLabel = "Quitar fijación",
    historyRemoveLabel = "Quitar",
    historyClearLabel = "Limpiar",
    historyClearDialogTitle = "¿Limpiar historial?",
    historyClearDialogBody = "Esto borra el historial del diccionario en este dispositivo.",
    historyClearConfirmLabel = "Limpiar",
    historyClearCancelLabel = "Cancelar",
    sortRecentLabel = "Reciente",
    sortNameLabel = "A–Z",
    moreActionsLabel = "Más",
    helpTitle = "Consejos",
    helpBody = "- Los datos provienen del word.db incluido, así que funciona sin conexión.\n- Guardados e historial se quedan solo en el dispositivo.\n- Para detalles de caligrafía y privacidad revisa docs/help-guide.md dentro del proyecto.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Trazos: %2\$s",
    traditionalLabelFormat = "Tradicional: %1\$s",
    definitionFallback = "Sin definición disponible.",
    valueNotAvailable = "N/D",
    valueUnknown = "?",
    practiceButtonLabel = "Practicar este carácter",
    practiceCharactersLabel = "Practicar caracteres",
    quickSuggestions = listOf("永", "发", "学", "好", "汉"),
    errorEmpty = "Ingresa un carácter para buscar.",
    errorNotFound = "Carácter no encontrado en el diccionario sin conexión.",
    errorRead = "No se pudo leer el diccionario. Intenta de nuevo.",
)

private val spanishCoursesStrings = CoursesStrings(
    title = "Cursos",
    description = "Explora niveles HSK y practica cada carácter completamente sin conexión.",
    emptyCatalogMessage = "No se encontraron datos del curso. Comprueba que assets/learn-datas esté incluido en el APK.",
    filterAll = "Todos",
    filterRemaining = "Pendientes",
    filterCompleted = "Completados",
    legendTitle = "Leyenda",
    legendActive = "Activo",
    legendCompleted = "Completado",
    legendRemaining = "Pendiente",
    legendHint = "Mantén pulsado cualquier icono para marcarlo como aprendido.",
    symbolEmptyMessage = "Ningún carácter coincide con el filtro actual.",
    symbolShowAllLabel = "Mostrar todos los caracteres",
    symbolCollapseLabel = "Ocultar lista",
    activeCourseTitleFormat = "Curso activo · HSK %1\$d",
    activeCourseStatusFormat = "Carácter %1\$s · %2\$s",
    activeResume = "Reanudar",
    activeSkip = "Saltar",
    activeRestart = "Reiniciar",
    activeExit = "Salir",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Nivel %1\$d",
    levelProgressFormat = "%1\$d/%2\$d · faltan %3\$d",
    levelNextFormat = "Siguiente · %1\$s",
    levelCompletedLabel = "Completado",
    lockedSignInLabel = "Iniciar sesión",
    lockedUnlockLabel = "Desbloquear",
    lockedBrowseLabel = "Ver cursos",
    lockedGreatJobLabel = "¡Buen trabajo!",
    iconStartDescriptionFormat = "Iniciar HSK %1\$d",
    toastSkippedLabel = "Carácter omitido",
    toastMarkedLearnedFormat = "Marcaste %1\$s como aprendido",
    toastCourseCompleteFormat = "HSK %1\$d completado",
    toastAutoAdvancedFormat = "Avance automático a %1\$s",
    toastNextUpFormat = "Siguiente: %1\$s",
)

private val spanishAccountStrings = AccountStrings(
    title = "Ajustes",
    signInCardTitle = "Estado de sesión",
    signInDescriptionSignedIn = "Sesión iniciada. Las compras y niveles desbloqueados siguen ligados a este dispositivo.",
    signInDescriptionSignedOut = "El modo invitado mantiene los datos de práctica sin conexión. Inicia sesión solo cuando quieras desbloquear cursos.",
    signInButtonSignedIn = "Cerrar sesión",
    signInButtonSignedOut = "Iniciar sesión y aceptar política",
    courseCardTitle = "Desbloqueo de cursos",
    courseDescriptionSignedOut = "Consulta los niveles HSK cuando quieras. Inicia sesión para completar la compra.",
    courseDescriptionUnlocked = "Todos los niveles premium están desbloqueados. Continúa desde la pestaña Cursos.",
    courseDescriptionLocked = "Un desbloqueo único guarda una licencia local para que las lecciones sigan disponibles offline.",
    courseButtonSignedOut = "Se requiere sesión",
    courseButtonUnlocked = "Ver cursos",
    courseButtonLocked = "Desbloquear todos los cursos",
    supportTitle = "Soporte",
    supportDescription = "La ayuda y la información de privacidad viven aquí.",
    supportFeedbackButton = "Enviar comentarios",
    clearDataTitle = "Restablecer datos locales",
    clearDataDescription = "Elimina el historial de práctica, el progreso y las preferencias guardadas en este dispositivo.",
    clearDataButton = "Borrar registros locales",
    clearDataDialogTitle = "¿Borrar datos locales?",
    clearDataDialogBody = "Se eliminarán el historial, las rachas, las preferencias y las búsquedas del diccionario de este dispositivo. Esta acción no se puede deshacer.",
    consentSignInTitle = "Antes de iniciar sesión",
    consentSignInBullets = listOf(
        "Solo necesitas iniciar sesión para asociar compras. Los datos de práctica permanecen en el dispositivo.",
        "Al continuar confirmas que revisaste la Política de Privacidad.",
        "Puedes seguir en modo invitado: las lecciones premium simplemente seguirán bloqueadas.",
    ),
    consentSignInConfirm = "Aceptar e iniciar sesión",
    consentUnlockTitle = "Desbloquear lecciones premium",
    consentUnlockBullets = listOf(
        "Los tokens de pago se guardan localmente para que todo funcione sin conexión.",
        "El desbloqueo también registra la compra en la pestaña Cuenta para restauraciones posteriores.",
        "Durante el pago volverá a mostrarse un recordatorio de privacidad por cumplimiento.",
    ),
    consentUnlockConfirm = "Confirmar desbloqueo",
    consentCheckboxLabel = "Ya revisé la política de privacidad.",
    cancelLabel = "Cancelar",
    closeLabel = "Cerrar",
    proCardTitle = "Pro",
    proStatusPro = "Pro",
    proStatusFree = "Gratis",
    proStatusPlayRequired = "Se requiere Google Play",
    proStatusPending = "Compra pendiente",
    proStatusConnecting = "Conectando\u2026",
    proStatusNotAvailable = "No disponible",
    proDescriptionPro = "Gracias por apoyar la app. Pro sigue disponible sin conexión y se restaura automáticamente con Google Play.",
    proDescriptionNoPlayStore = "La compra Pro solo está disponible en dispositivos con Google Play. Instala desde Google Play para comprar y restaurar compras.",
    proDescriptionFree = "Apoya la app con una compra única. Pro se restaura automáticamente con Google Play.",
    proBillingStatusCodeFormat = "Código de estado de facturación: %1\$d",
    proRestorePurchasesButton = "Restaurar compras",
    proBuyButton = "Comprar",
    proBuyButtonWithPriceFormat = "Comprar (%1\$s)",
    appearanceCardTitle = "Apariencia",
    appearanceCardDescription = "Elige cómo se ve la app en este dispositivo.",
    themeModeSystemLabel = "Sistema",
    themeModeLightLabel = "Claro",
    themeModeDarkLabel = "Oscuro",
    accentColorLabel = "Color de acento",
    brushThicknessLabel = "Grosor del trazo",
    requiresProChipLabelFormat = "%1\$s \u00b7 Pro",
    accentColorOptionLabels = listOf(
        "Lila",
        "Azul zafiro",
        "Verde espuma de mar",
        "Rosa plateado",
        "Marrón galleta",
        "Marrón jengibre",
        "Rosa clavel oscuro",
        "Rojo violeta medio",
    ),
    brushWidthOptionLabels = listOf(
        "Fino",
        "Normal",
        "Grueso",
    ),
    audioSafetyTitle = "Seguridad de audio",
    audioSafetyDescription = "Muestra un recordatorio antes de reproducir la pronunciación con volumen alto.",
    audioSafetyVolumeReminderLabel = "Recordatorio de volumen",
    audioSafetyThresholdLabel = "Umbral del recordatorio",
    audioSafetyLowerToLabel = "Bajar a",
    guidanceTitle = "Primeros pasos",
    guidanceDescription = "Revisa la guía rápida para usuarios nuevos.",
    guidanceOpenButton = "Abrir guía",
    dailyReminderTitle = "Recordatorio diario",
    dailyReminderDescription = "Recibe una notificación diaria para practicar el carácter de hoy (Android 13+ requiere permiso de notificaciones).",
    dailyReminderEnabledLabel = "Activar recordatorio",
    dailyReminderTimeLabelFormat = "Hora del recordatorio: %1\$s",
    dailyReminderChangeTimeButton = "Cambiar",
    dailyReminderOnlyWhenIncompleteLabel = "Solo si no está completado",
    languageTitle = "Idioma",
    languageDescription = "Sobrescribe el idioma del contenido.",
    languageCurrentFormat = "Actual: %1\$s",
    languageChangeButton = "Cambiar",
    languageSystemOption = "Sistema",
    languageChineseOption = "Chino",
    languageEnglishOption = "Ingl\u00e9s",
    languageSpanishOption = "Espa\u00f1ol",
    languageJapaneseOption = "Japon\u00e9s",
    dataTitle = "Datos",
    dataDescription = "Gestiona lo que se guarda en este dispositivo.",
    clearDictionaryHistoryButton = "Borrar historial del diccionario",
    clearDictionaryHistoryDialogTitle = "Borrar historial del diccionario",
    clearDictionaryHistoryDialogBody = "Elimina las b\u00fasquedas recientes del diccionario guardadas en este dispositivo.",
    clearDictionaryHistoryConfirmButton = "Borrar",
    shareAppButton = "Compartir app",
    shareAppMessage = "Descubre Hanzi Dictionary & Strokes — aprende el orden de trazos chino sin conexión.\nhttps://play.google.com/store/apps/details?id=com.yourstudio.hskstroke.bishun",
    rateAppButton = "Valorar en Google Play",
)

private val spanishSupportStrings = SupportStrings(
    analyticsTitle = "Analítica de uso",
    analyticsDescription = "Contadores anónimos para funciones futuras.",
    crashTitle = "Informes de fallos",
    crashDescription = "Comparte registros ligeros si falla el renderizado.",
    prefetchTitle = "Prefetch de red",
    prefetchDescription = "Permite descargas por Wi‑Fi de paquetes futuros.",
    privacyCloseLabel = "Cerrar",
    feedbackTitle = "Enviar comentarios",
    feedbackThanksTitle = "¡Gracias!",
    feedbackSavedMessage = "Guardamos tu nota localmente. La próxima versión la adjuntará a los diagnósticos para que nada se pierda.",
    feedbackTopicLabel = "Tema",
    feedbackTopicPlaceholder = "Solicitud, error...",
    feedbackMessageLabel = "Detalles",
    feedbackMessagePlaceholder = "Describe la idea o el problema",
    feedbackContactLabel = "Contacto (opcional)",
    feedbackContactPlaceholder = "Correo o usuario",
    feedbackSendLabel = "Enviar",
    feedbackCloseLabel = "Cerrar",
    feedbackShareLogLabel = "Compartir registro",
    feedbackCancelLabel = "Cancelar",
    feedbackLastSentFormat = "Último envío: %1\$s",
    feedbackLogEmpty = "El registro está vacío.",
    feedbackLogShareError = "No se pudo compartir el registro.",
    feedbackLogNoApps = "No hay aplicaciones disponibles para compartir el registro.",
    feedbackEmailError = "No se pudo abrir el correo. El registro quedó guardado; compártelo luego desde Cuenta.",
    feedbackEmailNoApp = "No hay aplicaciones de correo instaladas. El registro quedó guardado; compártelo luego desde Cuenta.",
)

private val spanishNavigationStrings = NavigationStrings(
    homeLabel = "Inicio",
    learnLabel = "Aprender",
    libraryLabel = "Diccionario",
    accountLabel = "Ajustes",
)

private val spanishOnboardingStrings = OnboardingStrings(
    appTitle = "Hanzi",
    skipLabel = "Saltar",
    backLabel = "Atrás",
    nextLabel = "Siguiente",
    startLabel = "Empezar",
    pages = listOf(
        OnboardingPageText(
            title = "Busca caracteres rápido",
            body = "Consulta el orden de trazos y la pronunciación sin conexión, cuando lo necesites.",
        ),
        OnboardingPageText(
            title = "Practica con guía",
            body = "Traza los trazos y recibe pistas para mejorar la precisión y la confianza.",
        ),
        OnboardingPageText(
            title = "Diccionario cuando necesites detalles",
            body = "Abre la tarjeta del diccionario para ver pinyin y significado sin salir de la práctica.",
        ),
        OnboardingPageText(
            title = "Añade el widget Diario",
            body = "Fija el widget Diario en tu pantalla de inicio para practicar y escuchar con un toque.",
        ),
        OnboardingPageText(
            title = "Reproducción de audio más segura",
            body = "Activa recordatorios de volumen para evitar reproducir audio demasiado alto en público.",
        ),
    ),
)

fun localizedStringsEs(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    navigation = spanishNavigationStrings,
    onboarding = spanishOnboardingStrings,
    searchLabel = "Hanzi",
    loadButton = "Cargar carácter",
    clearButton = "Borrar",
    loadingLabel = "Cargando...",
    coursesDialogTitle = "Cursos HSK",
    coursePlanHeading = "Elige un curso para continuar",
    courseIntroTitle = "Cómo funcionan los cursos",
    courseIntroBullets = listOf(
        "Selecciona un nivel HSK para comenzar o retomar el estudio.",
        "Toca un carácter para practicar; mantén pulsado para marcarlo como dominado.",
        "La insignia sobre el tablero refleja tu progreso actual.",
    ),
    courseEmptyTitle = "Sin curso activo",
    courseEmptyDescription = "Selecciona un nivel HSK para iniciar una sesión guiada.",
    courseNoDataMessage = "No se encontraron datos del curso. Comprueba el paquete de recursos.",
    expandCharactersLabel = "Mostrar todo",
    collapseCharactersLabel = "Ocultar",
    legendTitle = "Leyenda y gestos",
    legendGesture = "Toca un carácter para practicar; mantén pulsado para marcarlo como aprendido.",
    legendActiveLabel = "Activo",
    legendCompletedLabel = "Completado",
    legendRemainingLabel = "Pendiente",
    courseLegendHint = "Usa los controles de la insignia para reanudar, saltar, reiniciar o salir sin cubrir el tablero.",
    courseLevelCompleteLabel = "Curso completo",
    courseLevelStartFormat = "Empieza con %s",
    courseLevelNextFormat = "Siguiente • %s",
    levelLabelFormat = "Nivel %d",
    courseLevelProgressFormat = "%1\$d/%2\$d dominados · faltan %3\$d",
    loadLevelFormat = "Abrir HSK %d",
    filterAllLabel = "Todos",
    filterRemainingLabel = "Pendientes",
    filterCompletedLabel = "Completados",
    helpTitle = "Ayuda e introducción",
    helpSections = listOf(
        HelpSectionText(
            title = "Inicio rápido",
            description = "Completa un ciclo de demostración → práctica en segundos.",
            bullets = listOf(
                "Escribe cualquier hanzi y toca el ícono de nube para cargar los datos sin conexión.",
                "Usa Reproducir o Bucle para ver la demostración; activa la plantilla caligráfica para calcar.",
                "Pulsa el lápiz en el tablero para empezar; el ícono de pista resalta el siguiente trazo.",
            ),
        ),
        HelpSectionText(
            title = "Cursos y progreso",
            description = "Los cursos HSK viven bajo el avatar y la insignia muestra tu estado.",
            bullets = listOf(
                "Los botones Reanudar/Saltar/Reiniciar/Salir permanecen en la insignia para no tapar el tablero.",
                "Las flechas cambian de carácter; al terminar uno se actualiza el resumen al instante.",
            ),
        ),
        HelpSectionText(
            title = "Tarjetas y pronunciación",
            description = "La tarjeta en caligrafía muestra el diccionario y la voz sintética.",
            bullets = listOf(
                "Toca la tarjeta para abrir la definición completa y desplazarte por la explicación.",
                "El botón de altavoz reproduce audio en mandarín sin conexión.",
            ),
        ),
        HelpSectionText(
            title = "Cuadrículas y plantillas",
            description = "El tablero admite cuadrícula mi, cuadrícula de nueve o sin guías.",
            bullets = listOf(
                "Cambia entre modo con plantilla o libre; los colores de los trazos se conservan.",
                "Desplázate fuera del lienzo para mover la página y mantener fija la zona de escritura.",
            ),
        ),
        HelpSectionText(
            title = "Soporte",
            description = "¿Necesitas ayuda? Escríbenos.",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
                "El aprendizaje funciona sin conexión y tus datos se quedan en el dispositivo.",
            ),
        ),
    ),
    helpConfirm = "Entendido",
    privacyTitle = "Privacidad",
    privacyIntro = "Funciona sin conexión por defecto.",
    dataSafetyHeading = "Resumen de seguridad de datos",
    privacySummaryRows = listOf(
        SummaryRowText(
            title = "Almacenamiento",
            detail = "Historial de práctica, progreso y ajustes del tablero permanecen solo en DataStore local.",
        ),
        SummaryRowText(
            title = "Recursos sin conexión",
            detail = "Los paquetes de trazos y cursos vienen en el APK.",
        ),
        SummaryRowText(
            title = "Notificaciones",
            detail = "Recordatorios diarios opcionales. En Android 13+ la app solicita permiso de notificaciones solo si activas los recordatorios.",
        ),
        SummaryRowText(
            title = "Red",
            detail = "Permiso de red usado solo para compras y restauración con Google Play. Los datos de aprendizaje no se suben.",
        ),
    ),
    contactSupportLabel = "Contacto: %s",
    emailSupportButton = "Enviar correo",
    viewPolicyButton = "Ver política completa",
    fullPolicyTitle = "Política de privacidad",
    fullPolicySections = listOf(
        PolicySectionText(
            title = "1. Datos que recopilamos",
            bullets = listOf(
                "Recursos de caracteres incluidos en el APK para mostrar el orden de los trazos.",
                "Historial local de práctica, progreso HSK y estado de reanudación.",
                "Preferencias del tablero y ajuste de idioma guardados localmente.",
                "Búsquedas recientes del diccionario guardadas en el dispositivo.",
                "Preferencias de recordatorios diarios (activado/hora/reglas) guardadas en el dispositivo.",
                "Compras dentro de la app opcionales gestionadas por Google Play. Sin anuncios.",
            ),
        ),
        PolicySectionText(
            title = "2. Uso de los datos",
            bullets = listOf(
                "Reanudar práctica y cursos localmente.",
                "Mostrar tarjetas y resúmenes HSK totalmente sin conexión.",
                "Calcular progreso y rachas en el dispositivo.",
            ),
        ),
        PolicySectionText(
            title = "3. Permisos",
            bullets = listOf(
                "POST_NOTIFICATIONS (Android 13+): opcional, para mostrar recordatorios diarios si están activados.",
                "RECEIVE_BOOT_COMPLETED: restaura los recordatorios tras reiniciar el dispositivo o cambiar la hora.",
                "Permiso de red: usado solo para compras y restauración con Google Play. El aprendizaje funciona sin conexión.",
                "Sin acceso a ubicación precisa, contactos, cámara o micrófono.",
            ),
        ),
        PolicySectionText(
            title = "4. Tus controles",
            bullets = listOf(
                "Borra los datos de la app en Ajustes de Android para reiniciar todo.",
                "Los datos se quedan en tu dispositivo salvo copias de seguridad del sistema.",
            ),
        ),
        PolicySectionText(
            title = "5. Contacto",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
            ),
        ),
    ),
    progress = ProgressStrings(
        title = "Progreso",
        description = "Consulta rachas, finalización de HSK y el historial de práctica más reciente. Todo se actualiza automáticamente al trazar nuevos caracteres.",
        jumpBackLabel = "Volver a Práctica",
        dailyTitle = "Diario",
        dailyDescription = "Practica un carácter al día. Sugerido a partir de tu próximo objetivo HSK.",
        dailyPracticeLabel = "Practicar",
        dailyCompletedLabel = "Completado hoy",
        learnedLabel = "Aprendidos",
        streakLabel = "Racha",
        lastSessionLabel = "Última sesión",
        streakDaySingularFormat = "%1\$d día",
        streakDayPluralFormat = "%1\$d días",
        streakStartLabel = "Comienza",
        lastSessionNeverLabel = "Nunca",
        weeklyChartTitle = "Últimos 7 días",
        levelsTitle = "Niveles",
        levelsEmpty = "Inicia una sesión de práctica para ver los niveles HSK aquí.",
        levelLabelFormat = "HSK %1\$d",
        levelMasteredFormat = "%1\$d/%2\$d dominados",
        levelJumpDescription = "Ir al siguiente carácter",
        levelBrowseCourses = "Ver cursos",
        historyTitle = "Práctica reciente",
        historyEmpty = "Cuando traces un carácter aparecerá aquí para repasarlo rápidamente.",
        historyStrokesFormat = "%1\$d trazos · %2\$s",
        historyMistakesPerfect = "Sin errores",
        historyMistakesFormat = "%1\$d errores",
        historyLoadCharacterFormat = "Cargar %1\$s",
        relativeJustNow = "justo ahora",
        relativeMinutesFormat = "hace %1\$d min",
        relativeHoursFormat = "hace %1\$d h",
        relativeDaysFormat = "hace %1\$d d",
    ),
    library = spanishLibraryStrings,
    courses = spanishCoursesStrings,
    account = spanishAccountStrings,
    support = spanishSupportStrings,
    boardControls = spanishPracticeBoardStrings,
)

