package com.yourstudio.hskstroke.bishun.ui.character

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import java.util.Locale

data class HelpSectionText(
    val title: String,
    val description: String,
    val bullets: List<String>,
)

data class PolicySectionText(
    val title: String,
    val bullets: List<String>,
)

data class SummaryRowText(val title: String, val detail: String)

data class CoursesStrings(
    val title: String,
    val description: String,
    val emptyCatalogMessage: String,
    val filterAll: String,
    val filterRemaining: String,
    val filterCompleted: String,
    val legendTitle: String,
    val legendActive: String,
    val legendCompleted: String,
    val legendRemaining: String,
    val legendHint: String,
    val symbolEmptyMessage: String,
    val symbolShowAllLabel: String,
    val symbolCollapseLabel: String,
    val activeCourseTitleFormat: String,
    val activeCourseStatusFormat: String,
    val activeResume: String,
    val activeSkip: String,
    val activeRestart: String,
    val activeExit: String,
    val levelHeaderFormat: String,
    val levelChipFormat: String,
    val levelProgressFormat: String,
    val levelNextFormat: String,
    val levelCompletedLabel: String,
    val lockedSignInLabel: String,
    val lockedUnlockLabel: String,
    val lockedBrowseLabel: String,
    val lockedGreatJobLabel: String,
    val iconStartDescriptionFormat: String,
)

data class AccountStrings(
    val title: String,
    val signInCardTitle: String,
    val signInDescriptionSignedIn: String,
    val signInDescriptionSignedOut: String,
    val signInButtonSignedIn: String,
    val signInButtonSignedOut: String,
    val courseCardTitle: String,
    val courseDescriptionSignedOut: String,
    val courseDescriptionUnlocked: String,
    val courseDescriptionLocked: String,
    val courseButtonSignedOut: String,
    val courseButtonUnlocked: String,
    val courseButtonLocked: String,
    val supportTitle: String,
    val supportDescription: String,
    val supportFeedbackButton: String,
    val clearDataTitle: String,
    val clearDataDescription: String,
    val clearDataButton: String,
    val clearDataDialogTitle: String,
    val clearDataDialogBody: String,
    val consentSignInTitle: String,
    val consentSignInBullets: List<String>,
    val consentSignInConfirm: String,
    val consentUnlockTitle: String,
    val consentUnlockBullets: List<String>,
    val consentUnlockConfirm: String,
    val consentCheckboxLabel: String,
    val cancelLabel: String,
    val closeLabel: String,
)

data class SupportStrings(
    val analyticsTitle: String,
    val analyticsDescription: String,
    val crashTitle: String,
    val crashDescription: String,
    val prefetchTitle: String,
    val prefetchDescription: String,
    val privacyCloseLabel: String,
    val feedbackTitle: String,
    val feedbackThanksTitle: String,
    val feedbackSavedMessage: String,
    val feedbackTopicLabel: String,
    val feedbackTopicPlaceholder: String,
    val feedbackMessageLabel: String,
    val feedbackMessagePlaceholder: String,
    val feedbackContactLabel: String,
    val feedbackContactPlaceholder: String,
    val feedbackSendLabel: String,
    val feedbackCloseLabel: String,
    val feedbackShareLogLabel: String,
    val feedbackCancelLabel: String,
    val feedbackLastSentFormat: String,
    val feedbackLogEmpty: String,
    val feedbackLogShareError: String,
    val feedbackLogNoApps: String,
    val feedbackEmailError: String,
    val feedbackEmailNoApp: String,
)

data class PracticeBoardStrings(
    val startLabel: String,
    val hintLabel: String,
    val previousLabel: String,
    val nextLabel: String,
    val settingsLabel: String,
    val pronunciationLabel: String,
    val dictionaryLabel: String,
    val hskLabel: String,
)

private val defaultPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Start practice",
    hintLabel = "Hint",
    previousLabel = "Previous character",
    nextLabel = "Next character",
    settingsLabel = "Canvas settings",
    pronunciationLabel = "Play pronunciation",
    dictionaryLabel = "Show dictionary entry",
    hskLabel = "HSK info",
)

private val spanishPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Iniciar pr\u00e1ctica",
    hintLabel = "Pista",
    previousLabel = "Car\u00e1cter anterior",
    nextLabel = "Siguiente car\u00e1cter",
    settingsLabel = "Ajustes del tablero",
    pronunciationLabel = "Reproducir pronunciaci\u00f3n",
    dictionaryLabel = "Mostrar definici\u00f3n",
    hskLabel = "Informaci\u00f3n HSK",
)

private val japanesePracticeBoardStrings = PracticeBoardStrings(
    startLabel = "\u7df4\u7fd2\u3092\u958b\u59cb",
    hintLabel = "\u30d2\u30f3\u30c8",
    previousLabel = "\u524d\u306e\u6587\u5b57",
    nextLabel = "\u6b21\u306e\u6587\u5b57",
    settingsLabel = "\u30dc\u30fc\u30c9\u8a2d\u5b9a",
    pronunciationLabel = "\u767a\u97f3\u3092\u518d\u751f",
    dictionaryLabel = "\u8f9e\u66f8\u3092\u898b\u308b",
    hskLabel = "HSK\u60c5\u5831",
)

private val japaneseProgressStrings = ProgressStrings(
    title = "\u9032\u6357",
    description = "HSK\u306e\u9054\u6210\u72b6\u6cc1\u3084\u9023\u7d9a\u65e5\u6570\u3001\u6700\u8fd1\u306e\u7df4\u7fd2\u5c65\u6b74\u3092\u78ba\u8a8d\u3067\u304d\u307e\u3059\u3002\u65b0\u3057\u3044\u6f22\u5b57\u3092\u66f8\u304f\u305f\u3073\u306b\u81ea\u52d5\u3067\u66f4\u65b0\u3055\u308c\u307e\u3059\u3002",
    jumpBackLabel = "\u7df4\u7fd2\u306b\u623b\u308b",
    learnedLabel = "\u7fd2\u5f97\u6e08\u307f",
    streakLabel = "\u9023\u7d9a\u65e5\u6570",
    lastSessionLabel = "\u6700\u7d42\u30bb\u30c3\u30b7\u30e7\u30f3",
    streakDaySingularFormat = "%1\$d\u65e5",
    streakDayPluralFormat = "%1\$d\u65e5",
    streakStartLabel = "\u958b\u59cb",
    lastSessionNeverLabel = "\u672a\u5b9f\u65bd",
    weeklyChartTitle = "\u76f4\u8fd1 7 \u65e5",
    levelsTitle = "HSK\u30ec\u30d9\u30eb",
    levelsEmpty = "\u7df4\u7fd2\u3092\u958b\u59cb\u3059\u308b\u3068\u3001\u3053\u3053\u306b\u30ec\u30d9\u30eb\u306e\u9032\u6357\u304c\u8868\u793a\u3055\u308c\u307e\u3059\u3002",
    levelLabelFormat = "HSK %1\$d",
    levelMasteredFormat = "%1\$d/%2\$d \u6587\u5b57",
    levelJumpDescription = "\u6b21\u306e\u6f22\u5b57\u3078",
    levelBrowseCourses = "\u30b3\u30fc\u30b9\u3092\u898b\u308b",
    historyTitle = "\u6700\u8fd1\u306e\u7df4\u7fd2",
    historyEmpty = "\u6f22\u5b57\u3092\u66f8\u304f\u3068\u3053\u3053\u306b\u8868\u793a\u3055\u308c\u3001\u3059\u3050\u306b\u5fa9\u7fd2\u3067\u304d\u307e\u3059\u3002",
    historyStrokesFormat = "%1\$d\u753b \u00b7 %2\$s",
    historyMistakesPerfect = "\u30df\u30b9\u306a\u3057",
    historyMistakesFormat = "\u30df\u30b9 %1\$d\u56de",
    historyLoadCharacterFormat = "%1\$s \u3092\u8aad\u307f\u8fbc\u3080",
    relativeJustNow = "\u305f\u3063\u305f\u4eca",
    relativeMinutesFormat = "%1\$d\u5206\u524d",
    relativeHoursFormat = "%1\$d\u6642\u9593\u524d",
    relativeDaysFormat = "%1\$d\u65e5\u524d",
)

data class ProgressStrings(
    val title: String,
    val description: String,
    val jumpBackLabel: String,
    val learnedLabel: String,
    val streakLabel: String,
    val lastSessionLabel: String,
    val streakDaySingularFormat: String,
    val streakDayPluralFormat: String,
    val streakStartLabel: String,
    val lastSessionNeverLabel: String,
    val weeklyChartTitle: String,
    val levelsTitle: String,
    val levelsEmpty: String,
    val levelLabelFormat: String,
    val levelMasteredFormat: String,
    val levelJumpDescription: String,
    val levelBrowseCourses: String,
    val historyTitle: String,
    val historyEmpty: String,
    val historyStrokesFormat: String,
    val historyMistakesPerfect: String,
    val historyMistakesFormat: String,
    val historyLoadCharacterFormat: String,
    val relativeJustNow: String,
    val relativeMinutesFormat: String,
    val relativeHoursFormat: String,
    val relativeDaysFormat: String,
)

data class LibraryStrings(
    val title: String,
    val description: String,
    val inputLabel: String,
    val supportingText: String,
    val quickTryLabel: String,
    val recentHeader: String,
    val recentClear: String,
    val recentOverflowLabel: String,
    val recentOverflowDialogTitle: String,
    val recentOverflowClose: String,
    val lookupLabel: String,
    val lookupLoadingLabel: String,
    val clearResultLabel: String,
    val helpTitle: String,
    val helpBody: String,
    val pinyinLabelFormat: String,
    val radicalsStrokesFormat: String,
    val traditionalLabelFormat: String,
    val definitionFallback: String,
    val valueNotAvailable: String,
    val valueUnknown: String,
    val practiceButtonLabel: String,
    val quickSuggestions: List<String>,
    val errorEmpty: String,
    val errorNotFound: String,
    val errorRead: String,
)

data class LocalizedStrings(
    val locale: Locale,
    val appTitle: String,
    val searchLabel: String,
    val loadButton: String,
    val clearButton: String,
    val loadingLabel: String,
    val coursesDialogTitle: String,
    val coursePlanHeading: String,
    val courseIntroTitle: String,
    val courseIntroBullets: List<String>,
    val courseEmptyTitle: String,
    val courseEmptyDescription: String,
    val courseNoDataMessage: String,
    val expandCharactersLabel: String,
    val collapseCharactersLabel: String,
    val legendTitle: String,
    val legendGesture: String,
    val legendActiveLabel: String,
    val legendCompletedLabel: String,
    val legendRemainingLabel: String,
    val courseLegendHint: String,
    val courseLevelCompleteLabel: String,
    val courseLevelStartFormat: String,
    val courseLevelNextFormat: String,
    val levelLabelFormat: String,
    val courseLevelProgressFormat: String,
    val loadLevelFormat: String,
    val filterAllLabel: String,
    val filterRemainingLabel: String,
    val filterCompletedLabel: String,
    val helpTitle: String,
    val helpSections: List<HelpSectionText>,
    val helpConfirm: String,
    val privacyTitle: String,
    val privacyIntro: String,
    val dataSafetyHeading: String,
    val privacySummaryRows: List<SummaryRowText>,
    val contactSupportLabel: String,
    val emailSupportButton: String,
    val viewPolicyButton: String,
    val fullPolicyTitle: String,
    val fullPolicySections: List<PolicySectionText>,
    val progress: ProgressStrings,
    val library: LibraryStrings,
    val courses: CoursesStrings,
    val account: AccountStrings,
    val support: SupportStrings,
    val boardControls: PracticeBoardStrings,
)

@Composable
fun rememberLocalizedStrings(languageOverride: String?): LocalizedStrings {
    val contextLocale = LocalContext.current.resources.configuration.locales[0]
    val targetLocale = remember(languageOverride, contextLocale) {
        languageOverride?.takeIf { it.isNotBlank() }?.let { Locale.forLanguageTag(it) } ?: contextLocale
    }
    return remember(targetLocale) {
        when (targetLocale.language) {
            "es" -> localizedStringsEs(targetLocale)
            "ja" -> localizedStringsJa(targetLocale)
            else -> localizedStringsEn(targetLocale)
        }
    }
}

private val defaultCoursesStrings = CoursesStrings(
    title = "Courses",
    description = "Preview every HSK pack for free. Unlock premium levels later to keep the offline lessons.",
    emptyCatalogMessage = "No course data found. Make sure assets/learn-datas is bundled.",
    filterAll = "All",
    filterRemaining = "Remaining",
    filterCompleted = "Completed",
    legendTitle = "Legend",
    legendActive = "Active",
    legendCompleted = "Completed",
    legendRemaining = "Remaining",
    legendHint = "Long press any chip to mark it as learned.",
    symbolEmptyMessage = "No characters match the current filter.",
    symbolShowAllLabel = "Show all characters",
    symbolCollapseLabel = "Collapse list",
    activeCourseTitleFormat = "Active course \u00B7 HSK %1\$d",
    activeCourseStatusFormat = "Character %1\$s \u00B7 %2\$s",
    activeResume = "Resume",
    activeSkip = "Skip",
    activeRestart = "Restart",
    activeExit = "Exit",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Level %1\$d",
    levelProgressFormat = "%1\$d/%2\$d \u00B7 remaining %3\$d",
    levelNextFormat = "Next \u00B7 %1\$s",
    levelCompletedLabel = "Completed",
    lockedSignInLabel = "Sign in",
    lockedUnlockLabel = "Unlock",
    lockedBrowseLabel = "Browse courses",
    lockedGreatJobLabel = "Great job!",
    iconStartDescriptionFormat = "Start HSK %1\$d",
)

private val defaultAccountStrings = AccountStrings(
    title = "Account & Purchases",
    signInCardTitle = "Sign-in status",
    signInDescriptionSignedIn = "Signed in. Purchases and unlocked levels remain linked to this device.",
    signInDescriptionSignedOut = "Guest mode keeps practice data offline. Sign in only when you are ready to unlock courses.",
    signInButtonSignedIn = "Sign out",
    signInButtonSignedOut = "Sign in & accept policy",
    courseCardTitle = "Course unlock",
    courseDescriptionSignedOut = "Preview HSK levels anytime. Sign in to complete the purchase checklist.",
    courseDescriptionUnlocked = "All premium levels are unlocked. Continue from the Courses tab.",
    courseDescriptionLocked = "One-time unlock stores a local license so lessons remain available offline.",
    courseButtonSignedOut = "Sign in required",
    courseButtonUnlocked = "Browse courses",
    courseButtonLocked = "Unlock all courses",
    supportTitle = "Support & compliance",
    supportDescription = "Help articles, privacy toggles, and the feedback form now live here so compliance checks happen before login or purchases.",
    supportFeedbackButton = "Send feedback",
    clearDataTitle = "Reset local data",
    clearDataDescription = "Remove practice history, course progress, purchases, and preferences stored on this device.",
    clearDataButton = "Clear local records",
    clearDataDialogTitle = "Erase local data?",
    clearDataDialogBody = "This removes practice history, streaks, unlocked levels, preferences, and dictionary searches from this device. This cannot be undone.",
    consentSignInTitle = "Before signing in",
    consentSignInBullets = listOf(
        "Sign-in is only needed to associate purchases. Practice data stays on-device.",
        "Continuing confirms you have reviewed the Privacy Policy.",
        "You can remain in guest mode at any time—premium lessons simply stay locked.",
    ),
    consentSignInConfirm = "Agree & sign in",
    consentUnlockTitle = "Unlock premium lessons",
    consentUnlockBullets = listOf(
        "Payment tokens are cached locally so all content works offline.",
        "Unlocking also records the purchase under your account tab for later restores.",
        "A quick privacy reminder will appear again during checkout for compliance.",
    ),
    consentUnlockConfirm = "Confirm unlock",
    consentCheckboxLabel = "I have reviewed the privacy policy.",
    cancelLabel = "Cancel",
    closeLabel = "Close",
)

private val defaultSupportStrings = SupportStrings(
    analyticsTitle = "Usage analytics",
    analyticsDescription = "Anonymous counters for upcoming features.",
    crashTitle = "Crash reports",
    crashDescription = "Share lightweight logs if rendering fails.",
    prefetchTitle = "Network prefetch",
    prefetchDescription = "Allow Wi-Fi downloads of future packs.",
    privacyCloseLabel = "Close",
    feedbackTitle = "Send feedback",
    feedbackThanksTitle = "Thanks!",
    feedbackSavedMessage = "We stored your note locally. The next release will bundle it with diagnostic exports so nothing gets lost.",
    feedbackTopicLabel = "Topic",
    feedbackTopicPlaceholder = "Feature request, bug...",
    feedbackMessageLabel = "Details",
    feedbackMessagePlaceholder = "Describe the idea or issue",
    feedbackContactLabel = "Contact (optional)",
    feedbackContactPlaceholder = "Email or handle",
    feedbackSendLabel = "Send",
    feedbackCloseLabel = "Close",
    feedbackShareLogLabel = "Share log",
    feedbackCancelLabel = "Cancel",
    feedbackLastSentFormat = "Last sent: %1\$s",
    feedbackLogEmpty = "Feedback log is empty.",
    feedbackLogShareError = "Unable to share log.",
    feedbackLogNoApps = "No apps available to share log.",
    feedbackEmailError = "Couldn't open email. Log saved locally—share from Account later.",
    feedbackEmailNoApp = "No email app installed. Log saved locally—share from Account later.",
)

private val defaultLibraryStrings = LibraryStrings(
    title = "Dictionary",
    description = "Check pinyin, radicals, and quick definitions entirely offline. Enter a single character and hop back to Practice whenever you want to trace.",
    inputLabel = "Chinese character",
    supportingText = "Tip: Input one character (HSK 1 stays unlocked).",
    quickTryLabel = "Try:",
    recentHeader = "Recent searches",
    recentClear = "Clear",
    recentOverflowLabel = "More...",
    recentOverflowDialogTitle = "Recent searches",
    recentOverflowClose = "Close",
    lookupLabel = "Lookup",
    lookupLoadingLabel = "Looking up...",
    clearResultLabel = "Clear result",
    helpTitle = "Tips",
    helpBody = "- Data comes from the bundled word.json so it works offline.\n- Unlock more lessons under Account to pair dictionary results with courses.\n- For writing details and privacy specifics see docs/help-guide.md in the project.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Strokes: %2\$s",
    traditionalLabelFormat = "Traditional: %1\$s",
    definitionFallback = "No definition available.",
    valueNotAvailable = "N/A",
    valueUnknown = "?",
    practiceButtonLabel = "Practice this character",
    quickSuggestions = listOf("永", "学", "好", "中", "发"),
    errorEmpty = "Enter one character to search.",
    errorNotFound = "Character not found in the offline dictionary.",
    errorRead = "Unable to read the dictionary. Try again.",
)

private val spanishLibraryStrings = LibraryStrings(
    title = "Diccionario",
    description = "Consulta pinyin, radicales y definiciones rápidas completamente sin conexión. Ingresa un solo carácter y vuelve a Práctica cuando quieras trazarlo.",
    inputLabel = "Carácter chino",
    supportingText = "Consejo: escribe un carácter (HSK 1 siempre está desbloqueado).",
    quickTryLabel = "Prueba:",
    recentHeader = "Búsquedas recientes",
    recentClear = "Limpiar",
    recentOverflowLabel = "Más...",
    recentOverflowDialogTitle = "Búsquedas recientes",
    recentOverflowClose = "Cerrar",
    lookupLabel = "Buscar",
    lookupLoadingLabel = "Buscando...",
    clearResultLabel = "Borrar resultado",
    helpTitle = "Consejos",
    helpBody = "- Los datos provienen del word.json incluido, así que funciona sin conexión.\n- Desbloquea lecciones adicionales en la pestaña Cuenta para combinar el diccionario con los cursos.\n- Para detalles de caligrafía y privacidad revisa docs/help-guide.md dentro del proyecto.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Trazos: %2\$s",
    traditionalLabelFormat = "Tradicional: %1\$s",
    definitionFallback = "Sin definición disponible.",
    valueNotAvailable = "N/D",
    valueUnknown = "?",
    practiceButtonLabel = "Practicar este carácter",
    quickSuggestions = listOf("永", "发", "学", "好", "汉"),
    errorEmpty = "Ingresa un carácter para buscar.",
    errorNotFound = "Carácter no encontrado en el diccionario sin conexión.",
    errorRead = "No se pudo leer el diccionario. Intenta de nuevo.",
)

private val japaneseLibraryStrings = LibraryStrings(
    title = "辞書",
    description = "ピンイン・部首・簡単な意味をすべてオフラインで確認できます。1文字だけ入力して、いつでも練習タブに戻りましょう。",
    inputLabel = "漢字",
    supportingText = "ヒント: 1文字のみ入力してください（HSK1は常に解放済み）。",
    quickTryLabel = "例:",
    recentHeader = "最近の検索",
    recentClear = "削除",
    recentOverflowLabel = "もっと見る",
    recentOverflowDialogTitle = "最近の検索",
    recentOverflowClose = "閉じる",
    lookupLabel = "検索",
    lookupLoadingLabel = "検索中...",
    clearResultLabel = "結果をクリア",
    helpTitle = "ヒント",
    helpBody = "- データは同梱の word.json から読み込むため完全オフラインで動作します。\n- アカウントタブでレッスンを解除すると辞書の結果とコースを連携できます。\n- 筆順やプライバシーの詳細は docs/help-guide.md を参照してください。",
    pinyinLabelFormat = "ピンイン：%1\$s",
    radicalsStrokesFormat = "部首：%1\$s    画数：%2\$s",
    traditionalLabelFormat = "繁体字：%1\$s",
    definitionFallback = "意味を取得できませんでした。",
    valueNotAvailable = "該当なし",
    valueUnknown = "?",
    practiceButtonLabel = "この漢字で練習",
    quickSuggestions = listOf("永", "学", "好", "新", "漢"),
    errorEmpty = "検索する漢字を1文字入力してください。",
    errorNotFound = "オフライン辞書で該当する漢字が見つかりません。",
    errorRead = "辞書を読み込めませんでした。もう一度お試しください。",
)


private val spanishCoursesStrings = CoursesStrings(
    title = "Cursos",
    description = "Previsualiza cada paquete HSK gratis. Desbloquea los niveles premium más adelante para conservar las lecciones sin conexión.",
    emptyCatalogMessage = "No se encontraron datos del curso. Comprueba que assets/learn-datas esté incluido en el APK.",
    filterAll = "Todos",
    filterRemaining = "Pendientes",
    filterCompleted = "Completados",
    legendTitle = "Leyenda",
    legendActive = "Activo",
    legendCompleted = "Completado",
    legendRemaining = "Pendiente",
    legendHint = "Mantén pulsado cualquier icono para marcarlo como aprendido.",
    symbolEmptyMessage = "Ningún carácter coincide con el filtro actual.",
    symbolShowAllLabel = "Mostrar todos los caracteres",
    symbolCollapseLabel = "Ocultar lista",
    activeCourseTitleFormat = "Curso activo · HSK %1\$d",
    activeCourseStatusFormat = "Carácter %1\$s · %2\$s",
    activeResume = "Reanudar",
    activeSkip = "Saltar",
    activeRestart = "Reiniciar",
    activeExit = "Salir",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Nivel %1\$d",
    levelProgressFormat = "%1\$d/%2\$d · faltan %3\$d",
    levelNextFormat = "Siguiente · %1\$s",
    levelCompletedLabel = "Completado",
    lockedSignInLabel = "Iniciar sesión",
    lockedUnlockLabel = "Desbloquear",
    lockedBrowseLabel = "Ver cursos",
    lockedGreatJobLabel = "¡Buen trabajo!",
    iconStartDescriptionFormat = "Iniciar HSK %1\$d",
)

private val spanishAccountStrings = AccountStrings(
    title = "Cuenta y compras",
    signInCardTitle = "Estado de sesión",
    signInDescriptionSignedIn = "Sesión iniciada. Las compras y niveles desbloqueados siguen ligados a este dispositivo.",
    signInDescriptionSignedOut = "El modo invitado mantiene los datos de práctica sin conexión. Inicia sesión solo cuando quieras desbloquear cursos.",
    signInButtonSignedIn = "Cerrar sesión",
    signInButtonSignedOut = "Iniciar sesión y aceptar política",
    courseCardTitle = "Desbloqueo de cursos",
    courseDescriptionSignedOut = "Consulta los niveles HSK cuando quieras. Inicia sesión para completar la compra.",
    courseDescriptionUnlocked = "Todos los niveles premium están desbloqueados. Continúa desde la pestaña Cursos.",
    courseDescriptionLocked = "Un desbloqueo único guarda una licencia local para que las lecciones sigan disponibles offline.",
    courseButtonSignedOut = "Se requiere sesión",
    courseButtonUnlocked = "Ver cursos",
    courseButtonLocked = "Desbloquear todos los cursos",
    supportTitle = "Soporte y cumplimiento",
    supportDescription = "La ayuda, la privacidad y el formulario de comentarios viven aquí para que las revisiones ocurran antes de iniciar sesión o comprar.",
    supportFeedbackButton = "Enviar comentarios",
    clearDataTitle = "Restablecer datos locales",
    clearDataDescription = "Elimina el historial de práctica, el progreso, las compras y las preferencias guardadas en este dispositivo.",
    clearDataButton = "Borrar registros locales",
    clearDataDialogTitle = "¿Borrar datos locales?",
    clearDataDialogBody = "Se eliminarán el historial, las rachas, los niveles desbloqueados, las preferencias y las búsquedas del diccionario de este dispositivo. Esta acción no se puede deshacer.",
    consentSignInTitle = "Antes de iniciar sesión",
    consentSignInBullets = listOf(
        "Solo necesitas iniciar sesión para asociar compras. Los datos de práctica permanecen en el dispositivo.",
        "Al continuar confirmas que revisaste la Política de Privacidad.",
        "Puedes seguir en modo invitado: las lecciones premium simplemente seguirán bloqueadas.",
    ),
    consentSignInConfirm = "Aceptar e iniciar sesión",
    consentUnlockTitle = "Desbloquear lecciones premium",
    consentUnlockBullets = listOf(
        "Los tokens de pago se guardan localmente para que todo funcione sin conexión.",
        "El desbloqueo también registra la compra en la pestaña Cuenta para restauraciones posteriores.",
        "Durante el pago volverá a mostrarse un recordatorio de privacidad por cumplimiento.",
    ),
    consentUnlockConfirm = "Confirmar desbloqueo",
    consentCheckboxLabel = "Ya revisé la política de privacidad.",
    cancelLabel = "Cancelar",
    closeLabel = "Cerrar",
)

private val spanishSupportStrings = SupportStrings(
    analyticsTitle = "Analítica de uso",
    analyticsDescription = "Contadores anónimos para funciones futuras.",
    crashTitle = "Informes de fallos",
    crashDescription = "Comparte registros ligeros si falla el renderizado.",
    prefetchTitle = "Prefetch de red",
    prefetchDescription = "Permite descargas por Wi‑Fi de paquetes futuros.",
    privacyCloseLabel = "Cerrar",
    feedbackTitle = "Enviar comentarios",
    feedbackThanksTitle = "¡Gracias!",
    feedbackSavedMessage = "Guardamos tu nota localmente. La próxima versión la adjuntará a los diagnósticos para que nada se pierda.",
    feedbackTopicLabel = "Tema",
    feedbackTopicPlaceholder = "Solicitud, error...",
    feedbackMessageLabel = "Detalles",
    feedbackMessagePlaceholder = "Describe la idea o el problema",
    feedbackContactLabel = "Contacto (opcional)",
    feedbackContactPlaceholder = "Correo o usuario",
    feedbackSendLabel = "Enviar",
    feedbackCloseLabel = "Cerrar",
    feedbackShareLogLabel = "Compartir registro",
    feedbackCancelLabel = "Cancelar",
    feedbackLastSentFormat = "Último envío: %1\$s",
    feedbackLogEmpty = "El registro está vacío.",
    feedbackLogShareError = "No se pudo compartir el registro.",
    feedbackLogNoApps = "No hay aplicaciones disponibles para compartir el registro.",
    feedbackEmailError = "No se pudo abrir el correo. El registro quedó guardado; compártelo luego desde Cuenta.",
    feedbackEmailNoApp = "No hay aplicaciones de correo instaladas. El registro quedó guardado; compártelo luego desde Cuenta.",
)




private val japaneseCoursesStrings = CoursesStrings(
    title = "コース",
    description = "すべてのHSKパックを無料でプレビューできます。オフラインで学びたいレベルだけ後から解除しましょう。",
    emptyCatalogMessage = "コースデータが見つかりません。assets/learn-data がバンドルされているか確認してください。",
    filterAll = "すべて",
    filterRemaining = "学習予定",
    filterCompleted = "完了",
    legendTitle = "凡例",
    legendActive = "学習中",
    legendCompleted = "完了",
    legendRemaining = "未学習",
    legendHint = "長押しで習得済みに切り替えられます。",
    symbolEmptyMessage = "現在のフィルターに一致する文字はありません。",
    symbolShowAllLabel = "すべての文字を表示",
    symbolCollapseLabel = "一覧を閉じる",
    activeCourseTitleFormat = "進行中のコース・HSK %1\$d",
    activeCourseStatusFormat = "文字 %1\$s ・ %2\$s",
    activeResume = "再開",
    activeSkip = "スキップ",
    activeRestart = "最初から",
    activeExit = "終了",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "レベル %1\$d",
    levelProgressFormat = "%1\$d/%2\$d ・ 残り %3\$d",
    levelNextFormat = "次 ・ %1\$s",
    levelCompletedLabel = "完了",
    lockedSignInLabel = "サインイン",
    lockedUnlockLabel = "解除",
    lockedBrowseLabel = "コースを見る",
    lockedGreatJobLabel = "お疲れさま！",
    iconStartDescriptionFormat = "HSK %1\$d を開始",
)

private val japaneseAccountStrings = AccountStrings(
    title = "\u30a2\u30ab\u30a6\u30f3\u30c8\u3068\u8cfc\u5165",
    signInCardTitle = "\u30b5\u30a4\u30f3\u30a4\u30f3\u30b9\u30c6\u30fc\u30bf\u30b9",
    signInDescriptionSignedIn = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u3044\u307e\u3059\u3002\u8cfc\u5165\u304a\u3088\u3073\u30ed\u30c3\u30af\u89e3\u9664\u3055\u308c\u305f\u30ec\u30d9\u30eb\u306f\u3001\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u306b\u30ea\u30f3\u30af\u3055\u308c\u305f\u307e\u307e\u306b\u306a\u308a\u307e\u3059\u3002",
    signInDescriptionSignedOut = "\u30b2\u30b9\u30c8 \u30e2\u30fc\u30c9\u3067\u306f\u3001\u7df4\u7fd2\u30c7\u30fc\u30bf\u3092\u30aa\u30d5\u30e9\u30a4\u30f3\u306b\u4fdd\u3061\u307e\u3059\u3002\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b\u6e96\u5099\u304c\u3067\u304d\u3066\u3044\u308b\u5834\u5408\u306b\u306e\u307f\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",
    signInButtonSignedIn = "\u30b5\u30a4\u30f3\u30a2\u30a6\u30c8",
    signInButtonSignedOut = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u30dd\u30ea\u30b7\u30fc\u306b\u540c\u610f\u3059\u308b",
    courseCardTitle = "\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u89e3\u9664",
    courseDescriptionSignedOut = "HSK \u30ec\u30d9\u30eb\u3092\u3044\u3064\u3067\u3082\u30d7\u30ec\u30d3\u30e5\u30fc\u3067\u304d\u307e\u3059\u3002\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u8cfc\u5165\u30c1\u30a7\u30c3\u30af\u30ea\u30b9\u30c8\u3092\u5b8c\u4e86\u3057\u307e\u3059\u3002",
    courseDescriptionUnlocked = "\u3059\u3079\u3066\u306e\u30d7\u30ec\u30df\u30a2\u30e0\u30ec\u30d9\u30eb\u304c\u30ed\u30c3\u30af\u89e3\u9664\u6e08\u307f\u3067\u3059\u3002\u30b3\u30fc\u30b9\u30bf\u30d6\u304b\u3089\u518d\u958b\u3057\u307e\u3057\u3087\u3046\u3002",
    courseDescriptionLocked = "\u30ef\u30f3\u30bf\u30a4\u30e0\u30ed\u30c3\u30af\u89e3\u9664\u3067\u306f\u30ed\u30fc\u30ab\u30eb\u30e9\u30a4\u30bb\u30f3\u30b9\u304c\u4fdd\u5b58\u3055\u308c\u308b\u305f\u3081\u3001\u30ec\u30c3\u30b9\u30f3\u306f\u30aa\u30d5\u30e9\u30a4\u30f3\u3067\u3082\u5229\u7528\u3067\u304d\u307e\u3059\u3002",
    courseButtonSignedOut = "\u30b5\u30a4\u30f3\u30a4\u30f3\u304c\u5fc5\u8981\u3067\u3059",
    courseButtonUnlocked = "\u30b3\u30fc\u30b9\u3092\u95b2\u89a7\u3059\u308b",
    courseButtonLocked = "\u3059\u3079\u3066\u306e\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b",
    supportTitle = "\u30b5\u30dd\u30fc\u30c8\u3068\u30b3\u30f3\u30d7\u30e9\u30a4\u30a2\u30f3\u30b9",
    supportDescription = "\u30d8\u30eb\u30d7\u8a18\u4e8b\u3001\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u5207\u308a\u66ff\u3048\u3001\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af \u30d5\u30a9\u30fc\u30e0\u304c\u3053\u3053\u306b\u8868\u793a\u3055\u308c\u308b\u3088\u3046\u306b\u306a\u308a\u3001\u30ed\u30b0\u30a4\u30f3\u307e\u305f\u306f\u8cfc\u5165\u524d\u306b\u30b3\u30f3\u30d7\u30e9\u30a4\u30a2\u30f3\u30b9 \u30c1\u30a7\u30c3\u30af\u304c\u884c\u308f\u308c\u307e\u3059\u3002",
    supportFeedbackButton = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af\u3092\u9001\u4fe1\u3059\u308b",
    clearDataTitle = "\u30ed\u30fc\u30ab\u30eb\u30c7\u30fc\u30bf\u3092\u30ea\u30bb\u30c3\u30c8\u3059\u308b",
    clearDataDescription = "\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u306b\u4fdd\u5b58\u3055\u308c\u3066\u3044\u308b\u7df4\u7fd2\u5c65\u6b74\u3001\u30b3\u30fc\u30b9\u306e\u9032\u884c\u72b6\u6cc1\u3001\u8cfc\u5165\u5185\u5bb9\u3001\u8a2d\u5b9a\u3092\u524a\u9664\u3057\u307e\u3059\u3002",
    clearDataButton = "\u30ed\u30fc\u30ab\u30eb\u8a18\u9332\u3092\u30af\u30ea\u30a2\u3059\u308b",
    clearDataDialogTitle = "\u30ed\u30fc\u30ab\u30eb\u30c7\u30fc\u30bf\u3092\u6d88\u53bb\u3057\u307e\u3059\u304b\uff1f",
    clearDataDialogBody = "\u3053\u308c\u306b\u3088\u308a\u3001\u7df4\u7fd2\u5c65\u6b74\u3001\u30b9\u30c8\u30ea\u30fc\u30af\u3001\u30ed\u30c3\u30af\u89e3\u9664\u3055\u308c\u305f\u30ec\u30d9\u30eb\u3001\u8a2d\u5b9a\u3001\u8f9e\u66f8\u691c\u7d22\u304c\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u304b\u3089\u524a\u9664\u3055\u308c\u307e\u3059\u3002\u3053\u308c\u3092\u5143\u306b\u623b\u3059\u3053\u3068\u306f\u3067\u304d\u307e\u305b\u3093\u3002",
    consentSignInTitle = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3059\u308b\u524d\u306b",
    consentSignInConfirm = "\u540c\u610f\u3057\u3066\u30b5\u30a4\u30f3\u30a4\u30f3\u3059\u308b",
    consentUnlockTitle = "\u30d7\u30ec\u30df\u30a2\u30e0\u30ec\u30c3\u30b9\u30f3\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b",
    consentUnlockConfirm = "\u30ed\u30c3\u30af\u89e3\u9664\u306e\u78ba\u8a8d",
    consentCheckboxLabel = "\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u30dd\u30ea\u30b7\u30fc\u3092\u78ba\u8a8d\u3057\u307e\u3057\u305f\u3002",
    cancelLabel = "\u30ad\u30e3\u30f3\u30bb\u30eb",
    closeLabel = "\u9589\u3058\u308b",
    consentSignInBullets = listOf(
        "\u30b5\u30a4\u30f3\u30a4\u30f3\u306f\u3001\u8cfc\u5165\u3092\u95a2\u9023\u4ed8\u3051\u308b\u5834\u5408\u306b\u306e\u307f\u5fc5\u8981\u3067\u3059\u3002\u7df4\u7fd2\u30c7\u30fc\u30bf\u306f\u30c7\u30d0\u30a4\u30b9\u4e0a\u306b\u6b8b\u308a\u307e\u3059\u3002",
        "\u7d9a\u884c\u3059\u308b\u3068\u3001\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc \u30dd\u30ea\u30b7\u30fc\u3092\u78ba\u8a8d\u3057\u305f\u3053\u3068\u3092\u78ba\u8a8d\u3057\u307e\u3059\u3002",
        "\u3044\u3064\u3067\u3082\u30b2\u30b9\u30c8 \u30e2\u30fc\u30c9\u306e\u307e\u307e\u306b\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002\u30d7\u30ec\u30df\u30a2\u30e0 \u30ec\u30c3\u30b9\u30f3\u306f\u30ed\u30c3\u30af\u3055\u308c\u305f\u307e\u307e\u306b\u306a\u308a\u307e\u3059\u3002",
    ),
    consentUnlockBullets = listOf(
        "\u652f\u6255\u3044\u30c8\u30fc\u30af\u30f3\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u30ad\u30e3\u30c3\u30b7\u30e5\u3055\u308c\u308b\u305f\u3081\u3001\u3059\u3079\u3066\u306e\u30b3\u30f3\u30c6\u30f3\u30c4\u306f\u30aa\u30d5\u30e9\u30a4\u30f3\u3067\u52d5\u4f5c\u3057\u307e\u3059\u3002",
        "\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b\u3068\u3001\u5f8c\u3067\u5fa9\u5143\u3067\u304d\u308b\u3088\u3046\u306b\u3001\u30a2\u30ab\u30a6\u30f3\u30c8 \u30bf\u30d6\u306b\u8cfc\u5165\u5185\u5bb9\u3082\u8a18\u9332\u3055\u308c\u307e\u3059\u3002",
        "\u30b3\u30f3\u30d7\u30e9\u30a4\u30a2\u30f3\u30b9\u3092\u78ba\u4fdd\u3059\u308b\u305f\u3081\u306b\u3001\u30c1\u30a7\u30c3\u30af\u30a2\u30a6\u30c8\u4e2d\u306b\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u306b\u95a2\u3059\u308b\u7c21\u5358\u306a\u30ea\u30de\u30a4\u30f3\u30c0\u30fc\u304c\u518d\u5ea6\u8868\u793a\u3055\u308c\u307e\u3059\u3002",
    ),
)


private val japaneseSupportStrings = SupportStrings(
    analyticsTitle = "\u4f7f\u7528\u72b6\u6cc1\u5206\u6790",
    analyticsDescription = "\u4eca\u5f8c\u306e\u6a5f\u80fd\u306e\u533f\u540d\u30ab\u30a6\u30f3\u30bf\u30fc\u3002",
    crashTitle = "\u30af\u30e9\u30c3\u30b7\u30e5\u30ec\u30dd\u30fc\u30c8",
    crashDescription = "\u30ec\u30f3\u30c0\u30ea\u30f3\u30b0\u304c\u5931\u6557\u3057\u305f\u5834\u5408\u306f\u8efd\u91cf\u30ed\u30b0\u3092\u5171\u6709\u3057\u307e\u3059\u3002",
    prefetchTitle = "\u30cd\u30c3\u30c8\u30ef\u30fc\u30af\u30d7\u30ea\u30d5\u30a7\u30c3\u30c1",
    prefetchDescription = "\u5c06\u6765\u306e\u30d1\u30c3\u30af\u306e Wi-Fi \u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3092\u8a31\u53ef\u3057\u307e\u3059\u3002",
    privacyCloseLabel = "\u9589\u3058\u308b",
    feedbackTitle = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af\u3092\u9001\u4fe1\u3059\u308b",
    feedbackThanksTitle = "\u3042\u308a\u304c\u3068\u3046\uff01",
    feedbackSavedMessage = "\u3042\u306a\u305f\u306e\u30e1\u30e2\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3057\u305f\u3002\u6b21\u306e\u30ea\u30ea\u30fc\u30b9\u3067\u306f\u8a3a\u65ad\u30a8\u30af\u30b9\u30dd\u30fc\u30c8\u304c\u30d0\u30f3\u30c9\u30eb\u3055\u308c\u308b\u305f\u3081\u3001\u4f55\u3082\u5931\u308f\u308c\u308b\u3053\u3068\u306f\u3042\u308a\u307e\u305b\u3093\u3002",
    feedbackTopicLabel = "\u30c8\u30d4\u30c3\u30af",
    feedbackTopicPlaceholder = "\u6a5f\u80fd\u30ea\u30af\u30a8\u30b9\u30c8\u3001\u30d0\u30b0...",
    feedbackMessageLabel = "\u8a73\u7d30",
    feedbackMessagePlaceholder = "\u30a2\u30a4\u30c7\u30a2\u3084\u554f\u984c\u306b\u3064\u3044\u3066\u8aac\u660e\u3059\u308b",
    feedbackContactLabel = "\u9023\u7d61\u5148 (\u30aa\u30d7\u30b7\u30e7\u30f3)",
    feedbackContactPlaceholder = "\u30e1\u30fc\u30eb\u307e\u305f\u306f\u30cf\u30f3\u30c9\u30eb",
    feedbackSendLabel = "\u9001\u4fe1",
    feedbackCloseLabel = "\u9589\u3058\u308b",
    feedbackShareLogLabel = "\u30ed\u30b0\u3092\u5171\u6709\u3059\u308b",
    feedbackCancelLabel = "\u30ad\u30e3\u30f3\u30bb\u30eb",
    feedbackLastSentFormat = "\u6700\u5f8c\u306b\u9001\u4fe1\u3057\u307e\u3057\u305f: %1\$s",
    feedbackLogEmpty = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af \u30ed\u30b0\u304c\u7a7a\u3067\u3059\u3002",
    feedbackLogShareError = "\u30ed\u30b0\u3092\u5171\u6709\u3067\u304d\u307e\u305b\u3093\u3002",
    feedbackLogNoApps = "\u30ed\u30b0\u3092\u5171\u6709\u3067\u304d\u308b\u30a2\u30d7\u30ea\u304c\u3042\u308a\u307e\u305b\u3093\u3002",
    feedbackEmailError = "\u30e1\u30fc\u30eb\u3092\u958b\u3051\u307e\u305b\u3093\u3067\u3057\u305f\u3002\u30ed\u30b0\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3059\u3002\u5f8c\u3067\u30a2\u30ab\u30a6\u30f3\u30c8\u304b\u3089\u5171\u6709\u3057\u307e\u3059\u3002",
    feedbackEmailNoApp = "\u30e1\u30fc\u30eb\u30a2\u30d7\u30ea\u304c\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002\u30ed\u30b0\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3059\u3002\u5f8c\u3067\u30a2\u30ab\u30a6\u30f3\u30c8\u304b\u3089\u5171\u6709\u3057\u307e\u3059\u3002",
)
private fun localizedStringsEn(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    searchLabel = "Hanzi",
    loadButton = "Load character",
    clearButton = "Clear input",
    loadingLabel = "Loading...",
    coursesDialogTitle = "HSK Courses",
    coursePlanHeading = "Pick a course to continue",
    courseIntroTitle = "How courses work",
    courseIntroBullets = listOf(
        "Choose an HSK level to begin or jump back in.",
        "Tap a character to practice; long-press to mark it mastered.",
        "The badge above the board mirrors your current course progress.",
    ),
    courseEmptyTitle = "No active course yet",
    courseEmptyDescription = "Select an HSK level below to start a guided session.",
    courseNoDataMessage = "No course data found. Please double-check the resource pack.",
    expandCharactersLabel = "Show all",
    collapseCharactersLabel = "Hide",
    legendTitle = "Legend & gestures",
    legendGesture = "Tap any character to practice; long-press to mark it as learned.",
    legendActiveLabel = "Active",
    legendCompletedLabel = "Completed",
    legendRemainingLabel = "Remaining",
    courseLegendHint = "Badge controls let you resume, skip, restart, or exit without covering the board.",
    courseLevelCompleteLabel = "Course complete",
    courseLevelStartFormat = "Start with %s",
    courseLevelNextFormat = "Next • %s",
    levelLabelFormat = "Level %d",
    courseLevelProgressFormat = "%1\$d/%2\$d mastered · %3\$d remaining",
    loadLevelFormat = "Load HSK %d",
    filterAllLabel = "All",
    filterRemainingLabel = "Remaining",
    filterCompletedLabel = "Completed",
    helpTitle = "Help & onboarding",
    helpSections = listOf(
        HelpSectionText(
            title = "Quick start",
            description = "Complete a full demo → practice cycle in seconds.",
            bullets = listOf(
                "Enter any hanzi and tap the cloud icon to load offline data.",
                "Use Play or Loop to watch the demo; enable the calligraphy template for tracing.",
                "Press the pencil on the board to begin; the hint icon highlights the next stroke.",
            ),
        ),
        HelpSectionText(
            title = "Courses & progress",
            description = "HSK courses live under the avatar menu, and the badge reflects your status.",
            bullets = listOf(
                "Resume/Skip/Restart/Exit icons stay inside the badge so controls never hide the board.",
                "Chevron arrows jump between characters; finishing one updates the summary instantly.",
            ),
        ),
        HelpSectionText(
            title = "Cards & pronunciation",
            description = "The Kaishu card shows dictionary data plus TextToSpeech playback.",
            bullets = listOf(
                "Tap the card to open the full definition and scroll through the explanation.",
                "The speaker button plays Mandarin audio entirely offline.",
            ),
        ),
        HelpSectionText(
            title = "Grids & templates",
            description = "Board settings support Mi-grid, nine-grid, or no guides at all.",
            bullets = listOf(
                "Switch between outline and freestyle modes; stroke colors persist between sessions.",
                "Scroll outside the canvas to move the page so the writing surface stays fixed.",
            ),
        ),
        HelpSectionText(
            title = "Support & feedback",
            description = "Need help? Reach out anytime.",
            bullets = listOf(
                "Email: qq260316514@gmail.com",
                "Profile → Feedback lets you attach logs before sending.",
            ),
        ),
    ),
    helpConfirm = "Got it",
    privacyTitle = "Privacy preferences",
    privacyIntro = "Everything runs offline by default. Enable diagnostics only if you agree.",
    dataSafetyHeading = "Data safety snapshot",
    privacySummaryRows = listOf(
        SummaryRowText(
            title = "Data storage",
            detail = "Practice history, course progress, and board settings stay in local DataStore only.",
        ),
        SummaryRowText(
            title = "Offline assets",
            detail = "Stroke JSON and course packs ship inside the APK; optional prefetch won't run unless enabled.",
        ),
        SummaryRowText(
            title = "Logs & feedback",
            detail = "Text logs are attached only when you explicitly send feedback.",
        ),
    ),
    contactSupportLabel = "Contact: %s",
    emailSupportButton = "Email support",
    viewPolicyButton = "View full policy",
    fullPolicyTitle = "Privacy policy",
    fullPolicySections = listOf(
        PolicySectionText(
            title = "1. Data we collect",
            bullets = listOf(
                "Character resources packaged in the APK for rendering stroke order.",
                "Up to 40 local practice records for resuming sessions.",
                "Board preferences such as grids, colors, and template visibility.",
                "Optional plain-text logs attached only when you send feedback.",
            ),
        ),
        PolicySectionText(
            title = "2. How data is used",
            bullets = listOf(
                "Resume course progress and compute streaks locally.",
                "Display dictionary cards and HSK summaries without internet access.",
                "Investigate bugs only if you share logs manually.",
            ),
        ),
        PolicySectionText(
            title = "3. Permissions",
            bullets = listOf(
                "INTERNET (optional) reserved for future downloads or external dictionary links.",
                "No access to location, contacts, or advertising IDs.",
            ),
        ),
        PolicySectionText(
            title = "4. Your controls",
            bullets = listOf(
                "Clear the app's storage in Android settings to reset all data.",
                "Use the Privacy dialog to toggle analytics, crash logs, or network prefetch.",
                "Review and edit feedback logs before sending.",
            ),
        ),
        PolicySectionText(
            title = "5. Contact",
            bullets = listOf(
                "Email: qq260316514@gmail.com",
                "GitHub: https://github.com/chanind/hanzi-writer-data (resource reference).",
            ),
        ),
    ),
                    progress = ProgressStrings(
        title = "Progress",
        description = "Check streaks, HSK completion, and the latest practice records. Everything refreshes automatically whenever you trace a new character.",
        jumpBackLabel = "Back to Practice",
        learnedLabel = "Learned",
        streakLabel = "Streak",
        lastSessionLabel = "Last session",
        streakDaySingularFormat = "%1\$d day",
        streakDayPluralFormat = "%1\$d days",
        streakStartLabel = "Start",
        lastSessionNeverLabel = "Never",
        weeklyChartTitle = "Last 7 days",
        levelsTitle = "Levels",
        levelsEmpty = "Start a practice session to see each HSK level tracked here.",
        levelLabelFormat = "HSK %1\$d",
        levelMasteredFormat = "%1\$d/%2\$d mastered",
        levelJumpDescription = "Jump to the next character",
        levelBrowseCourses = "Browse courses",
        historyTitle = "Recent practice",
        historyEmpty = "Trace any character and it shows up here for a quick review.",
        historyStrokesFormat = "%1\$d strokes \u00b7 %2\$s",
        historyMistakesPerfect = "Perfect run",
        historyMistakesFormat = "%1\$d mistakes",
        historyLoadCharacterFormat = "Load %1\$s",
        relativeJustNow = "just now",
        relativeMinutesFormat = "%1\$d min ago",
        relativeHoursFormat = "%1\$d hr ago",
        relativeDaysFormat = "%1\$d d ago",
    ),
    library = defaultLibraryStrings,
    courses = defaultCoursesStrings,
    account = defaultAccountStrings,
    support = defaultSupportStrings,
    boardControls = defaultPracticeBoardStrings,
)

private fun localizedStringsJa(locale: Locale): LocalizedStrings {
    val base = localizedStringsEn(locale)
    return base.copy(
        locale = locale,
        appTitle = "\u6f22\u5b57\u7b46\u9806",
        searchLabel = "\u6f22\u5b57",
        loadButton = "\u6587\u5b57\u3092\u8aad\u307f\u8fbc\u3080",
        clearButton = "\u30af\u30ea\u30a2",
        loadingLabel = "\u8aad\u307f\u8fbc\u307f\u4e2d...",
        coursesDialogTitle = "HSK\u30b3\u30fc\u30b9",
        coursePlanHeading = "\u7d9a\u3051\u308b\u30b3\u30fc\u30b9\u3092\u9078\u3076",
        courseIntroTitle = "\u30b3\u30fc\u30b9\u306e\u4ed5\u7d44\u307f",
        courseIntroBullets = listOf(
            "HSK\u30ec\u30d9\u30eb\u3092\u9078\u3093\u3067\u958b\u59cb\u3057\u3001\u4e2d\u65ad\u3057\u305f\u5834\u6240\u304b\u3089\u518d\u958b\u3067\u304d\u307e\u3059",
            "\u6587\u5b57\u3092\u30bf\u30c3\u30d7\u3059\u308b\u3068\u7df4\u7fd2\u3001\u9577\u62bc\u3057\u3067\u7fd2\u5f97\u6e08\u307f\u306b\u3067\u304d\u307e\u3059",
            "\u30dc\u30fc\u30c9\u4e0a\u306e\u30d0\u30c3\u30b8\u304c\u73fe\u5728\u306e\u9032\u6357\u3092\u5e38\u306b\u8868\u793a\u3057\u307e\u3059",
        ),
        courseEmptyTitle = "\u307e\u3060\u30b3\u30fc\u30b9\u304c\u3042\u308a\u307e\u305b\u3093",
        courseEmptyDescription = "\u4e0b\u306eHSK\u30ec\u30d9\u30eb\u3092\u9078\u3093\u3067\u30ac\u30a4\u30c9\u4ed8\u304d\u30bb\u30c3\u30b7\u30e7\u30f3\u3092\u59cb\u3081\u307e\u3057\u3087\u3046",
        courseNoDataMessage = "\u30b3\u30fc\u30b9\u30c7\u30fc\u30bf\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\u30ea\u30bd\u30fc\u30b9\u30d1\u30c3\u30af\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044",
        expandCharactersLabel = "\u3059\u3079\u3066\u8868\u793a",
        collapseCharactersLabel = "\u96a0\u3059",
        legendTitle = "\u51e1\u4f8b\u3068\u64cd\u4f5c",
        legendGesture = "\u6587\u5b57\u3092\u30bf\u30c3\u30d7\u3057\u3066\u7df4\u7fd2\u3001\u9577\u62bc\u3057\u3067\u7fd2\u5f97\u6e08\u307f\u306b\u3057\u307e\u3059",
        courseLegendHint = "\u30d0\u30c3\u30b8\u304b\u3089\u518d\u958b\u30fb\u30b9\u30ad\u30c3\u30d7\u30fb\u3084\u308a\u76f4\u3057\u30fb\u7d42\u4e86\u304c\u3067\u304d\u307e\u3059",
        helpTitle = "\u30d8\u30eb\u30d7",
        helpConfirm = "\u4e86\u89e3",
        privacyTitle = "\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u8a2d\u5b9a",
        privacyIntro = "\u3059\u3079\u3066\u306e\u6a5f\u80fd\u306f\u30c7\u30d5\u30a9\u30eb\u30c8\u3067\u30aa\u30d5\u30e9\u30a4\u30f3\u3067\u3059\u3002\u8a3a\u65ad\u30c7\u30fc\u30bf\u304c\u5fc5\u8981\u306a\u5834\u5408\u306e\u307f\u6709\u52b9\u306b\u3057\u3066\u304f\u3060\u3055\u3044",
        contactSupportLabel = "\u304a\u554f\u3044\u5408\u308f\u305b: %s",
        emailSupportButton = "\u30e1\u30fc\u30eb\u3067\u9023\u7d61",
        viewPolicyButton = "\u30dd\u30ea\u30b7\u30fc\u5168\u6587",
        courses = japaneseCoursesStrings,
        account = japaneseAccountStrings,
        support = japaneseSupportStrings,
        progress = japaneseProgressStrings,
        library = japaneseLibraryStrings,
        boardControls = japanesePracticeBoardStrings,
    )
}

private fun localizedStringsEs(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    searchLabel = "Hanzi",
    loadButton = "Cargar carácter",
    clearButton = "Borrar",
    loadingLabel = "Cargando...",
    coursesDialogTitle = "Cursos HSK",
    coursePlanHeading = "Elige un curso para continuar",
    courseIntroTitle = "Cómo funcionan los cursos",
    courseIntroBullets = listOf(
        "Selecciona un nivel HSK para comenzar o retomar el estudio.",
        "Toca un carácter para practicar; mantén pulsado para marcarlo como dominado.",
        "La insignia sobre el tablero refleja tu progreso actual.",
    ),
    courseEmptyTitle = "Sin curso activo",
    courseEmptyDescription = "Selecciona un nivel HSK para iniciar una sesión guiada.",
    courseNoDataMessage = "No se encontraron datos del curso. Comprueba el paquete de recursos.",
    expandCharactersLabel = "Mostrar todo",
    collapseCharactersLabel = "Ocultar",
    legendTitle = "Leyenda y gestos",
    legendGesture = "Toca un carácter para practicar; mantén pulsado para marcarlo como aprendido.",
    legendActiveLabel = "Activo",
    legendCompletedLabel = "Completado",
    legendRemainingLabel = "Pendiente",
    courseLegendHint = "Usa los controles de la insignia para reanudar, saltar, reiniciar o salir sin cubrir el tablero.",
    courseLevelCompleteLabel = "Curso completo",
    courseLevelStartFormat = "Empieza con %s",
    courseLevelNextFormat = "Siguiente • %s",
    levelLabelFormat = "Nivel %d",
    courseLevelProgressFormat = "%1\$d/%2\$d dominados · faltan %3\$d",
    loadLevelFormat = "Abrir HSK %d",
    filterAllLabel = "Todos",
    filterRemainingLabel = "Pendientes",
    filterCompletedLabel = "Completados",
    helpTitle = "Ayuda e introducción",
    helpSections = listOf(
        HelpSectionText(
            title = "Inicio rápido",
            description = "Completa un ciclo de demostración → práctica en segundos.",
            bullets = listOf(
                "Escribe cualquier hanzi y toca el ícono de nube para cargar los datos sin conexión.",
                "Usa Reproducir o Bucle para ver la demostración; activa la plantilla caligráfica para calcar.",
                "Pulsa el lápiz en el tablero para empezar; el ícono de pista resalta el siguiente trazo.",
            ),
        ),
        HelpSectionText(
            title = "Cursos y progreso",
            description = "Los cursos HSK viven bajo el avatar y la insignia muestra tu estado.",
            bullets = listOf(
                "Los botones Reanudar/Saltar/Reiniciar/Salir permanecen en la insignia para no tapar el tablero.",
                "Las flechas cambian de carácter; al terminar uno se actualiza el resumen al instante.",
            ),
        ),
        HelpSectionText(
            title = "Tarjetas y pronunciación",
            description = "La tarjeta en caligrafía muestra el diccionario y la voz sintética.",
            bullets = listOf(
                "Toca la tarjeta para abrir la definición completa y desplazarte por la explicación.",
                "El botón de altavoz reproduce audio en mandarín sin conexión.",
            ),
        ),
        HelpSectionText(
            title = "Cuadrículas y plantillas",
            description = "El tablero admite cuadrícula mi, cuadrícula de nueve o sin guías.",
            bullets = listOf(
                "Cambia entre modo con plantilla o libre; los colores de los trazos se conservan.",
                "Desplázate fuera del lienzo para mover la página y mantener fija la zona de escritura.",
            ),
        ),
        HelpSectionText(
            title = "Soporte y comentarios",
            description = "¿Necesitas ayuda? Escríbenos.",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
                "Perfil → Feedback permite adjuntar registros antes de enviarlos.",
            ),
        ),
    ),
    helpConfirm = "Entendido",
    privacyTitle = "Preferencias de privacidad",
    privacyIntro = "La app funciona sin conexión por defecto. Activa diagnósticos solo si estás de acuerdo.",
    dataSafetyHeading = "Resumen de seguridad de datos",
    privacySummaryRows = listOf(
        SummaryRowText(
            title = "Almacenamiento",
            detail = "Historial de práctica, progreso y ajustes del tablero permanecen solo en DataStore local.",
        ),
        SummaryRowText(
            title = "Recursos sin conexión",
            detail = "Los paquetes de trazos y cursos vienen en el APK; el prefetch opcional solo funciona si lo habilitas.",
        ),
        SummaryRowText(
            title = "Registros y comentarios",
            detail = "Los registros de texto se adjuntan únicamente cuando envías comentarios.",
        ),
    ),
    contactSupportLabel = "Contacto: %s",
    emailSupportButton = "Enviar correo",
    viewPolicyButton = "Ver política completa",
    fullPolicyTitle = "Política de privacidad",
    fullPolicySections = listOf(
        PolicySectionText(
            title = "1. Datos que recopilamos",
            bullets = listOf(
                "Recursos de caracteres incluidos en el APK para mostrar el orden de los trazos.",
                "Hasta 40 registros locales para reanudar sesiones.",
                "Preferencias del tablero como cuadrículas, colores y plantillas.",
                "Registros de texto opcionales solo cuando envías comentarios.",
            ),
        ),
        PolicySectionText(
            title = "2. Uso de los datos",
            bullets = listOf(
                "Reanudar el progreso del curso y calcular rachas localmente.",
                "Mostrar tarjetas de diccionario y resúmenes HSK sin internet.",
                "Investigar errores solo si compartes registros manualmente.",
            ),
        ),
        PolicySectionText(
            title = "3. Permisos",
            bullets = listOf(
                "INTERNET (opcional) reservado para futuras descargas o enlaces externos.",
                "Sin acceso a ubicación, contactos ni identificadores publicitarios.",
            ),
        ),
        PolicySectionText(
            title = "4. Tus controles",
            bullets = listOf(
                "Borra los datos de la app en Ajustes de Android para reiniciar todo.",
                "Usa el diálogo de Privacidad para activar o desactivar analíticas, registros o prefetch.",
                "Revisa y edita los registros antes de enviarlos.",
            ),
        ),
        PolicySectionText(
            title = "5. Contacto",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
                "GitHub: https://github.com/chanind/hanzi-writer-data (referencia de recursos).",
            ),
        ),
    ),
    progress = ProgressStrings(
        title = "Progreso",
        description = "Consulta rachas, finalización de HSK y el historial de práctica más reciente. Todo se actualiza automáticamente al trazar nuevos caracteres.",
        jumpBackLabel = "Volver a Práctica",
        learnedLabel = "Aprendidos",
        streakLabel = "Racha",
        lastSessionLabel = "Última sesión",
        streakDaySingularFormat = "%1\$d día",
        streakDayPluralFormat = "%1\$d días",
        streakStartLabel = "Comienza",
        lastSessionNeverLabel = "Nunca",
        weeklyChartTitle = "Últimos 7 días",
        levelsTitle = "Niveles",
        levelsEmpty = "Inicia una sesión de práctica para ver los niveles HSK aquí.",
        levelLabelFormat = "HSK %1\$d",
        levelMasteredFormat = "%1\$d/%2\$d dominados",
        levelJumpDescription = "Ir al siguiente carácter",
        levelBrowseCourses = "Ver cursos",
        historyTitle = "Práctica reciente",
        historyEmpty = "Cuando traces un carácter aparecerá aquí para repasarlo rápidamente.",
        historyStrokesFormat = "%1\$d trazos · %2\$s",
        historyMistakesPerfect = "Sin errores",
        historyMistakesFormat = "%1\$d errores",
        historyLoadCharacterFormat = "Cargar %1\$s",
        relativeJustNow = "justo ahora",
        relativeMinutesFormat = "hace %1\$d min",
        relativeHoursFormat = "hace %1\$d h",
        relativeDaysFormat = "hace %1\$d d",
    ),
    library = spanishLibraryStrings,
    courses = spanishCoursesStrings,
    account = spanishAccountStrings,
    support = spanishSupportStrings,
    boardControls = spanishPracticeBoardStrings,
)

