package com.yourstudio.hskstroke.bishun.ui.character

import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.platform.LocalContext
import java.util.Locale

data class HelpSectionText(
    val title: String,
    val description: String,
    val bullets: List<String>,
)

data class PolicySectionText(
    val title: String,
    val bullets: List<String>,
)

data class SummaryRowText(val title: String, val detail: String)

data class CoursesStrings(
    val title: String,
    val description: String,
    val emptyCatalogMessage: String,
    val filterAll: String,
    val filterRemaining: String,
    val filterCompleted: String,
    val legendTitle: String,
    val legendActive: String,
    val legendCompleted: String,
    val legendRemaining: String,
    val legendHint: String,
    val symbolEmptyMessage: String,
    val symbolShowAllLabel: String,
    val symbolCollapseLabel: String,
    val activeCourseTitleFormat: String,
    val activeCourseStatusFormat: String,
    val activeResume: String,
    val activeSkip: String,
    val activeRestart: String,
    val activeExit: String,
    val levelHeaderFormat: String,
    val levelChipFormat: String,
    val levelProgressFormat: String,
    val levelNextFormat: String,
    val levelCompletedLabel: String,
    val lockedSignInLabel: String,
    val lockedUnlockLabel: String,
    val lockedBrowseLabel: String,
    val lockedGreatJobLabel: String,
    val iconStartDescriptionFormat: String,
    val toastSkippedLabel: String,
    val toastMarkedLearnedFormat: String,
    val toastCourseCompleteFormat: String,
    val toastAutoAdvancedFormat: String,
    val toastNextUpFormat: String,
)

data class AccountStrings(
    val title: String,
    val signInCardTitle: String,
    val signInDescriptionSignedIn: String,
    val signInDescriptionSignedOut: String,
    val signInButtonSignedIn: String,
    val signInButtonSignedOut: String,
    val courseCardTitle: String,
    val courseDescriptionSignedOut: String,
    val courseDescriptionUnlocked: String,
    val courseDescriptionLocked: String,
    val courseButtonSignedOut: String,
    val courseButtonUnlocked: String,
    val courseButtonLocked: String,
    val supportTitle: String,
    val supportDescription: String,
    val supportFeedbackButton: String,
    val clearDataTitle: String,
    val clearDataDescription: String,
    val clearDataButton: String,
    val clearDataDialogTitle: String,
    val clearDataDialogBody: String,
    val consentSignInTitle: String,
    val consentSignInBullets: List<String>,
    val consentSignInConfirm: String,
    val consentUnlockTitle: String,
    val consentUnlockBullets: List<String>,
    val consentUnlockConfirm: String,
    val consentCheckboxLabel: String,
    val cancelLabel: String,
    val closeLabel: String,
)

data class SupportStrings(
    val analyticsTitle: String,
    val analyticsDescription: String,
    val crashTitle: String,
    val crashDescription: String,
    val prefetchTitle: String,
    val prefetchDescription: String,
    val privacyCloseLabel: String,
    val feedbackTitle: String,
    val feedbackThanksTitle: String,
    val feedbackSavedMessage: String,
    val feedbackTopicLabel: String,
    val feedbackTopicPlaceholder: String,
    val feedbackMessageLabel: String,
    val feedbackMessagePlaceholder: String,
    val feedbackContactLabel: String,
    val feedbackContactPlaceholder: String,
    val feedbackSendLabel: String,
    val feedbackCloseLabel: String,
    val feedbackShareLogLabel: String,
    val feedbackCancelLabel: String,
    val feedbackLastSentFormat: String,
    val feedbackLogEmpty: String,
    val feedbackLogShareError: String,
    val feedbackLogNoApps: String,
    val feedbackEmailError: String,
    val feedbackEmailNoApp: String,
)

data class NavigationStrings(
    val homeLabel: String,
    val learnLabel: String,
    val libraryLabel: String,
    val accountLabel: String,
)

data class OnboardingPageText(
    val title: String,
    val body: String,
)

data class OnboardingStrings(
    val appTitle: String,
    val skipLabel: String,
    val backLabel: String,
    val nextLabel: String,
    val startLabel: String,
    val pages: List<OnboardingPageText>,
)

data class PracticeBoardStrings(
    val startLabel: String,
    val hintLabel: String,
    val previousLabel: String,
    val nextLabel: String,
    val settingsLabel: String,
    val pronunciationLabel: String,
    val dictionaryLabel: String,
    val hskLabel: String,
    val statusReadyLabel: String,
    val statusStrokeProgressFormat: String,
    val statusStartFromStrokeFormat: String,
    val statusTryAgainFormat: String,
    val statusGreatContinueLabel: String,
    val statusBackwardsAcceptedLabel: String,
    val statusPracticeCompleteLabel: String,
)

private val defaultPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Start practice",
    hintLabel = "Hint",
    previousLabel = "Previous character",
    nextLabel = "Next character",
    settingsLabel = "Canvas settings",
    pronunciationLabel = "Play pronunciation",
    dictionaryLabel = "Show dictionary entry",
    hskLabel = "HSK info",
    statusReadyLabel = "Ready to start",
    statusStrokeProgressFormat = "Stroke %1\$d/%2\$d",
    statusStartFromStrokeFormat = "Start from stroke %1\$d",
    statusTryAgainFormat = "Try again (mistakes %1\$d)",
    statusGreatContinueLabel = "Great! Continue to the next stroke",
    statusBackwardsAcceptedLabel = "Stroke direction reversed but accepted",
    statusPracticeCompleteLabel = "Practice complete",
)

private val spanishPracticeBoardStrings = PracticeBoardStrings(
    startLabel = "Iniciar pr\u00e1ctica",
    hintLabel = "Pista",
    previousLabel = "Car\u00e1cter anterior",
    nextLabel = "Siguiente car\u00e1cter",
    settingsLabel = "Ajustes del tablero",
    pronunciationLabel = "Reproducir pronunciaci\u00f3n",
    dictionaryLabel = "Mostrar definici\u00f3n",
    hskLabel = "Informaci\u00f3n HSK",
    statusReadyLabel = "Listo para empezar",
    statusStrokeProgressFormat = "Trazo %1\$d/%2\$d",
    statusStartFromStrokeFormat = "Empieza desde el trazo %1\$d",
    statusTryAgainFormat = "Intenta de nuevo (errores %1\$d)",
    statusGreatContinueLabel = "\u00a1Bien! Contin\u00faa con el siguiente trazo",
    statusBackwardsAcceptedLabel = "Direcci\u00f3n del trazo invertida, pero aceptada",
    statusPracticeCompleteLabel = "Pr\u00e1ctica completada",
)

private val japanesePracticeBoardStrings = PracticeBoardStrings(
    startLabel = "\u7df4\u7fd2\u3092\u958b\u59cb",
    hintLabel = "\u30d2\u30f3\u30c8",
    previousLabel = "\u524d\u306e\u6587\u5b57",
    nextLabel = "\u6b21\u306e\u6587\u5b57",
    settingsLabel = "\u30dc\u30fc\u30c9\u8a2d\u5b9a",
    pronunciationLabel = "\u767a\u97f3\u3092\u518d\u751f",
    dictionaryLabel = "\u8f9e\u66f8\u3092\u898b\u308b",
    hskLabel = "HSK\u60c5\u5831",
    statusReadyLabel = "\u6e96\u5099\u5b8c\u4e86",
    statusStrokeProgressFormat = "\u753b %1\$d/%2\$d",
    statusStartFromStrokeFormat = "%1\$d \u753b\u76ee\u304b\u3089\u958b\u59cb",
    statusTryAgainFormat = "\u3082\u3046\u4e00\u5ea6\uff08\u30df\u30b9 %1\$d \u56de\uff09",
    statusGreatContinueLabel = "\u3044\u3044\u3067\u3059\u306d\u3002\u6b21\u306e\u753b\u3078\u9032\u307f\u307e\u3057\u3087\u3046",
    statusBackwardsAcceptedLabel = "\u9006\u65b9\u5411\u3067\u3057\u305f\u304c\u8a31\u5bb9\u3057\u307e\u3057\u305f",
    statusPracticeCompleteLabel = "\u7df4\u7fd2\u5b8c\u4e86",
)

private val japaneseProgressStrings = ProgressStrings(
    title = "\u9032\u6357",
    description = "HSK\u306e\u9054\u6210\u72b6\u6cc1\u3084\u9023\u7d9a\u65e5\u6570\u3001\u6700\u8fd1\u306e\u7df4\u7fd2\u5c65\u6b74\u3092\u78ba\u8a8d\u3067\u304d\u307e\u3059\u3002\u65b0\u3057\u3044\u6f22\u5b57\u3092\u66f8\u304f\u305f\u3073\u306b\u81ea\u52d5\u3067\u66f4\u65b0\u3055\u308c\u307e\u3059\u3002",
    jumpBackLabel = "\u7df4\u7fd2\u306b\u623b\u308b",
    dailyTitle = "\u4eca\u65e5\u306e\u4e00\u5b57",
    dailyDescription = "\u6b21\u306eHSK\u5bfe\u8c61\u304b\u3089\u3001\u4eca\u65e5\u306e\u7df4\u7fd2\u6587\u5b57\u3092\u63d0\u6848\u3057\u307e\u3059\u3002",
    dailyPracticeLabel = "\u7df4\u7fd2",
    dailyCompletedLabel = "\u4eca\u65e5\u5b8c\u4e86",
    learnedLabel = "\u7fd2\u5f97\u6e08\u307f",
    streakLabel = "\u9023\u7d9a\u65e5\u6570",
    lastSessionLabel = "\u6700\u7d42\u30bb\u30c3\u30b7\u30e7\u30f3",
    streakDaySingularFormat = "%1\$d\u65e5",
    streakDayPluralFormat = "%1\$d\u65e5",
    streakStartLabel = "\u958b\u59cb",
    lastSessionNeverLabel = "\u672a\u5b9f\u65bd",
    weeklyChartTitle = "\u76f4\u8fd1 7 \u65e5",
    levelsTitle = "HSK\u30ec\u30d9\u30eb",
    levelsEmpty = "\u7df4\u7fd2\u3092\u958b\u59cb\u3059\u308b\u3068\u3001\u3053\u3053\u306b\u30ec\u30d9\u30eb\u306e\u9032\u6357\u304c\u8868\u793a\u3055\u308c\u307e\u3059\u3002",
    levelLabelFormat = "HSK %1\$d",
    levelMasteredFormat = "%1\$d/%2\$d \u6587\u5b57",
    levelJumpDescription = "\u6b21\u306e\u6f22\u5b57\u3078",
    levelBrowseCourses = "\u30b3\u30fc\u30b9\u3092\u898b\u308b",
    historyTitle = "\u6700\u8fd1\u306e\u7df4\u7fd2",
    historyEmpty = "\u6f22\u5b57\u3092\u66f8\u304f\u3068\u3053\u3053\u306b\u8868\u793a\u3055\u308c\u3001\u3059\u3050\u306b\u5fa9\u7fd2\u3067\u304d\u307e\u3059\u3002",
    historyStrokesFormat = "%1\$d\u753b \u00b7 %2\$s",
    historyMistakesPerfect = "\u30df\u30b9\u306a\u3057",
    historyMistakesFormat = "\u30df\u30b9 %1\$d\u56de",
    historyLoadCharacterFormat = "%1\$s \u3092\u8aad\u307f\u8fbc\u3080",
    relativeJustNow = "\u305f\u3063\u305f\u4eca",
    relativeMinutesFormat = "%1\$d\u5206\u524d",
    relativeHoursFormat = "%1\$d\u6642\u9593\u524d",
    relativeDaysFormat = "%1\$d\u65e5\u524d",
)

data class ProgressStrings(
    val title: String,
    val description: String,
    val jumpBackLabel: String,
    val dailyTitle: String,
    val dailyDescription: String,
    val dailyPracticeLabel: String,
    val dailyCompletedLabel: String,
    val learnedLabel: String,
    val streakLabel: String,
    val lastSessionLabel: String,
    val streakDaySingularFormat: String,
    val streakDayPluralFormat: String,
    val streakStartLabel: String,
    val lastSessionNeverLabel: String,
    val weeklyChartTitle: String,
    val levelsTitle: String,
    val levelsEmpty: String,
    val levelLabelFormat: String,
    val levelMasteredFormat: String,
    val levelJumpDescription: String,
    val levelBrowseCourses: String,
    val historyTitle: String,
    val historyEmpty: String,
    val historyStrokesFormat: String,
    val historyMistakesPerfect: String,
    val historyMistakesFormat: String,
    val historyLoadCharacterFormat: String,
    val relativeJustNow: String,
    val relativeMinutesFormat: String,
    val relativeHoursFormat: String,
    val relativeDaysFormat: String,
)

data class LibraryStrings(
    val title: String,
    val description: String,
    val tabSearchLabel: String,
    val tabFavoritesLabel: String,
    val tabHistoryLabel: String,
    val inputLabel: String,
    val supportingText: String,
    val resultsHeader: String,
    val quickTryLabel: String,
    val recentHeader: String,
    val recentClear: String,
    val recentOverflowLabel: String,
    val recentOverflowDialogTitle: String,
    val recentOverflowClose: String,
    val lookupLabel: String,
    val lookupLoadingLabel: String,
    val clearResultLabel: String,
    val editLabel: String,
    val doneLabel: String,
    val selectAllLabel: String,
    val deselectAllLabel: String,
    val selectedCountFormat: String,
    val deleteLabel: String,
    val favoritesFilterLabel: String,
    val historyFilterLabel: String,
    val filterNoResultsLabel: String,
    val favoritesHeader: String,
    val favoritesEmpty: String,
    val favoritesSaveLabel: String,
    val favoritesSavedLabel: String,
    val favoritesAddLabel: String,
    val favoritesRemoveLabel: String,
    val favoritesClearLabel: String,
    val favoritesClearDialogTitle: String,
    val favoritesClearDialogBody: String,
    val favoritesClearConfirmLabel: String,
    val favoritesClearCancelLabel: String,
    val historyHeader: String,
    val historyPinnedHeader: String,
    val historyEmpty: String,
    val historyPinLabel: String,
    val historyUnpinLabel: String,
    val historyRemoveLabel: String,
    val historyClearLabel: String,
    val historyClearDialogTitle: String,
    val historyClearDialogBody: String,
    val historyClearConfirmLabel: String,
    val historyClearCancelLabel: String,
    val sortRecentLabel: String,
    val sortNameLabel: String,
    val moreActionsLabel: String,
    val helpTitle: String,
    val helpBody: String,
    val pinyinLabelFormat: String,
    val radicalsStrokesFormat: String,
    val traditionalLabelFormat: String,
    val definitionFallback: String,
    val valueNotAvailable: String,
    val valueUnknown: String,
    val practiceButtonLabel: String,
    val practiceCharactersLabel: String,
    val quickSuggestions: List<String>,
    val errorEmpty: String,
    val errorNotFound: String,
    val errorRead: String,
)

data class LocalizedStrings(
    val locale: Locale,
    val appTitle: String,
    val navigation: NavigationStrings,
    val onboarding: OnboardingStrings,
    val searchLabel: String,
    val loadButton: String,
    val clearButton: String,
    val loadingLabel: String,
    val coursesDialogTitle: String,
    val coursePlanHeading: String,
    val courseIntroTitle: String,
    val courseIntroBullets: List<String>,
    val courseEmptyTitle: String,
    val courseEmptyDescription: String,
    val courseNoDataMessage: String,
    val expandCharactersLabel: String,
    val collapseCharactersLabel: String,
    val legendTitle: String,
    val legendGesture: String,
    val legendActiveLabel: String,
    val legendCompletedLabel: String,
    val legendRemainingLabel: String,
    val courseLegendHint: String,
    val courseLevelCompleteLabel: String,
    val courseLevelStartFormat: String,
    val courseLevelNextFormat: String,
    val levelLabelFormat: String,
    val courseLevelProgressFormat: String,
    val loadLevelFormat: String,
    val filterAllLabel: String,
    val filterRemainingLabel: String,
    val filterCompletedLabel: String,
    val helpTitle: String,
    val helpSections: List<HelpSectionText>,
    val helpConfirm: String,
    val privacyTitle: String,
    val privacyIntro: String,
    val dataSafetyHeading: String,
    val privacySummaryRows: List<SummaryRowText>,
    val contactSupportLabel: String,
    val emailSupportButton: String,
    val viewPolicyButton: String,
    val fullPolicyTitle: String,
    val fullPolicySections: List<PolicySectionText>,
    val progress: ProgressStrings,
    val library: LibraryStrings,
    val courses: CoursesStrings,
    val account: AccountStrings,
    val support: SupportStrings,
    val boardControls: PracticeBoardStrings,
)

@Composable
fun rememberLocalizedStrings(languageOverride: String?): LocalizedStrings {
    val contextLocale = LocalContext.current.resources.configuration.locales[0]
    val targetLocale = remember(languageOverride, contextLocale) {
        languageOverride?.takeIf { it.isNotBlank() }?.let { Locale.forLanguageTag(it) } ?: contextLocale
    }
    return remember(targetLocale) {
        when (targetLocale.language) {
            "es" -> localizedStringsEs(targetLocale)
            "ja" -> localizedStringsJa(targetLocale)
            else -> localizedStringsEn(targetLocale)
        }
    }
}

private val defaultCoursesStrings = CoursesStrings(
    title = "Courses",
    description = "Browse HSK levels and practice each character fully offline.",
    emptyCatalogMessage = "No course data found. Make sure assets/learn-datas is bundled.",
    filterAll = "All",
    filterRemaining = "Remaining",
    filterCompleted = "Completed",
    legendTitle = "Legend",
    legendActive = "Active",
    legendCompleted = "Completed",
    legendRemaining = "Remaining",
    legendHint = "Long press any chip to mark it as learned.",
    symbolEmptyMessage = "No characters match the current filter.",
    symbolShowAllLabel = "Show all characters",
    symbolCollapseLabel = "Collapse list",
    activeCourseTitleFormat = "Active course \u00B7 HSK %1\$d",
    activeCourseStatusFormat = "Character %1\$s \u00B7 %2\$s",
    activeResume = "Resume",
    activeSkip = "Skip",
    activeRestart = "Restart",
    activeExit = "Exit",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Level %1\$d",
    levelProgressFormat = "%1\$d/%2\$d \u00B7 remaining %3\$d",
    levelNextFormat = "Next \u00B7 %1\$s",
    levelCompletedLabel = "Completed",
    lockedSignInLabel = "Sign in",
    lockedUnlockLabel = "Unlock",
    lockedBrowseLabel = "Browse courses",
    lockedGreatJobLabel = "Great job!",
    iconStartDescriptionFormat = "Start HSK %1\$d",
    toastSkippedLabel = "Skipped character",
    toastMarkedLearnedFormat = "Marked %1\$s as learned",
    toastCourseCompleteFormat = "HSK %1\$d complete!",
    toastAutoAdvancedFormat = "Auto-advanced to %1\$s",
    toastNextUpFormat = "Next up: %1\$s",
)

private val defaultAccountStrings = AccountStrings(
    title = "Settings",
    signInCardTitle = "Sign-in status",
    signInDescriptionSignedIn = "Signed in. Purchases and unlocked levels remain linked to this device.",
    signInDescriptionSignedOut = "Guest mode keeps practice data offline. Sign in only when you are ready to unlock courses.",
    signInButtonSignedIn = "Sign out",
    signInButtonSignedOut = "Sign in & accept policy",
    courseCardTitle = "Course unlock",
    courseDescriptionSignedOut = "Preview HSK levels anytime. Sign in to complete the purchase checklist.",
    courseDescriptionUnlocked = "All premium levels are unlocked. Continue from the Courses tab.",
    courseDescriptionLocked = "One-time unlock stores a local license so lessons remain available offline.",
    courseButtonSignedOut = "Sign in required",
    courseButtonUnlocked = "Browse courses",
    courseButtonLocked = "Unlock all courses",
    supportTitle = "Support",
    supportDescription = "Help articles and privacy information live here.",
    supportFeedbackButton = "Send feedback",
    clearDataTitle = "Reset local data",
    clearDataDescription = "Remove practice history, course progress, and preferences stored on this device.",
    clearDataButton = "Clear local records",
    clearDataDialogTitle = "Erase local data?",
    clearDataDialogBody = "This removes practice history, streaks, preferences, and dictionary searches from this device. This cannot be undone.",
    consentSignInTitle = "Before signing in",
    consentSignInBullets = listOf(
        "Sign-in is only needed to associate purchases. Practice data stays on-device.",
        "Continuing confirms you have reviewed the Privacy Policy.",
        "You can remain in guest mode at any time—premium lessons simply stay locked.",
    ),
    consentSignInConfirm = "Agree & sign in",
    consentUnlockTitle = "Unlock premium lessons",
    consentUnlockBullets = listOf(
        "Payment tokens are cached locally so all content works offline.",
        "Unlocking also records the purchase under your account tab for later restores.",
        "A quick privacy reminder will appear again during checkout for compliance.",
    ),
    consentUnlockConfirm = "Confirm unlock",
    consentCheckboxLabel = "I have reviewed the privacy policy.",
    cancelLabel = "Cancel",
    closeLabel = "Close",
)

private val defaultSupportStrings = SupportStrings(
    analyticsTitle = "Usage analytics",
    analyticsDescription = "Anonymous counters for upcoming features.",
    crashTitle = "Crash reports",
    crashDescription = "Share lightweight logs if rendering fails.",
    prefetchTitle = "Network prefetch",
    prefetchDescription = "Allow Wi-Fi downloads of future packs.",
    privacyCloseLabel = "Close",
    feedbackTitle = "Send feedback",
    feedbackThanksTitle = "Thanks!",
    feedbackSavedMessage = "We stored your note locally. The next release will bundle it with diagnostic exports so nothing gets lost.",
    feedbackTopicLabel = "Topic",
    feedbackTopicPlaceholder = "Feature request, bug...",
    feedbackMessageLabel = "Details",
    feedbackMessagePlaceholder = "Describe the idea or issue",
    feedbackContactLabel = "Contact (optional)",
    feedbackContactPlaceholder = "Email or handle",
    feedbackSendLabel = "Send",
    feedbackCloseLabel = "Close",
    feedbackShareLogLabel = "Share log",
    feedbackCancelLabel = "Cancel",
    feedbackLastSentFormat = "Last sent: %1\$s",
    feedbackLogEmpty = "Feedback log is empty.",
    feedbackLogShareError = "Unable to share log.",
    feedbackLogNoApps = "No apps available to share log.",
    feedbackEmailError = "Couldn't open email. Log saved locally—share from Account later.",
    feedbackEmailNoApp = "No email app installed. Log saved locally—share from Account later.",
)

private val defaultLibraryStrings = LibraryStrings(
    title = "Dictionary",
    description = "Check pinyin, radicals, and quick definitions entirely offline. Enter a single character and hop back to Practice whenever you want to trace.",
    tabSearchLabel = "Search",
    tabFavoritesLabel = "Saved",
    tabHistoryLabel = "History",
    inputLabel = "Chinese character",
    supportingText = "Tip: Input one character (HSK 1 stays unlocked).",
    resultsHeader = "Results",
    quickTryLabel = "Try:",
    recentHeader = "Recent searches",
    recentClear = "Clear",
    recentOverflowLabel = "More...",
    recentOverflowDialogTitle = "Recent searches",
    recentOverflowClose = "Close",
    lookupLabel = "Lookup",
    lookupLoadingLabel = "Looking up...",
    clearResultLabel = "Clear result",
    editLabel = "Edit",
    doneLabel = "Done",
    selectAllLabel = "Select all",
    deselectAllLabel = "Deselect all",
    selectedCountFormat = "%1\$d selected",
    deleteLabel = "Delete",
    favoritesFilterLabel = "Filter saved",
    historyFilterLabel = "Filter history",
    filterNoResultsLabel = "No matches.",
    favoritesHeader = "Saved",
    favoritesEmpty = "Save a character or word to revisit it later.",
    favoritesSaveLabel = "Save",
    favoritesSavedLabel = "Saved",
    favoritesAddLabel = "Save",
    favoritesRemoveLabel = "Remove",
    favoritesClearLabel = "Clear",
    favoritesClearDialogTitle = "Clear saved items?",
    favoritesClearDialogBody = "This removes all saved dictionary items on this device.",
    favoritesClearConfirmLabel = "Clear",
    favoritesClearCancelLabel = "Cancel",
    historyHeader = "History",
    historyPinnedHeader = "Pinned",
    historyEmpty = "Recent dictionary lookups will appear here.",
    historyPinLabel = "Pin",
    historyUnpinLabel = "Unpin",
    historyRemoveLabel = "Remove",
    historyClearLabel = "Clear",
    historyClearDialogTitle = "Clear history?",
    historyClearDialogBody = "This clears dictionary history on this device.",
    historyClearConfirmLabel = "Clear",
    historyClearCancelLabel = "Cancel",
    sortRecentLabel = "Recent",
    sortNameLabel = "A–Z",
    moreActionsLabel = "More",
    helpTitle = "Tips",
    helpBody = "- Data comes from the bundled word.db so it works offline.\n- Saved items and history stay only on your device.\n- For writing details and privacy specifics see docs/help-guide.md in the project.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Strokes: %2\$s",
    traditionalLabelFormat = "Traditional: %1\$s",
    definitionFallback = "No definition available.",
    valueNotAvailable = "N/A",
    valueUnknown = "?",
    practiceButtonLabel = "Practice this character",
    practiceCharactersLabel = "Practice characters",
    quickSuggestions = listOf("永", "学", "好", "中", "发"),
    errorEmpty = "Enter one character to search.",
    errorNotFound = "Character not found in the offline dictionary.",
    errorRead = "Unable to read the dictionary. Try again.",
)

private val spanishLibraryStrings = LibraryStrings(
    title = "Diccionario",
    description = "Consulta pinyin, radicales y definiciones rápidas completamente sin conexión. Ingresa un solo carácter y vuelve a Práctica cuando quieras trazarlo.",
    tabSearchLabel = "Buscar",
    tabFavoritesLabel = "Guardados",
    tabHistoryLabel = "Historial",
    inputLabel = "Carácter chino",
    supportingText = "Consejo: escribe un carácter (HSK 1 siempre está desbloqueado).",
    resultsHeader = "Resultados",
    quickTryLabel = "Prueba:",
    recentHeader = "Búsquedas recientes",
    recentClear = "Limpiar",
    recentOverflowLabel = "Más...",
    recentOverflowDialogTitle = "Búsquedas recientes",
    recentOverflowClose = "Cerrar",
    lookupLabel = "Buscar",
    lookupLoadingLabel = "Buscando...",
    clearResultLabel = "Borrar resultado",
    editLabel = "Editar",
    doneLabel = "Listo",
    selectAllLabel = "Seleccionar todo",
    deselectAllLabel = "Quitar selección",
    selectedCountFormat = "%1\$d seleccionados",
    deleteLabel = "Eliminar",
    favoritesFilterLabel = "Filtrar guardados",
    historyFilterLabel = "Filtrar historial",
    filterNoResultsLabel = "Sin coincidencias.",
    favoritesHeader = "Guardados",
    favoritesEmpty = "Guarda un carácter o palabra para verla más tarde.",
    favoritesSaveLabel = "Guardar",
    favoritesSavedLabel = "Guardado",
    favoritesAddLabel = "Guardar",
    favoritesRemoveLabel = "Quitar",
    favoritesClearLabel = "Limpiar",
    favoritesClearDialogTitle = "¿Limpiar guardados?",
    favoritesClearDialogBody = "Esto elimina todos los elementos guardados del diccionario en este dispositivo.",
    favoritesClearConfirmLabel = "Limpiar",
    favoritesClearCancelLabel = "Cancelar",
    historyHeader = "Historial",
    historyPinnedHeader = "Fijados",
    historyEmpty = "Tus búsquedas recientes aparecerán aquí.",
    historyPinLabel = "Fijar",
    historyUnpinLabel = "Quitar fijación",
    historyRemoveLabel = "Quitar",
    historyClearLabel = "Limpiar",
    historyClearDialogTitle = "¿Limpiar historial?",
    historyClearDialogBody = "Esto borra el historial del diccionario en este dispositivo.",
    historyClearConfirmLabel = "Limpiar",
    historyClearCancelLabel = "Cancelar",
    sortRecentLabel = "Reciente",
    sortNameLabel = "A–Z",
    moreActionsLabel = "Más",
    helpTitle = "Consejos",
    helpBody = "- Los datos provienen del word.db incluido, así que funciona sin conexión.\n- Guardados e historial se quedan solo en el dispositivo.\n- Para detalles de caligrafía y privacidad revisa docs/help-guide.md dentro del proyecto.",
    pinyinLabelFormat = "Pinyin: %1\$s",
    radicalsStrokesFormat = "Radical: %1\$s    Trazos: %2\$s",
    traditionalLabelFormat = "Tradicional: %1\$s",
    definitionFallback = "Sin definición disponible.",
    valueNotAvailable = "N/D",
    valueUnknown = "?",
    practiceButtonLabel = "Practicar este carácter",
    practiceCharactersLabel = "Practicar caracteres",
    quickSuggestions = listOf("永", "发", "学", "好", "汉"),
    errorEmpty = "Ingresa un carácter para buscar.",
    errorNotFound = "Carácter no encontrado en el diccionario sin conexión.",
    errorRead = "No se pudo leer el diccionario. Intenta de nuevo.",
)

private val japaneseLibraryStrings = LibraryStrings(
    title = "辞書",
    description = "ピンイン・部首・簡単な意味をすべてオフラインで確認できます。1文字だけ入力して、いつでも練習タブに戻りましょう。",
    tabSearchLabel = "検索",
    tabFavoritesLabel = "保存",
    tabHistoryLabel = "履歴",
    inputLabel = "漢字",
    supportingText = "ヒント: 1文字のみ入力してください（HSK1は常に解放済み）。",
    resultsHeader = "結果",
    quickTryLabel = "例:",
    recentHeader = "最近の検索",
    recentClear = "削除",
    recentOverflowLabel = "もっと見る",
    recentOverflowDialogTitle = "最近の検索",
    recentOverflowClose = "閉じる",
    lookupLabel = "検索",
    lookupLoadingLabel = "検索中...",
    clearResultLabel = "結果をクリア",
    editLabel = "編集",
    doneLabel = "完了",
    selectAllLabel = "すべて選択",
    deselectAllLabel = "選択解除",
    selectedCountFormat = "%1\$d 件を選択",
    deleteLabel = "削除",
    favoritesFilterLabel = "保存を絞り込み",
    historyFilterLabel = "履歴を絞り込み",
    filterNoResultsLabel = "一致する項目がありません。",
    favoritesHeader = "保存",
    favoritesEmpty = "後で見返すために保存できます。",
    favoritesSaveLabel = "保存",
    favoritesSavedLabel = "保存済み",
    favoritesAddLabel = "保存",
    favoritesRemoveLabel = "削除",
    favoritesClearLabel = "削除",
    favoritesClearDialogTitle = "保存済みを削除しますか？",
    favoritesClearDialogBody = "この端末に保存された辞書の保存項目をすべて削除します。",
    favoritesClearConfirmLabel = "削除",
    favoritesClearCancelLabel = "キャンセル",
    historyHeader = "履歴",
    historyPinnedHeader = "固定",
    historyEmpty = "最近の辞書検索がここに表示されます。",
    historyPinLabel = "固定",
    historyUnpinLabel = "固定解除",
    historyRemoveLabel = "削除",
    historyClearLabel = "削除",
    historyClearDialogTitle = "履歴を削除しますか？",
    historyClearDialogBody = "この端末の辞書履歴を削除します。",
    historyClearConfirmLabel = "削除",
    historyClearCancelLabel = "キャンセル",
    sortRecentLabel = "最近",
    sortNameLabel = "A–Z",
    moreActionsLabel = "その他",
    helpTitle = "ヒント",
    helpBody = "- データは同梱の word.db から読み込むため完全オフラインで動作します。\n- 保存と履歴はこの端末内にのみ保存されます。\n- 筆順やプライバシーの詳細は docs/help-guide.md を参照してください。",
    pinyinLabelFormat = "ピンイン：%1\$s",
    radicalsStrokesFormat = "部首：%1\$s    画数：%2\$s",
    traditionalLabelFormat = "繁体字：%1\$s",
    definitionFallback = "意味を取得できませんでした。",
    valueNotAvailable = "該当なし",
    valueUnknown = "?",
    practiceButtonLabel = "この漢字で練習",
    practiceCharactersLabel = "文字ごとに練習",
    quickSuggestions = listOf("永", "学", "好", "新", "漢"),
    errorEmpty = "検索する漢字を1文字入力してください。",
    errorNotFound = "オフライン辞書で該当する漢字が見つかりません。",
    errorRead = "辞書を読み込めませんでした。もう一度お試しください。",
)


private val spanishCoursesStrings = CoursesStrings(
    title = "Cursos",
    description = "Explora niveles HSK y practica cada carácter completamente sin conexión.",
    emptyCatalogMessage = "No se encontraron datos del curso. Comprueba que assets/learn-datas esté incluido en el APK.",
    filterAll = "Todos",
    filterRemaining = "Pendientes",
    filterCompleted = "Completados",
    legendTitle = "Leyenda",
    legendActive = "Activo",
    legendCompleted = "Completado",
    legendRemaining = "Pendiente",
    legendHint = "Mantén pulsado cualquier icono para marcarlo como aprendido.",
    symbolEmptyMessage = "Ningún carácter coincide con el filtro actual.",
    symbolShowAllLabel = "Mostrar todos los caracteres",
    symbolCollapseLabel = "Ocultar lista",
    activeCourseTitleFormat = "Curso activo · HSK %1\$d",
    activeCourseStatusFormat = "Carácter %1\$s · %2\$s",
    activeResume = "Reanudar",
    activeSkip = "Saltar",
    activeRestart = "Reiniciar",
    activeExit = "Salir",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "Nivel %1\$d",
    levelProgressFormat = "%1\$d/%2\$d · faltan %3\$d",
    levelNextFormat = "Siguiente · %1\$s",
    levelCompletedLabel = "Completado",
    lockedSignInLabel = "Iniciar sesión",
    lockedUnlockLabel = "Desbloquear",
    lockedBrowseLabel = "Ver cursos",
    lockedGreatJobLabel = "¡Buen trabajo!",
    iconStartDescriptionFormat = "Iniciar HSK %1\$d",
    toastSkippedLabel = "Carácter omitido",
    toastMarkedLearnedFormat = "Marcaste %1\$s como aprendido",
    toastCourseCompleteFormat = "HSK %1\$d completado",
    toastAutoAdvancedFormat = "Avance automático a %1\$s",
    toastNextUpFormat = "Siguiente: %1\$s",
)

private val spanishAccountStrings = AccountStrings(
    title = "Ajustes",
    signInCardTitle = "Estado de sesión",
    signInDescriptionSignedIn = "Sesión iniciada. Las compras y niveles desbloqueados siguen ligados a este dispositivo.",
    signInDescriptionSignedOut = "El modo invitado mantiene los datos de práctica sin conexión. Inicia sesión solo cuando quieras desbloquear cursos.",
    signInButtonSignedIn = "Cerrar sesión",
    signInButtonSignedOut = "Iniciar sesión y aceptar política",
    courseCardTitle = "Desbloqueo de cursos",
    courseDescriptionSignedOut = "Consulta los niveles HSK cuando quieras. Inicia sesión para completar la compra.",
    courseDescriptionUnlocked = "Todos los niveles premium están desbloqueados. Continúa desde la pestaña Cursos.",
    courseDescriptionLocked = "Un desbloqueo único guarda una licencia local para que las lecciones sigan disponibles offline.",
    courseButtonSignedOut = "Se requiere sesión",
    courseButtonUnlocked = "Ver cursos",
    courseButtonLocked = "Desbloquear todos los cursos",
    supportTitle = "Soporte",
    supportDescription = "La ayuda y la información de privacidad viven aquí.",
    supportFeedbackButton = "Enviar comentarios",
    clearDataTitle = "Restablecer datos locales",
    clearDataDescription = "Elimina el historial de práctica, el progreso y las preferencias guardadas en este dispositivo.",
    clearDataButton = "Borrar registros locales",
    clearDataDialogTitle = "¿Borrar datos locales?",
    clearDataDialogBody = "Se eliminarán el historial, las rachas, las preferencias y las búsquedas del diccionario de este dispositivo. Esta acción no se puede deshacer.",
    consentSignInTitle = "Antes de iniciar sesión",
    consentSignInBullets = listOf(
        "Solo necesitas iniciar sesión para asociar compras. Los datos de práctica permanecen en el dispositivo.",
        "Al continuar confirmas que revisaste la Política de Privacidad.",
        "Puedes seguir en modo invitado: las lecciones premium simplemente seguirán bloqueadas.",
    ),
    consentSignInConfirm = "Aceptar e iniciar sesión",
    consentUnlockTitle = "Desbloquear lecciones premium",
    consentUnlockBullets = listOf(
        "Los tokens de pago se guardan localmente para que todo funcione sin conexión.",
        "El desbloqueo también registra la compra en la pestaña Cuenta para restauraciones posteriores.",
        "Durante el pago volverá a mostrarse un recordatorio de privacidad por cumplimiento.",
    ),
    consentUnlockConfirm = "Confirmar desbloqueo",
    consentCheckboxLabel = "Ya revisé la política de privacidad.",
    cancelLabel = "Cancelar",
    closeLabel = "Cerrar",
)

private val spanishSupportStrings = SupportStrings(
    analyticsTitle = "Analítica de uso",
    analyticsDescription = "Contadores anónimos para funciones futuras.",
    crashTitle = "Informes de fallos",
    crashDescription = "Comparte registros ligeros si falla el renderizado.",
    prefetchTitle = "Prefetch de red",
    prefetchDescription = "Permite descargas por Wi‑Fi de paquetes futuros.",
    privacyCloseLabel = "Cerrar",
    feedbackTitle = "Enviar comentarios",
    feedbackThanksTitle = "¡Gracias!",
    feedbackSavedMessage = "Guardamos tu nota localmente. La próxima versión la adjuntará a los diagnósticos para que nada se pierda.",
    feedbackTopicLabel = "Tema",
    feedbackTopicPlaceholder = "Solicitud, error...",
    feedbackMessageLabel = "Detalles",
    feedbackMessagePlaceholder = "Describe la idea o el problema",
    feedbackContactLabel = "Contacto (opcional)",
    feedbackContactPlaceholder = "Correo o usuario",
    feedbackSendLabel = "Enviar",
    feedbackCloseLabel = "Cerrar",
    feedbackShareLogLabel = "Compartir registro",
    feedbackCancelLabel = "Cancelar",
    feedbackLastSentFormat = "Último envío: %1\$s",
    feedbackLogEmpty = "El registro está vacío.",
    feedbackLogShareError = "No se pudo compartir el registro.",
    feedbackLogNoApps = "No hay aplicaciones disponibles para compartir el registro.",
    feedbackEmailError = "No se pudo abrir el correo. El registro quedó guardado; compártelo luego desde Cuenta.",
    feedbackEmailNoApp = "No hay aplicaciones de correo instaladas. El registro quedó guardado; compártelo luego desde Cuenta.",
)




private val japaneseCoursesStrings = CoursesStrings(
    title = "コース",
    description = "すべてのHSKパックを無料でプレビューできます。オフラインで学びたいレベルだけ後から解除しましょう。",
    emptyCatalogMessage = "コースデータが見つかりません。assets/learn-data がバンドルされているか確認してください。",
    filterAll = "すべて",
    filterRemaining = "学習予定",
    filterCompleted = "完了",
    legendTitle = "凡例",
    legendActive = "学習中",
    legendCompleted = "完了",
    legendRemaining = "未学習",
    legendHint = "長押しで習得済みに切り替えられます。",
    symbolEmptyMessage = "現在のフィルターに一致する文字はありません。",
    symbolShowAllLabel = "すべての文字を表示",
    symbolCollapseLabel = "一覧を閉じる",
    activeCourseTitleFormat = "進行中のコース・HSK %1\$d",
    activeCourseStatusFormat = "文字 %1\$s ・ %2\$s",
    activeResume = "再開",
    activeSkip = "スキップ",
    activeRestart = "最初から",
    activeExit = "終了",
    levelHeaderFormat = "HSK %1\$d",
    levelChipFormat = "レベル %1\$d",
    levelProgressFormat = "%1\$d/%2\$d ・ 残り %3\$d",
    levelNextFormat = "次 ・ %1\$s",
    levelCompletedLabel = "完了",
    lockedSignInLabel = "サインイン",
    lockedUnlockLabel = "解除",
    lockedBrowseLabel = "コースを見る",
    lockedGreatJobLabel = "お疲れさま！",
    iconStartDescriptionFormat = "HSK %1\$d を開始",
    toastSkippedLabel = "スキップしました",
    toastMarkedLearnedFormat = "%1\$s を習得済みにしました",
    toastCourseCompleteFormat = "HSK %1\$d 完了！",
    toastAutoAdvancedFormat = "%1\$s に自動で進みました",
    toastNextUpFormat = "次：%1\$s",
)

private val japaneseAccountStrings = AccountStrings(
    title = "\u8a2d\u5b9a",
    signInCardTitle = "\u30b5\u30a4\u30f3\u30a4\u30f3\u30b9\u30c6\u30fc\u30bf\u30b9",
    signInDescriptionSignedIn = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u3044\u307e\u3059\u3002\u8cfc\u5165\u304a\u3088\u3073\u30ed\u30c3\u30af\u89e3\u9664\u3055\u308c\u305f\u30ec\u30d9\u30eb\u306f\u3001\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u306b\u30ea\u30f3\u30af\u3055\u308c\u305f\u307e\u307e\u306b\u306a\u308a\u307e\u3059\u3002",
    signInDescriptionSignedOut = "\u30b2\u30b9\u30c8 \u30e2\u30fc\u30c9\u3067\u306f\u3001\u7df4\u7fd2\u30c7\u30fc\u30bf\u3092\u30aa\u30d5\u30e9\u30a4\u30f3\u306b\u4fdd\u3061\u307e\u3059\u3002\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b\u6e96\u5099\u304c\u3067\u304d\u3066\u3044\u308b\u5834\u5408\u306b\u306e\u307f\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u304f\u3060\u3055\u3044\u3002",
    signInButtonSignedIn = "\u30b5\u30a4\u30f3\u30a2\u30a6\u30c8",
    signInButtonSignedOut = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u30dd\u30ea\u30b7\u30fc\u306b\u540c\u610f\u3059\u308b",
    courseCardTitle = "\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u89e3\u9664",
    courseDescriptionSignedOut = "HSK \u30ec\u30d9\u30eb\u3092\u3044\u3064\u3067\u3082\u30d7\u30ec\u30d3\u30e5\u30fc\u3067\u304d\u307e\u3059\u3002\u30b5\u30a4\u30f3\u30a4\u30f3\u3057\u3066\u8cfc\u5165\u30c1\u30a7\u30c3\u30af\u30ea\u30b9\u30c8\u3092\u5b8c\u4e86\u3057\u307e\u3059\u3002",
    courseDescriptionUnlocked = "\u3059\u3079\u3066\u306e\u30d7\u30ec\u30df\u30a2\u30e0\u30ec\u30d9\u30eb\u304c\u30ed\u30c3\u30af\u89e3\u9664\u6e08\u307f\u3067\u3059\u3002\u30b3\u30fc\u30b9\u30bf\u30d6\u304b\u3089\u518d\u958b\u3057\u307e\u3057\u3087\u3046\u3002",
    courseDescriptionLocked = "\u30ef\u30f3\u30bf\u30a4\u30e0\u30ed\u30c3\u30af\u89e3\u9664\u3067\u306f\u30ed\u30fc\u30ab\u30eb\u30e9\u30a4\u30bb\u30f3\u30b9\u304c\u4fdd\u5b58\u3055\u308c\u308b\u305f\u3081\u3001\u30ec\u30c3\u30b9\u30f3\u306f\u30aa\u30d5\u30e9\u30a4\u30f3\u3067\u3082\u5229\u7528\u3067\u304d\u307e\u3059\u3002",
    courseButtonSignedOut = "\u30b5\u30a4\u30f3\u30a4\u30f3\u304c\u5fc5\u8981\u3067\u3059",
    courseButtonUnlocked = "\u30b3\u30fc\u30b9\u3092\u95b2\u89a7\u3059\u308b",
    courseButtonLocked = "\u3059\u3079\u3066\u306e\u30b3\u30fc\u30b9\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b",
    supportTitle = "\u30b5\u30dd\u30fc\u30c8",
    supportDescription = "\u30d8\u30eb\u30d7\u3068\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u60c5\u5831\u306f\u3053\u3053\u304b\u3089\u5229\u7528\u3067\u304d\u307e\u3059\u3002",
    supportFeedbackButton = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af\u3092\u9001\u4fe1\u3059\u308b",
    clearDataTitle = "\u30ed\u30fc\u30ab\u30eb\u30c7\u30fc\u30bf\u3092\u30ea\u30bb\u30c3\u30c8\u3059\u308b",
    clearDataDescription = "\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u306b\u4fdd\u5b58\u3055\u308c\u3066\u3044\u308b\u7df4\u7fd2\u5c65\u6b74\u3001\u30b3\u30fc\u30b9\u306e\u9032\u884c\u72b6\u6cc1\u3001\u8a2d\u5b9a\u3092\u524a\u9664\u3057\u307e\u3059\u3002",
    clearDataButton = "\u30ed\u30fc\u30ab\u30eb\u8a18\u9332\u3092\u30af\u30ea\u30a2\u3059\u308b",
    clearDataDialogTitle = "\u30ed\u30fc\u30ab\u30eb\u30c7\u30fc\u30bf\u3092\u6d88\u53bb\u3057\u307e\u3059\u304b\uff1f",
    clearDataDialogBody = "\u3053\u308c\u306b\u3088\u308a\u3001\u7df4\u7fd2\u5c65\u6b74\u3001\u30b9\u30c8\u30ea\u30fc\u30af\u3001\u8a2d\u5b9a\u3001\u8f9e\u66f8\u691c\u7d22\u304c\u3053\u306e\u30c7\u30d0\u30a4\u30b9\u304b\u3089\u524a\u9664\u3055\u308c\u307e\u3059\u3002\u3053\u308c\u3092\u5143\u306b\u623b\u3059\u3053\u3068\u306f\u3067\u304d\u307e\u305b\u3093\u3002",
    consentSignInTitle = "\u30b5\u30a4\u30f3\u30a4\u30f3\u3059\u308b\u524d\u306b",
    consentSignInConfirm = "\u540c\u610f\u3057\u3066\u30b5\u30a4\u30f3\u30a4\u30f3\u3059\u308b",
    consentUnlockTitle = "\u30d7\u30ec\u30df\u30a2\u30e0\u30ec\u30c3\u30b9\u30f3\u306e\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b",
    consentUnlockConfirm = "\u30ed\u30c3\u30af\u89e3\u9664\u306e\u78ba\u8a8d",
    consentCheckboxLabel = "\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u30dd\u30ea\u30b7\u30fc\u3092\u78ba\u8a8d\u3057\u307e\u3057\u305f\u3002",
    cancelLabel = "\u30ad\u30e3\u30f3\u30bb\u30eb",
    closeLabel = "\u9589\u3058\u308b",
    consentSignInBullets = listOf(
        "\u30b5\u30a4\u30f3\u30a4\u30f3\u306f\u3001\u8cfc\u5165\u3092\u95a2\u9023\u4ed8\u3051\u308b\u5834\u5408\u306b\u306e\u307f\u5fc5\u8981\u3067\u3059\u3002\u7df4\u7fd2\u30c7\u30fc\u30bf\u306f\u30c7\u30d0\u30a4\u30b9\u4e0a\u306b\u6b8b\u308a\u307e\u3059\u3002",
        "\u7d9a\u884c\u3059\u308b\u3068\u3001\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc \u30dd\u30ea\u30b7\u30fc\u3092\u78ba\u8a8d\u3057\u305f\u3053\u3068\u3092\u78ba\u8a8d\u3057\u307e\u3059\u3002",
        "\u3044\u3064\u3067\u3082\u30b2\u30b9\u30c8 \u30e2\u30fc\u30c9\u306e\u307e\u307e\u306b\u3059\u308b\u3053\u3068\u304c\u3067\u304d\u307e\u3059\u3002\u30d7\u30ec\u30df\u30a2\u30e0 \u30ec\u30c3\u30b9\u30f3\u306f\u30ed\u30c3\u30af\u3055\u308c\u305f\u307e\u307e\u306b\u306a\u308a\u307e\u3059\u3002",
    ),
    consentUnlockBullets = listOf(
        "\u652f\u6255\u3044\u30c8\u30fc\u30af\u30f3\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u30ad\u30e3\u30c3\u30b7\u30e5\u3055\u308c\u308b\u305f\u3081\u3001\u3059\u3079\u3066\u306e\u30b3\u30f3\u30c6\u30f3\u30c4\u306f\u30aa\u30d5\u30e9\u30a4\u30f3\u3067\u52d5\u4f5c\u3057\u307e\u3059\u3002",
        "\u30ed\u30c3\u30af\u3092\u89e3\u9664\u3059\u308b\u3068\u3001\u5f8c\u3067\u5fa9\u5143\u3067\u304d\u308b\u3088\u3046\u306b\u3001\u30a2\u30ab\u30a6\u30f3\u30c8 \u30bf\u30d6\u306b\u8cfc\u5165\u5185\u5bb9\u3082\u8a18\u9332\u3055\u308c\u307e\u3059\u3002",
        "\u30b3\u30f3\u30d7\u30e9\u30a4\u30a2\u30f3\u30b9\u3092\u78ba\u4fdd\u3059\u308b\u305f\u3081\u306b\u3001\u30c1\u30a7\u30c3\u30af\u30a2\u30a6\u30c8\u4e2d\u306b\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc\u306b\u95a2\u3059\u308b\u7c21\u5358\u306a\u30ea\u30de\u30a4\u30f3\u30c0\u30fc\u304c\u518d\u5ea6\u8868\u793a\u3055\u308c\u307e\u3059\u3002",
    ),
)


private val japaneseSupportStrings = SupportStrings(
    analyticsTitle = "\u4f7f\u7528\u72b6\u6cc1\u5206\u6790",
    analyticsDescription = "\u4eca\u5f8c\u306e\u6a5f\u80fd\u306e\u533f\u540d\u30ab\u30a6\u30f3\u30bf\u30fc\u3002",
    crashTitle = "\u30af\u30e9\u30c3\u30b7\u30e5\u30ec\u30dd\u30fc\u30c8",
    crashDescription = "\u30ec\u30f3\u30c0\u30ea\u30f3\u30b0\u304c\u5931\u6557\u3057\u305f\u5834\u5408\u306f\u8efd\u91cf\u30ed\u30b0\u3092\u5171\u6709\u3057\u307e\u3059\u3002",
    prefetchTitle = "\u30cd\u30c3\u30c8\u30ef\u30fc\u30af\u30d7\u30ea\u30d5\u30a7\u30c3\u30c1",
    prefetchDescription = "\u5c06\u6765\u306e\u30d1\u30c3\u30af\u306e Wi-Fi \u30c0\u30a6\u30f3\u30ed\u30fc\u30c9\u3092\u8a31\u53ef\u3057\u307e\u3059\u3002",
    privacyCloseLabel = "\u9589\u3058\u308b",
    feedbackTitle = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af\u3092\u9001\u4fe1\u3059\u308b",
    feedbackThanksTitle = "\u3042\u308a\u304c\u3068\u3046\uff01",
    feedbackSavedMessage = "\u3042\u306a\u305f\u306e\u30e1\u30e2\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3057\u305f\u3002\u6b21\u306e\u30ea\u30ea\u30fc\u30b9\u3067\u306f\u8a3a\u65ad\u30a8\u30af\u30b9\u30dd\u30fc\u30c8\u304c\u30d0\u30f3\u30c9\u30eb\u3055\u308c\u308b\u305f\u3081\u3001\u4f55\u3082\u5931\u308f\u308c\u308b\u3053\u3068\u306f\u3042\u308a\u307e\u305b\u3093\u3002",
    feedbackTopicLabel = "\u30c8\u30d4\u30c3\u30af",
    feedbackTopicPlaceholder = "\u6a5f\u80fd\u30ea\u30af\u30a8\u30b9\u30c8\u3001\u30d0\u30b0...",
    feedbackMessageLabel = "\u8a73\u7d30",
    feedbackMessagePlaceholder = "\u30a2\u30a4\u30c7\u30a2\u3084\u554f\u984c\u306b\u3064\u3044\u3066\u8aac\u660e\u3059\u308b",
    feedbackContactLabel = "\u9023\u7d61\u5148 (\u30aa\u30d7\u30b7\u30e7\u30f3)",
    feedbackContactPlaceholder = "\u30e1\u30fc\u30eb\u307e\u305f\u306f\u30cf\u30f3\u30c9\u30eb",
    feedbackSendLabel = "\u9001\u4fe1",
    feedbackCloseLabel = "\u9589\u3058\u308b",
    feedbackShareLogLabel = "\u30ed\u30b0\u3092\u5171\u6709\u3059\u308b",
    feedbackCancelLabel = "\u30ad\u30e3\u30f3\u30bb\u30eb",
    feedbackLastSentFormat = "\u6700\u5f8c\u306b\u9001\u4fe1\u3057\u307e\u3057\u305f: %1\$s",
    feedbackLogEmpty = "\u30d5\u30a3\u30fc\u30c9\u30d0\u30c3\u30af \u30ed\u30b0\u304c\u7a7a\u3067\u3059\u3002",
    feedbackLogShareError = "\u30ed\u30b0\u3092\u5171\u6709\u3067\u304d\u307e\u305b\u3093\u3002",
    feedbackLogNoApps = "\u30ed\u30b0\u3092\u5171\u6709\u3067\u304d\u308b\u30a2\u30d7\u30ea\u304c\u3042\u308a\u307e\u305b\u3093\u3002",
    feedbackEmailError = "\u30e1\u30fc\u30eb\u3092\u958b\u3051\u307e\u305b\u3093\u3067\u3057\u305f\u3002\u30ed\u30b0\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3059\u3002\u5f8c\u3067\u30a2\u30ab\u30a6\u30f3\u30c8\u304b\u3089\u5171\u6709\u3057\u307e\u3059\u3002",
    feedbackEmailNoApp = "\u30e1\u30fc\u30eb\u30a2\u30d7\u30ea\u304c\u30a4\u30f3\u30b9\u30c8\u30fc\u30eb\u3055\u308c\u3066\u3044\u307e\u305b\u3093\u3002\u30ed\u30b0\u306f\u30ed\u30fc\u30ab\u30eb\u306b\u4fdd\u5b58\u3055\u308c\u307e\u3059\u3002\u5f8c\u3067\u30a2\u30ab\u30a6\u30f3\u30c8\u304b\u3089\u5171\u6709\u3057\u307e\u3059\u3002",
)
private val defaultNavigationStrings = NavigationStrings(
    homeLabel = "首页",
    learnLabel = "学习",
    libraryLabel = "字典",
    accountLabel = "我的",
)

private val spanishNavigationStrings = NavigationStrings(
    homeLabel = "Inicio",
    learnLabel = "Aprender",
    libraryLabel = "Diccionario",
    accountLabel = "Ajustes",
)

private val japaneseNavigationStrings = NavigationStrings(
    homeLabel = "ホーム",
    learnLabel = "学習",
    libraryLabel = "辞書",
    accountLabel = "設定",
)

private val defaultOnboardingStrings = OnboardingStrings(
    appTitle = "Hanzi",
    skipLabel = "Skip",
    backLabel = "Back",
    nextLabel = "Next",
    startLabel = "Start",
    pages = listOf(
        OnboardingPageText(
            title = "Look up characters fast",
            body = "Search stroke order and pronunciation offline, anytime you need it.",
        ),
        OnboardingPageText(
            title = "Practice with guidance",
            body = "Trace strokes and get hints to improve accuracy and confidence.",
        ),
        OnboardingPageText(
            title = "Dictionary when you need details",
            body = "Open the dictionary card to see pinyin and meaning without leaving practice.",
        ),
        OnboardingPageText(
            title = "Safer pronunciation playback",
            body = "Enable volume reminders to avoid playing audio too loud in public.",
        ),
    ),
)

private val spanishOnboardingStrings = OnboardingStrings(
    appTitle = "Hanzi",
    skipLabel = "Saltar",
    backLabel = "Atrás",
    nextLabel = "Siguiente",
    startLabel = "Empezar",
    pages = listOf(
        OnboardingPageText(
            title = "Busca caracteres rápido",
            body = "Consulta el orden de trazos y la pronunciación sin conexión, cuando lo necesites.",
        ),
        OnboardingPageText(
            title = "Practica con guía",
            body = "Traza los trazos y recibe pistas para mejorar la precisión y la confianza.",
        ),
        OnboardingPageText(
            title = "Diccionario cuando necesites detalles",
            body = "Abre la tarjeta del diccionario para ver pinyin y significado sin salir de la práctica.",
        ),
        OnboardingPageText(
            title = "Reproducción de audio más segura",
            body = "Activa recordatorios de volumen para evitar reproducir audio demasiado alto en público.",
        ),
    ),
)

private val japaneseOnboardingStrings = OnboardingStrings(
    appTitle = "漢字",
    skipLabel = "スキップ",
    backLabel = "戻る",
    nextLabel = "次へ",
    startLabel = "開始",
    pages = listOf(
        OnboardingPageText(
            title = "素早く漢字を調べる",
            body = "筆順と発音をオフラインでいつでも確認できます。",
        ),
        OnboardingPageText(
            title = "ガイド付きで練習",
            body = "なぞって練習し、ヒントで精度と自信を高めましょう。",
        ),
        OnboardingPageText(
            title = "必要なときに辞書",
            body = "練習を離れずに辞書カードで読み方と意味を確認できます。",
        ),
        OnboardingPageText(
            title = "より安全な音量で再生",
            body = "公共の場で音が大きすぎないよう、音量リマインダーを有効にできます。",
        ),
    ),
)

private fun localizedStringsEn(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    navigation = defaultNavigationStrings,
    onboarding = defaultOnboardingStrings,
    searchLabel = "Hanzi",
    loadButton = "Load character",
    clearButton = "Clear input",
    loadingLabel = "Loading...",
    coursesDialogTitle = "HSK Courses",
    coursePlanHeading = "Pick a course to continue",
    courseIntroTitle = "How courses work",
    courseIntroBullets = listOf(
        "Choose an HSK level to begin or jump back in.",
        "Tap a character to practice; long-press to mark it mastered.",
        "The badge above the board mirrors your current course progress.",
    ),
    courseEmptyTitle = "No active course yet",
    courseEmptyDescription = "Select an HSK level below to start a guided session.",
    courseNoDataMessage = "No course data found. Please double-check the resource pack.",
    expandCharactersLabel = "Show all",
    collapseCharactersLabel = "Hide",
    legendTitle = "Legend & gestures",
    legendGesture = "Tap any character to practice; long-press to mark it as learned.",
    legendActiveLabel = "Active",
    legendCompletedLabel = "Completed",
    legendRemainingLabel = "Remaining",
    courseLegendHint = "Badge controls let you resume, skip, restart, or exit without covering the board.",
    courseLevelCompleteLabel = "Course complete",
    courseLevelStartFormat = "Start with %s",
    courseLevelNextFormat = "Next • %s",
    levelLabelFormat = "Level %d",
    courseLevelProgressFormat = "%1\$d/%2\$d mastered · %3\$d remaining",
    loadLevelFormat = "Load HSK %d",
    filterAllLabel = "All",
    filterRemainingLabel = "Remaining",
    filterCompletedLabel = "Completed",
    helpTitle = "Help & onboarding",
    helpSections = listOf(
        HelpSectionText(
            title = "Quick start",
            description = "Complete a full demo → practice cycle in seconds.",
            bullets = listOf(
                "Enter any hanzi and tap the cloud icon to load offline data.",
                "Use Play or Loop to watch the demo; enable the calligraphy template for tracing.",
                "Press the pencil on the board to begin; the hint icon highlights the next stroke.",
            ),
        ),
        HelpSectionText(
            title = "Courses & progress",
            description = "HSK courses live under the avatar menu, and the badge reflects your status.",
            bullets = listOf(
                "Resume/Skip/Restart/Exit icons stay inside the badge so controls never hide the board.",
                "Chevron arrows jump between characters; finishing one updates the summary instantly.",
            ),
        ),
        HelpSectionText(
            title = "Cards & pronunciation",
            description = "The Kaishu card shows dictionary data plus TextToSpeech playback.",
            bullets = listOf(
                "Tap the card to open the full definition and scroll through the explanation.",
                "The speaker button plays Mandarin audio entirely offline.",
            ),
        ),
        HelpSectionText(
            title = "Grids & templates",
            description = "Board settings support Mi-grid, nine-grid, or no guides at all.",
            bullets = listOf(
                "Switch between outline and freestyle modes; stroke colors persist between sessions.",
                "Scroll outside the canvas to move the page so the writing surface stays fixed.",
            ),
        ),
        HelpSectionText(
            title = "Support",
            description = "Need help? Reach out anytime.",
            bullets = listOf(
                "Email: qq260316514@gmail.com",
                "This app runs fully offline and never uploads your data.",
            ),
        ),
    ),
    helpConfirm = "Got it",
    privacyTitle = "Privacy",
    privacyIntro = "Fully offline by default.",
    dataSafetyHeading = "Data safety snapshot",
    privacySummaryRows = listOf(
        SummaryRowText(
            title = "Data storage",
            detail = "Practice history, course progress, and board settings stay in local DataStore only.",
        ),
        SummaryRowText(
            title = "Offline assets",
            detail = "Stroke JSON and course packs ship inside the APK.",
        ),
        SummaryRowText(
            title = "Notifications",
            detail = "Optional daily reminders. On Android 13+ the app asks for notification permission only if you enable reminders.",
        ),
        SummaryRowText(
            title = "Network",
            detail = "No network permission. The app does not access the internet and never uploads your data.",
        ),
    ),
    contactSupportLabel = "Contact: %s",
    emailSupportButton = "Email support",
    viewPolicyButton = "View full policy",
    fullPolicyTitle = "Privacy policy",
    fullPolicySections = listOf(
        PolicySectionText(
            title = "1. Data we collect",
            bullets = listOf(
                "Character resources packaged in the APK for rendering stroke order.",
                "Local practice history, HSK progress, and resume state.",
                "Board preferences such as grids, colors, template visibility, and language override.",
                "Recent dictionary searches stored on-device.",
                "Daily reminder preferences (enabled/time/rules) stored on-device.",
                "No advertising, no in-app purchases.",
            ),
        ),
        PolicySectionText(
            title = "2. How data is used",
            bullets = listOf(
                "Resume practice and course progress locally.",
                "Display dictionary cards and HSK summaries fully offline.",
                "Compute progress and streaks locally.",
            ),
        ),
        PolicySectionText(
            title = "3. Permissions",
            bullets = listOf(
                "POST_NOTIFICATIONS (Android 13+): optional, used for daily reminder notifications if enabled.",
                "RECEIVE_BOOT_COMPLETED: restore reminders after reboot, app update, or time changes.",
                "No network permission required. The app works offline.",
                "No access to precise location, contacts, camera, or microphone.",
            ),
        ),
        PolicySectionText(
            title = "4. Your controls",
            bullets = listOf(
                "Clear the app's storage in Android settings to reset all data.",
                "All data stays on this device unless you back up your phone.",
            ),
        ),
        PolicySectionText(
            title = "5. Contact",
            bullets = listOf(
                "Email: qq260316514@gmail.com",
            ),
        ),
    ),
                    progress = ProgressStrings(
        title = "Progress",
        description = "Check streaks, HSK completion, and the latest practice records. Everything refreshes automatically whenever you trace a new character.",
        jumpBackLabel = "Back to Practice",
        dailyTitle = "Daily",
        dailyDescription = "Practice one character a day. Suggested from your next HSK target.",
        dailyPracticeLabel = "Practice",
        dailyCompletedLabel = "Completed today",
        learnedLabel = "Learned",
        streakLabel = "Streak",
        lastSessionLabel = "Last session",
        streakDaySingularFormat = "%1\$d day",
        streakDayPluralFormat = "%1\$d days",
        streakStartLabel = "Start",
        lastSessionNeverLabel = "Never",
        weeklyChartTitle = "Last 7 days",
        levelsTitle = "Levels",
        levelsEmpty = "Start a practice session to see each HSK level tracked here.",
        levelLabelFormat = "HSK %1\$d",
        levelMasteredFormat = "%1\$d/%2\$d mastered",
        levelJumpDescription = "Jump to the next character",
        levelBrowseCourses = "Browse courses",
        historyTitle = "Recent practice",
        historyEmpty = "Trace any character and it shows up here for a quick review.",
        historyStrokesFormat = "%1\$d strokes \u00b7 %2\$s",
        historyMistakesPerfect = "Perfect run",
        historyMistakesFormat = "%1\$d mistakes",
        historyLoadCharacterFormat = "Load %1\$s",
        relativeJustNow = "just now",
        relativeMinutesFormat = "%1\$d min ago",
        relativeHoursFormat = "%1\$d hr ago",
        relativeDaysFormat = "%1\$d d ago",
    ),
    library = defaultLibraryStrings,
    courses = defaultCoursesStrings,
    account = defaultAccountStrings,
    support = defaultSupportStrings,
    boardControls = defaultPracticeBoardStrings,
)

private fun localizedStringsJa(locale: Locale): LocalizedStrings {
    val base = localizedStringsEn(locale)
    return base.copy(
        locale = locale,
        appTitle = "\u6f22\u5b57\u7b46\u9806",
        navigation = japaneseNavigationStrings,
        onboarding = japaneseOnboardingStrings,
        searchLabel = "\u6f22\u5b57",
        loadButton = "\u6587\u5b57\u3092\u8aad\u307f\u8fbc\u3080",
        clearButton = "\u30af\u30ea\u30a2",
        loadingLabel = "\u8aad\u307f\u8fbc\u307f\u4e2d...",
        coursesDialogTitle = "HSK\u30b3\u30fc\u30b9",
        coursePlanHeading = "\u7d9a\u3051\u308b\u30b3\u30fc\u30b9\u3092\u9078\u3076",
        courseIntroTitle = "\u30b3\u30fc\u30b9\u306e\u4ed5\u7d44\u307f",
        courseIntroBullets = listOf(
            "HSK\u30ec\u30d9\u30eb\u3092\u9078\u3093\u3067\u958b\u59cb\u3057\u3001\u4e2d\u65ad\u3057\u305f\u5834\u6240\u304b\u3089\u518d\u958b\u3067\u304d\u307e\u3059",
            "\u6587\u5b57\u3092\u30bf\u30c3\u30d7\u3059\u308b\u3068\u7df4\u7fd2\u3001\u9577\u62bc\u3057\u3067\u7fd2\u5f97\u6e08\u307f\u306b\u3067\u304d\u307e\u3059",
            "\u30dc\u30fc\u30c9\u4e0a\u306e\u30d0\u30c3\u30b8\u304c\u73fe\u5728\u306e\u9032\u6357\u3092\u5e38\u306b\u8868\u793a\u3057\u307e\u3059",
        ),
        courseEmptyTitle = "\u307e\u3060\u30b3\u30fc\u30b9\u304c\u3042\u308a\u307e\u305b\u3093",
        courseEmptyDescription = "\u4e0b\u306eHSK\u30ec\u30d9\u30eb\u3092\u9078\u3093\u3067\u30ac\u30a4\u30c9\u4ed8\u304d\u30bb\u30c3\u30b7\u30e7\u30f3\u3092\u59cb\u3081\u307e\u3057\u3087\u3046",
        courseNoDataMessage = "\u30b3\u30fc\u30b9\u30c7\u30fc\u30bf\u304c\u898b\u3064\u304b\u308a\u307e\u305b\u3093\u3002\u30ea\u30bd\u30fc\u30b9\u30d1\u30c3\u30af\u3092\u78ba\u8a8d\u3057\u3066\u304f\u3060\u3055\u3044",
        expandCharactersLabel = "\u3059\u3079\u3066\u8868\u793a",
        collapseCharactersLabel = "\u96a0\u3059",
        legendTitle = "\u51e1\u4f8b\u3068\u64cd\u4f5c",
        legendGesture = "\u6587\u5b57\u3092\u30bf\u30c3\u30d7\u3057\u3066\u7df4\u7fd2\u3001\u9577\u62bc\u3057\u3067\u7fd2\u5f97\u6e08\u307f\u306b\u3057\u307e\u3059",
        courseLegendHint = "\u30d0\u30c3\u30b8\u304b\u3089\u518d\u958b\u30fb\u30b9\u30ad\u30c3\u30d7\u30fb\u3084\u308a\u76f4\u3057\u30fb\u7d42\u4e86\u304c\u3067\u304d\u307e\u3059",
        helpTitle = "\u30d8\u30eb\u30d7",
        helpConfirm = "\u4e86\u89e3",
        privacyTitle = "\u30d7\u30e9\u30a4\u30d0\u30b7\u30fc",
        privacyIntro = "\u30aa\u30d5\u30e9\u30a4\u30f3\u512a\u5148\u3002",
        contactSupportLabel = "\u304a\u554f\u3044\u5408\u308f\u305b: %s",
        emailSupportButton = "\u30e1\u30fc\u30eb\u3067\u9023\u7d61",
        viewPolicyButton = "\u30dd\u30ea\u30b7\u30fc\u5168\u6587",
        courses = japaneseCoursesStrings,
        account = japaneseAccountStrings,
        support = japaneseSupportStrings,
        progress = japaneseProgressStrings,
        library = japaneseLibraryStrings,
        boardControls = japanesePracticeBoardStrings,
    )
}

private fun localizedStringsEs(locale: Locale): LocalizedStrings = LocalizedStrings(
    locale = locale,
    appTitle = "中国字笔顺",
    navigation = spanishNavigationStrings,
    onboarding = spanishOnboardingStrings,
    searchLabel = "Hanzi",
    loadButton = "Cargar carácter",
    clearButton = "Borrar",
    loadingLabel = "Cargando...",
    coursesDialogTitle = "Cursos HSK",
    coursePlanHeading = "Elige un curso para continuar",
    courseIntroTitle = "Cómo funcionan los cursos",
    courseIntroBullets = listOf(
        "Selecciona un nivel HSK para comenzar o retomar el estudio.",
        "Toca un carácter para practicar; mantén pulsado para marcarlo como dominado.",
        "La insignia sobre el tablero refleja tu progreso actual.",
    ),
    courseEmptyTitle = "Sin curso activo",
    courseEmptyDescription = "Selecciona un nivel HSK para iniciar una sesión guiada.",
    courseNoDataMessage = "No se encontraron datos del curso. Comprueba el paquete de recursos.",
    expandCharactersLabel = "Mostrar todo",
    collapseCharactersLabel = "Ocultar",
    legendTitle = "Leyenda y gestos",
    legendGesture = "Toca un carácter para practicar; mantén pulsado para marcarlo como aprendido.",
    legendActiveLabel = "Activo",
    legendCompletedLabel = "Completado",
    legendRemainingLabel = "Pendiente",
    courseLegendHint = "Usa los controles de la insignia para reanudar, saltar, reiniciar o salir sin cubrir el tablero.",
    courseLevelCompleteLabel = "Curso completo",
    courseLevelStartFormat = "Empieza con %s",
    courseLevelNextFormat = "Siguiente • %s",
    levelLabelFormat = "Nivel %d",
    courseLevelProgressFormat = "%1\$d/%2\$d dominados · faltan %3\$d",
    loadLevelFormat = "Abrir HSK %d",
    filterAllLabel = "Todos",
    filterRemainingLabel = "Pendientes",
    filterCompletedLabel = "Completados",
    helpTitle = "Ayuda e introducción",
    helpSections = listOf(
        HelpSectionText(
            title = "Inicio rápido",
            description = "Completa un ciclo de demostración → práctica en segundos.",
            bullets = listOf(
                "Escribe cualquier hanzi y toca el ícono de nube para cargar los datos sin conexión.",
                "Usa Reproducir o Bucle para ver la demostración; activa la plantilla caligráfica para calcar.",
                "Pulsa el lápiz en el tablero para empezar; el ícono de pista resalta el siguiente trazo.",
            ),
        ),
        HelpSectionText(
            title = "Cursos y progreso",
            description = "Los cursos HSK viven bajo el avatar y la insignia muestra tu estado.",
            bullets = listOf(
                "Los botones Reanudar/Saltar/Reiniciar/Salir permanecen en la insignia para no tapar el tablero.",
                "Las flechas cambian de carácter; al terminar uno se actualiza el resumen al instante.",
            ),
        ),
        HelpSectionText(
            title = "Tarjetas y pronunciación",
            description = "La tarjeta en caligrafía muestra el diccionario y la voz sintética.",
            bullets = listOf(
                "Toca la tarjeta para abrir la definición completa y desplazarte por la explicación.",
                "El botón de altavoz reproduce audio en mandarín sin conexión.",
            ),
        ),
        HelpSectionText(
            title = "Cuadrículas y plantillas",
            description = "El tablero admite cuadrícula mi, cuadrícula de nueve o sin guías.",
            bullets = listOf(
                "Cambia entre modo con plantilla o libre; los colores de los trazos se conservan.",
                "Desplázate fuera del lienzo para mover la página y mantener fija la zona de escritura.",
            ),
        ),
        HelpSectionText(
            title = "Soporte",
            description = "¿Necesitas ayuda? Escríbenos.",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
                "La app funciona sin conexión y nunca sube tus datos.",
            ),
        ),
    ),
    helpConfirm = "Entendido",
    privacyTitle = "Privacidad",
    privacyIntro = "Funciona sin conexión por defecto.",
    dataSafetyHeading = "Resumen de seguridad de datos",
    privacySummaryRows = listOf(
        SummaryRowText(
            title = "Almacenamiento",
            detail = "Historial de práctica, progreso y ajustes del tablero permanecen solo en DataStore local.",
        ),
        SummaryRowText(
            title = "Recursos sin conexión",
            detail = "Los paquetes de trazos y cursos vienen en el APK.",
        ),
        SummaryRowText(
            title = "Notificaciones",
            detail = "Recordatorios diarios opcionales. En Android 13+ la app solicita permiso de notificaciones solo si activas los recordatorios.",
        ),
        SummaryRowText(
            title = "Red",
            detail = "Sin permiso de red. La app no accede a internet ni sube tus datos.",
        ),
    ),
    contactSupportLabel = "Contacto: %s",
    emailSupportButton = "Enviar correo",
    viewPolicyButton = "Ver política completa",
    fullPolicyTitle = "Política de privacidad",
    fullPolicySections = listOf(
        PolicySectionText(
            title = "1. Datos que recopilamos",
            bullets = listOf(
                "Recursos de caracteres incluidos en el APK para mostrar el orden de los trazos.",
                "Historial local de práctica, progreso HSK y estado de reanudación.",
                "Preferencias del tablero y ajuste de idioma guardados localmente.",
                "Búsquedas recientes del diccionario guardadas en el dispositivo.",
                "Preferencias de recordatorios diarios (activado/hora/reglas) guardadas en el dispositivo.",
                "Sin anuncios ni compras dentro de la app.",
            ),
        ),
        PolicySectionText(
            title = "2. Uso de los datos",
            bullets = listOf(
                "Reanudar práctica y cursos localmente.",
                "Mostrar tarjetas y resúmenes HSK totalmente sin conexión.",
                "Calcular progreso y rachas en el dispositivo.",
            ),
        ),
        PolicySectionText(
            title = "3. Permisos",
            bullets = listOf(
                "POST_NOTIFICATIONS (Android 13+): opcional, para mostrar recordatorios diarios si están activados.",
                "RECEIVE_BOOT_COMPLETED: restaura los recordatorios tras reiniciar el dispositivo o cambiar la hora.",
                "No requiere permiso de red. Funciona sin conexión.",
                "Sin acceso a ubicación precisa, contactos, cámara o micrófono.",
            ),
        ),
        PolicySectionText(
            title = "4. Tus controles",
            bullets = listOf(
                "Borra los datos de la app en Ajustes de Android para reiniciar todo.",
                "Los datos se quedan en tu dispositivo salvo copias de seguridad del sistema.",
            ),
        ),
        PolicySectionText(
            title = "5. Contacto",
            bullets = listOf(
                "Correo: qq260316514@gmail.com",
            ),
        ),
    ),
    progress = ProgressStrings(
        title = "Progreso",
        description = "Consulta rachas, finalización de HSK y el historial de práctica más reciente. Todo se actualiza automáticamente al trazar nuevos caracteres.",
        jumpBackLabel = "Volver a Práctica",
        dailyTitle = "Diario",
        dailyDescription = "Practica un carácter al día. Sugerido a partir de tu próximo objetivo HSK.",
        dailyPracticeLabel = "Practicar",
        dailyCompletedLabel = "Completado hoy",
        learnedLabel = "Aprendidos",
        streakLabel = "Racha",
        lastSessionLabel = "Última sesión",
        streakDaySingularFormat = "%1\$d día",
        streakDayPluralFormat = "%1\$d días",
        streakStartLabel = "Comienza",
        lastSessionNeverLabel = "Nunca",
        weeklyChartTitle = "Últimos 7 días",
        levelsTitle = "Niveles",
        levelsEmpty = "Inicia una sesión de práctica para ver los niveles HSK aquí.",
        levelLabelFormat = "HSK %1\$d",
        levelMasteredFormat = "%1\$d/%2\$d dominados",
        levelJumpDescription = "Ir al siguiente carácter",
        levelBrowseCourses = "Ver cursos",
        historyTitle = "Práctica reciente",
        historyEmpty = "Cuando traces un carácter aparecerá aquí para repasarlo rápidamente.",
        historyStrokesFormat = "%1\$d trazos · %2\$s",
        historyMistakesPerfect = "Sin errores",
        historyMistakesFormat = "%1\$d errores",
        historyLoadCharacterFormat = "Cargar %1\$s",
        relativeJustNow = "justo ahora",
        relativeMinutesFormat = "hace %1\$d min",
        relativeHoursFormat = "hace %1\$d h",
        relativeDaysFormat = "hace %1\$d d",
    ),
    library = spanishLibraryStrings,
    courses = spanishCoursesStrings,
    account = spanishAccountStrings,
    support = spanishSupportStrings,
    boardControls = spanishPracticeBoardStrings,
)

